// Code generated by javagen. DO NOT EDIT.

package navigation

import "github.com/AndroidGoLab/jni/com/google/android/material/navigation/consts"

const (
	Creator                  = consts.Creator
	LabelVisibilityAuto      = consts.LabelVisibilityAuto
	LabelVisibilitySelected  = consts.LabelVisibilitySelected
	LabelVisibilityLabeled   = consts.LabelVisibilityLabeled
	LabelVisibilityUnlabeled = consts.LabelVisibilityUnlabeled
)
