// Code generated by javagen. DO NOT EDIT.

package datatypes

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// FloorsClimbedRecord wraps android.health.connect.datatypes.FloorsClimbedRecord.
type FloorsClimbedRecord struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// Equals calls android.health.connect.datatypes.FloorsClimbedRecord.equals.
func (m *FloorsClimbedRecord) Equals(arg0 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midFloorsClimbedRecordEquals == nil {
			callErr = fmt.Errorf("android.health.connect.datatypes.FloorsClimbedRecord.equals is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midFloorsClimbedRecordEquals, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// GetFloors calls android.health.connect.datatypes.FloorsClimbedRecord.getFloors.
func (m *FloorsClimbedRecord) GetFloors() (float64, error) {
	var result float64
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midFloorsClimbedRecordGetFloors == nil {
			callErr = fmt.Errorf("android.health.connect.datatypes.FloorsClimbedRecord.getFloors is not available on this device")
			return callErr
		}
		result, callErr = env.CallDoubleMethod(
			m.Obj,
			midFloorsClimbedRecordGetFloors,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// ToString calls android.health.connect.datatypes.FloorsClimbedRecord.toString.
func (m *FloorsClimbedRecord) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midFloorsClimbedRecordToString == nil {
			callErr = fmt.Errorf("android.health.connect.datatypes.FloorsClimbedRecord.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midFloorsClimbedRecordToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// HashCode calls android.health.connect.datatypes.FloorsClimbedRecord.hashCode.
func (m *FloorsClimbedRecord) HashCode() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midFloorsClimbedRecordHashCode == nil {
			callErr = fmt.Errorf("android.health.connect.datatypes.FloorsClimbedRecord.hashCode is not available on this device")
			return callErr
		}
		result, callErr = env.CallStaticIntMethod(
			(*jni.Class)(unsafe.Pointer(clsFloorsClimbedRecord)),
			midFloorsClimbedRecordHashCode,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}
