// Code generated by javagen. DO NOT EDIT.

package center.dx.jni.generated.android.accessibilityservice;


import android.accessibilityservice.FingerprintGestureController;
import center.dx.jni.internal.GoAbstractDispatch;


public class FingerprintGestureController$FingerprintGestureCallbackAdapter extends FingerprintGestureController.FingerprintGestureCallback {
    private final long handlerID;

    public FingerprintGestureController$FingerprintGestureCallbackAdapter(long handlerID) {
        this.handlerID = handlerID;
    }

    @Override
    public void onGestureDetected(int arg0) {
        GoAbstractDispatch.invoke(
            handlerID, "onGestureDetected", new Object[]{ Integer.valueOf(arg0) });
    }

    @Override
    public void onGestureDetectionAvailabilityChanged(boolean arg0) {
        GoAbstractDispatch.invoke(
            handlerID, "onGestureDetectionAvailabilityChanged", new Object[]{ Boolean.valueOf(arg0) });
    }
}
