// Code generated by javagen. DO NOT EDIT.

package graphics

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// PathMeasure wraps android.graphics.PathMeasure.
type PathMeasure struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// NewPathMeasure creates a new android.graphics.PathMeasure instance.
func NewPathMeasure(vm *jni.VM) (*PathMeasure, error) {
	var t PathMeasure
	t.VM = vm

	err := vm.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			return err
		}
		if clsPathMeasure == nil {
			return fmt.Errorf("android.graphics.PathMeasure is not available on this device")
		}
		if midPathMeasureCtor == nil {
			return fmt.Errorf("android.graphics.PathMeasure constructor ()V is not available on this device")
		}
		obj, err := env.NewObject((*jni.Class)(unsafe.Pointer(clsPathMeasure)), midPathMeasureCtor)
		if err != nil {
			return err
		}
		t.Obj = env.NewGlobalRef(obj)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// GetLength calls android.graphics.PathMeasure.getLength.
func (m *PathMeasure) GetLength() (float32, error) {
	var result float32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPathMeasureGetLength == nil {
			callErr = fmt.Errorf("android.graphics.PathMeasure.getLength is not available on this device")
			return callErr
		}
		result, callErr = env.CallFloatMethod(
			m.Obj,
			midPathMeasureGetLength,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetMatrix calls android.graphics.PathMeasure.getMatrix.
func (m *PathMeasure) GetMatrix(
	arg0 float32,
	arg1 *jni.Object,
	arg2 int32,
) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPathMeasureGetMatrix == nil {
			callErr = fmt.Errorf("android.graphics.PathMeasure.getMatrix is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midPathMeasureGetMatrix, jni.FloatValue(arg0), jni.ObjectValue(arg1), jni.IntValue(arg2),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// GetPosTan calls android.graphics.PathMeasure.getPosTan.
func (m *PathMeasure) GetPosTan(
	arg0 float32,
	arg1 *jni.Object,
	arg2 *jni.Object,
) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPathMeasureGetPosTan == nil {
			callErr = fmt.Errorf("android.graphics.PathMeasure.getPosTan is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midPathMeasureGetPosTan, jni.FloatValue(arg0), jni.ObjectValue(arg1), jni.ObjectValue(arg2),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// GetSegment calls android.graphics.PathMeasure.getSegment.
func (m *PathMeasure) GetSegment(
	arg0 float32,
	arg1 float32,
	arg2 *jni.Object,
	arg3 bool,
) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPathMeasureGetSegment == nil {
			callErr = fmt.Errorf("android.graphics.PathMeasure.getSegment is not available on this device")
			return callErr
		}

		var jArg3 uint8
		if arg3 {
			jArg3 = jniTrue
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midPathMeasureGetSegment, jni.FloatValue(arg0), jni.FloatValue(arg1), jni.ObjectValue(arg2), jni.BooleanValue(jArg3),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// IsClosed calls android.graphics.PathMeasure.isClosed.
func (m *PathMeasure) IsClosed() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPathMeasureIsClosed == nil {
			callErr = fmt.Errorf("android.graphics.PathMeasure.isClosed is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midPathMeasureIsClosed,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// NextContour calls android.graphics.PathMeasure.nextContour.
func (m *PathMeasure) NextContour() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPathMeasureNextContour == nil {
			callErr = fmt.Errorf("android.graphics.PathMeasure.nextContour is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midPathMeasureNextContour,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// SetPath calls android.graphics.PathMeasure.setPath.
func (m *PathMeasure) SetPath(arg0 *jni.Object, arg1 bool) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPathMeasureSetPath == nil {
			callErr = fmt.Errorf("android.graphics.PathMeasure.setPath is not available on this device")
			return callErr
		}

		var jArg1 uint8
		if arg1 {
			jArg1 = jniTrue
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midPathMeasureSetPath, jni.ObjectValue(arg0), jni.BooleanValue(jArg1),
		)
		return callErr
	})
	return callErr
}

// ToString calls android.graphics.PathMeasure.toString.
func (m *PathMeasure) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPathMeasureToString == nil {
			callErr = fmt.Errorf("android.graphics.PathMeasure.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midPathMeasureToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
