// Code generated by javagen. DO NOT EDIT.

package graphics

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// Rect wraps android.graphics.Rect.
type Rect struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// NewRect creates a new android.graphics.Rect instance.
func NewRect(vm *jni.VM) (*Rect, error) {
	var t Rect
	t.VM = vm

	err := vm.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			return err
		}
		if clsRect == nil {
			return fmt.Errorf("android.graphics.Rect is not available on this device")
		}
		if midRectCtor == nil {
			return fmt.Errorf("android.graphics.Rect constructor ()V is not available on this device")
		}
		obj, err := env.NewObject((*jni.Class)(unsafe.Pointer(clsRect)), midRectCtor)
		if err != nil {
			return err
		}
		t.Obj = env.NewGlobalRef(obj)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// CenterX calls android.graphics.Rect.centerX.
func (m *Rect) CenterX() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectCenterX == nil {
			callErr = fmt.Errorf("android.graphics.Rect.centerX is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midRectCenterX,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// CenterY calls android.graphics.Rect.centerY.
func (m *Rect) CenterY() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectCenterY == nil {
			callErr = fmt.Errorf("android.graphics.Rect.centerY is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midRectCenterY,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// Contains1 calls android.graphics.Rect.contains.
func (m *Rect) Contains1(arg0 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectContains1 == nil {
			callErr = fmt.Errorf("android.graphics.Rect.contains is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midRectContains1, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// Contains2_1 calls android.graphics.Rect.contains.
func (m *Rect) Contains2_1(arg0 int32, arg1 int32) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectContains2_1 == nil {
			callErr = fmt.Errorf("android.graphics.Rect.contains is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midRectContains2_1, jni.IntValue(arg0), jni.IntValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// Contains4_2 calls android.graphics.Rect.contains.
func (m *Rect) Contains4_2(
	arg0 int32,
	arg1 int32,
	arg2 int32,
	arg3 int32,
) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectContains4_2 == nil {
			callErr = fmt.Errorf("android.graphics.Rect.contains is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midRectContains4_2, jni.IntValue(arg0), jni.IntValue(arg1), jni.IntValue(arg2), jni.IntValue(arg3),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// DescribeContents calls android.graphics.Rect.describeContents.
func (m *Rect) DescribeContents() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectDescribeContents == nil {
			callErr = fmt.Errorf("android.graphics.Rect.describeContents is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midRectDescribeContents,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// Equals calls android.graphics.Rect.equals.
func (m *Rect) Equals(arg0 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectEquals == nil {
			callErr = fmt.Errorf("android.graphics.Rect.equals is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midRectEquals, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// ExactCenterX calls android.graphics.Rect.exactCenterX.
func (m *Rect) ExactCenterX() (float32, error) {
	var result float32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectExactCenterX == nil {
			callErr = fmt.Errorf("android.graphics.Rect.exactCenterX is not available on this device")
			return callErr
		}
		result, callErr = env.CallFloatMethod(
			m.Obj,
			midRectExactCenterX,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// ExactCenterY calls android.graphics.Rect.exactCenterY.
func (m *Rect) ExactCenterY() (float32, error) {
	var result float32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectExactCenterY == nil {
			callErr = fmt.Errorf("android.graphics.Rect.exactCenterY is not available on this device")
			return callErr
		}
		result, callErr = env.CallFloatMethod(
			m.Obj,
			midRectExactCenterY,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// FlattenToString calls android.graphics.Rect.flattenToString.
func (m *Rect) FlattenToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectFlattenToString == nil {
			callErr = fmt.Errorf("android.graphics.Rect.flattenToString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midRectFlattenToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// HashCode calls android.graphics.Rect.hashCode.
func (m *Rect) HashCode() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectHashCode == nil {
			callErr = fmt.Errorf("android.graphics.Rect.hashCode is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midRectHashCode,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// Height calls android.graphics.Rect.height.
func (m *Rect) Height() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectHeight == nil {
			callErr = fmt.Errorf("android.graphics.Rect.height is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midRectHeight,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// Inset1 calls android.graphics.Rect.inset.
func (m *Rect) Inset1(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectInset1 == nil {
			callErr = fmt.Errorf("android.graphics.Rect.inset is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midRectInset1, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// Inset2_1 calls android.graphics.Rect.inset.
func (m *Rect) Inset2_1(arg0 int32, arg1 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectInset2_1 == nil {
			callErr = fmt.Errorf("android.graphics.Rect.inset is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midRectInset2_1, jni.IntValue(arg0), jni.IntValue(arg1),
		)
		return callErr
	})
	return callErr
}

// Inset4_2 calls android.graphics.Rect.inset.
func (m *Rect) Inset4_2(
	arg0 int32,
	arg1 int32,
	arg2 int32,
	arg3 int32,
) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectInset4_2 == nil {
			callErr = fmt.Errorf("android.graphics.Rect.inset is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midRectInset4_2, jni.IntValue(arg0), jni.IntValue(arg1), jni.IntValue(arg2), jni.IntValue(arg3),
		)
		return callErr
	})
	return callErr
}

// Intersect1 calls android.graphics.Rect.intersect.
func (m *Rect) Intersect1(arg0 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectIntersect1 == nil {
			callErr = fmt.Errorf("android.graphics.Rect.intersect is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midRectIntersect1, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// Intersect4_1 calls android.graphics.Rect.intersect.
func (m *Rect) Intersect4_1(
	arg0 int32,
	arg1 int32,
	arg2 int32,
	arg3 int32,
) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectIntersect4_1 == nil {
			callErr = fmt.Errorf("android.graphics.Rect.intersect is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midRectIntersect4_1, jni.IntValue(arg0), jni.IntValue(arg1), jni.IntValue(arg2), jni.IntValue(arg3),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// Intersects4_1 calls android.graphics.Rect.intersects.
func (m *Rect) Intersects4_1(
	arg0 int32,
	arg1 int32,
	arg2 int32,
	arg3 int32,
) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectIntersects4_1 == nil {
			callErr = fmt.Errorf("android.graphics.Rect.intersects is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midRectIntersects4_1, jni.IntValue(arg0), jni.IntValue(arg1), jni.IntValue(arg2), jni.IntValue(arg3),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// IsEmpty calls android.graphics.Rect.isEmpty.
func (m *Rect) IsEmpty() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectIsEmpty == nil {
			callErr = fmt.Errorf("android.graphics.Rect.isEmpty is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midRectIsEmpty,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// Offset calls android.graphics.Rect.offset.
func (m *Rect) Offset(arg0 int32, arg1 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectOffset == nil {
			callErr = fmt.Errorf("android.graphics.Rect.offset is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midRectOffset, jni.IntValue(arg0), jni.IntValue(arg1),
		)
		return callErr
	})
	return callErr
}

// OffsetTo calls android.graphics.Rect.offsetTo.
func (m *Rect) OffsetTo(arg0 int32, arg1 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectOffsetTo == nil {
			callErr = fmt.Errorf("android.graphics.Rect.offsetTo is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midRectOffsetTo, jni.IntValue(arg0), jni.IntValue(arg1),
		)
		return callErr
	})
	return callErr
}

// ReadFromParcel calls android.graphics.Rect.readFromParcel.
func (m *Rect) ReadFromParcel(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectReadFromParcel == nil {
			callErr = fmt.Errorf("android.graphics.Rect.readFromParcel is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midRectReadFromParcel, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// Set1 calls android.graphics.Rect.set.
func (m *Rect) Set1(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectSet1 == nil {
			callErr = fmt.Errorf("android.graphics.Rect.set is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midRectSet1, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// Set4_1 calls android.graphics.Rect.set.
func (m *Rect) Set4_1(
	arg0 int32,
	arg1 int32,
	arg2 int32,
	arg3 int32,
) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectSet4_1 == nil {
			callErr = fmt.Errorf("android.graphics.Rect.set is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midRectSet4_1, jni.IntValue(arg0), jni.IntValue(arg1), jni.IntValue(arg2), jni.IntValue(arg3),
		)
		return callErr
	})
	return callErr
}

// SetEmpty calls android.graphics.Rect.setEmpty.
func (m *Rect) SetEmpty() error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectSetEmpty == nil {
			callErr = fmt.Errorf("android.graphics.Rect.setEmpty is not available on this device")
			return callErr
		}
		callErr = env.CallVoidMethod(
			m.Obj,
			midRectSetEmpty,
		)
		return callErr
	})
	return callErr
}

// SetIntersect calls android.graphics.Rect.setIntersect.
func (m *Rect) SetIntersect(arg0 *jni.Object, arg1 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectSetIntersect == nil {
			callErr = fmt.Errorf("android.graphics.Rect.setIntersect is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midRectSetIntersect, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// Sort calls android.graphics.Rect.sort.
func (m *Rect) Sort() error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectSort == nil {
			callErr = fmt.Errorf("android.graphics.Rect.sort is not available on this device")
			return callErr
		}
		callErr = env.CallVoidMethod(
			m.Obj,
			midRectSort,
		)
		return callErr
	})
	return callErr
}

// ToShortString calls android.graphics.Rect.toShortString.
func (m *Rect) ToShortString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectToShortString == nil {
			callErr = fmt.Errorf("android.graphics.Rect.toShortString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midRectToShortString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// ToString calls android.graphics.Rect.toString.
func (m *Rect) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectToString == nil {
			callErr = fmt.Errorf("android.graphics.Rect.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midRectToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// Union1 calls android.graphics.Rect.union.
func (m *Rect) Union1(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectUnion1 == nil {
			callErr = fmt.Errorf("android.graphics.Rect.union is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midRectUnion1, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// Union2_1 calls android.graphics.Rect.union.
func (m *Rect) Union2_1(arg0 int32, arg1 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectUnion2_1 == nil {
			callErr = fmt.Errorf("android.graphics.Rect.union is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midRectUnion2_1, jni.IntValue(arg0), jni.IntValue(arg1),
		)
		return callErr
	})
	return callErr
}

// Union4_2 calls android.graphics.Rect.union.
func (m *Rect) Union4_2(
	arg0 int32,
	arg1 int32,
	arg2 int32,
	arg3 int32,
) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectUnion4_2 == nil {
			callErr = fmt.Errorf("android.graphics.Rect.union is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midRectUnion4_2, jni.IntValue(arg0), jni.IntValue(arg1), jni.IntValue(arg2), jni.IntValue(arg3),
		)
		return callErr
	})
	return callErr
}

// Width calls android.graphics.Rect.width.
func (m *Rect) Width() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectWidth == nil {
			callErr = fmt.Errorf("android.graphics.Rect.width is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midRectWidth,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// Intersects2 calls android.graphics.Rect.intersects.
func (m *Rect) Intersects2(arg0 *jni.Object, arg1 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectIntersects2 == nil {
			callErr = fmt.Errorf("android.graphics.Rect.intersects is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallStaticBooleanMethod(
			(*jni.Class)(unsafe.Pointer(clsRect)),
			midRectIntersects2, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// UnflattenFromString calls android.graphics.Rect.unflattenFromString.
func (m *Rect) UnflattenFromString(arg0 string) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectUnflattenFromString == nil {
			callErr = fmt.Errorf("android.graphics.Rect.unflattenFromString is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		result, callErr = env.CallStaticObjectMethod(
			(*jni.Class)(unsafe.Pointer(clsRect)),
			midRectUnflattenFromString, jni.ObjectValue(&jArg0.Object),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// WriteToParcel calls android.graphics.Rect.writeToParcel.
func (m *Rect) WriteToParcel(arg0 *jni.Object, arg1 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectWriteToParcel == nil {
			callErr = fmt.Errorf("android.graphics.Rect.writeToParcel is not available on this device")
			return callErr
		}

		callErr = env.CallStaticVoidMethod(
			(*jni.Class)(unsafe.Pointer(clsRect)),
			midRectWriteToParcel, jni.ObjectValue(arg0), jni.IntValue(arg1),
		)
		return callErr
	})
	return callErr
}
