// Code generated by javagen. DO NOT EDIT.

package drawable

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// Utils wraps com.google.android.material.drawable.DrawableUtils.
type Utils struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// ToString calls com.google.android.material.drawable.DrawableUtils.toString.
func (m *Utils) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midUtilsToString == nil {
			callErr = fmt.Errorf("com.google.android.material.drawable.DrawableUtils.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midUtilsToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// SetTint calls com.google.android.material.drawable.DrawableUtils.setTint.
func (m *Utils) SetTint(arg0 *jni.Object, arg1 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midUtilsSetTint == nil {
			callErr = fmt.Errorf("com.google.android.material.drawable.DrawableUtils.setTint is not available on this device")
			return callErr
		}

		callErr = env.CallStaticVoidMethod(
			(*jni.Class)(unsafe.Pointer(clsUtils)),
			midUtilsSetTint, jni.ObjectValue(arg0), jni.IntValue(arg1),
		)
		return callErr
	})
	return callErr
}

// UpdateTintFilter calls com.google.android.material.drawable.DrawableUtils.updateTintFilter.
func (m *Utils) UpdateTintFilter(
	arg0 *jni.Object,
	arg1 *jni.Object,
	arg2 *jni.Object,
) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midUtilsUpdateTintFilter == nil {
			callErr = fmt.Errorf("com.google.android.material.drawable.DrawableUtils.updateTintFilter is not available on this device")
			return callErr
		}

		result, callErr = env.CallStaticObjectMethod(
			(*jni.Class)(unsafe.Pointer(clsUtils)),
			midUtilsUpdateTintFilter, jni.ObjectValue(arg0), jni.ObjectValue(arg1), jni.ObjectValue(arg2),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// ParseDrawableXml calls com.google.android.material.drawable.DrawableUtils.parseDrawableXml.
func (m *Utils) ParseDrawableXml(
	arg0 *jni.Object,
	arg1 int32,
	arg2 string,
) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midUtilsParseDrawableXml == nil {
			callErr = fmt.Errorf("com.google.android.material.drawable.DrawableUtils.parseDrawableXml is not available on this device")
			return callErr
		}

		jArg2, err := env.NewStringUTF(arg2)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg2.Object)

		result, callErr = env.CallStaticObjectMethod(
			(*jni.Class)(unsafe.Pointer(clsUtils)),
			midUtilsParseDrawableXml, jni.ObjectValue(arg0), jni.IntValue(arg1), jni.ObjectValue(&jArg2.Object),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetRippleDrawableRadius calls com.google.android.material.drawable.DrawableUtils.setRippleDrawableRadius.
func (m *Utils) SetRippleDrawableRadius(arg0 *jni.Object, arg1 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midUtilsSetRippleDrawableRadius == nil {
			callErr = fmt.Errorf("com.google.android.material.drawable.DrawableUtils.setRippleDrawableRadius is not available on this device")
			return callErr
		}

		callErr = env.CallStaticVoidMethod(
			(*jni.Class)(unsafe.Pointer(clsUtils)),
			midUtilsSetRippleDrawableRadius, jni.ObjectValue(arg0), jni.IntValue(arg1),
		)
		return callErr
	})
	return callErr
}

// CreateTintableDrawableIfNeeded calls com.google.android.material.drawable.DrawableUtils.createTintableDrawableIfNeeded.
func (m *Utils) CreateTintableDrawableIfNeeded(
	arg0 *jni.Object,
	arg1 *jni.Object,
	arg2 *jni.Object,
) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midUtilsCreateTintableDrawableIfNeeded == nil {
			callErr = fmt.Errorf("com.google.android.material.drawable.DrawableUtils.createTintableDrawableIfNeeded is not available on this device")
			return callErr
		}

		result, callErr = env.CallStaticObjectMethod(
			(*jni.Class)(unsafe.Pointer(clsUtils)),
			midUtilsCreateTintableDrawableIfNeeded, jni.ObjectValue(arg0), jni.ObjectValue(arg1), jni.ObjectValue(arg2),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// CreateTintableMutatedDrawableIfNeeded calls com.google.android.material.drawable.DrawableUtils.createTintableMutatedDrawableIfNeeded.
func (m *Utils) CreateTintableMutatedDrawableIfNeeded(
	arg0 *jni.Object,
	arg1 *jni.Object,
	arg2 *jni.Object,
) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midUtilsCreateTintableMutatedDrawableIfNeeded == nil {
			callErr = fmt.Errorf("com.google.android.material.drawable.DrawableUtils.createTintableMutatedDrawableIfNeeded is not available on this device")
			return callErr
		}

		result, callErr = env.CallStaticObjectMethod(
			(*jni.Class)(unsafe.Pointer(clsUtils)),
			midUtilsCreateTintableMutatedDrawableIfNeeded, jni.ObjectValue(arg0), jni.ObjectValue(arg1), jni.ObjectValue(arg2),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// CompositeTwoLayeredDrawable2 calls com.google.android.material.drawable.DrawableUtils.compositeTwoLayeredDrawable.
func (m *Utils) CompositeTwoLayeredDrawable2(arg0 *jni.Object, arg1 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midUtilsCompositeTwoLayeredDrawable2 == nil {
			callErr = fmt.Errorf("com.google.android.material.drawable.DrawableUtils.compositeTwoLayeredDrawable is not available on this device")
			return callErr
		}

		result, callErr = env.CallStaticObjectMethod(
			(*jni.Class)(unsafe.Pointer(clsUtils)),
			midUtilsCompositeTwoLayeredDrawable2, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// CompositeTwoLayeredDrawable4_1 calls com.google.android.material.drawable.DrawableUtils.compositeTwoLayeredDrawable.
func (m *Utils) CompositeTwoLayeredDrawable4_1(
	arg0 *jni.Object,
	arg1 *jni.Object,
	arg2 int32,
	arg3 int32,
) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midUtilsCompositeTwoLayeredDrawable4_1 == nil {
			callErr = fmt.Errorf("com.google.android.material.drawable.DrawableUtils.compositeTwoLayeredDrawable is not available on this device")
			return callErr
		}

		result, callErr = env.CallStaticObjectMethod(
			(*jni.Class)(unsafe.Pointer(clsUtils)),
			midUtilsCompositeTwoLayeredDrawable4_1, jni.ObjectValue(arg0), jni.ObjectValue(arg1), jni.IntValue(arg2), jni.IntValue(arg3),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetCheckedState calls com.google.android.material.drawable.DrawableUtils.getCheckedState.
func (m *Utils) GetCheckedState(arg0 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midUtilsGetCheckedState == nil {
			callErr = fmt.Errorf("com.google.android.material.drawable.DrawableUtils.getCheckedState is not available on this device")
			return callErr
		}

		result, callErr = env.CallStaticObjectMethod(
			(*jni.Class)(unsafe.Pointer(clsUtils)),
			midUtilsGetCheckedState, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetUncheckedState calls com.google.android.material.drawable.DrawableUtils.getUncheckedState.
func (m *Utils) GetUncheckedState(arg0 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midUtilsGetUncheckedState == nil {
			callErr = fmt.Errorf("com.google.android.material.drawable.DrawableUtils.getUncheckedState is not available on this device")
			return callErr
		}

		result, callErr = env.CallStaticObjectMethod(
			(*jni.Class)(unsafe.Pointer(clsUtils)),
			midUtilsGetUncheckedState, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetOutlineToPath calls com.google.android.material.drawable.DrawableUtils.setOutlineToPath.
func (m *Utils) SetOutlineToPath(arg0 *jni.Object, arg1 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midUtilsSetOutlineToPath == nil {
			callErr = fmt.Errorf("com.google.android.material.drawable.DrawableUtils.setOutlineToPath is not available on this device")
			return callErr
		}

		callErr = env.CallStaticVoidMethod(
			(*jni.Class)(unsafe.Pointer(clsUtils)),
			midUtilsSetOutlineToPath, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		return callErr
	})
	return callErr
}

// GetColorStateListOrNull calls com.google.android.material.drawable.DrawableUtils.getColorStateListOrNull.
func (m *Utils) GetColorStateListOrNull(arg0 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midUtilsGetColorStateListOrNull == nil {
			callErr = fmt.Errorf("com.google.android.material.drawable.DrawableUtils.getColorStateListOrNull is not available on this device")
			return callErr
		}

		result, callErr = env.CallStaticObjectMethod(
			(*jni.Class)(unsafe.Pointer(clsUtils)),
			midUtilsGetColorStateListOrNull, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}
