// Code generated by javagen. DO NOT EDIT.

package center.dx.jni.generated;

import androidx.core.view.ActionProvider;
import center.dx.jni.internal.GoAbstractDispatch;

public class ActionProviderAdapter extends androidx.core.view.ActionProvider {
    private final long handlerID;

    public ActionProviderAdapter(long handlerID) {
        this.handlerID = handlerID;
    }

    @Override
    public android.content.Context getContext() {
        return (android.content.Context) GoAbstractDispatch.invoke(
            handlerID, "getContext", new Object[]{  });
    }

    @Override
    public android.view.View onCreateActionView() {
        return (android.view.View) GoAbstractDispatch.invoke(
            handlerID, "onCreateActionView", new Object[]{  });
    }

    @Override
    public android.view.View onCreateActionView(android.view.MenuItem arg0) {
        return (android.view.View) GoAbstractDispatch.invoke(
            handlerID, "onCreateActionView", new Object[]{ arg0 });
    }

    @Override
    public boolean overridesItemVisibility() {
        return (Boolean) GoAbstractDispatch.invoke(
            handlerID, "overridesItemVisibility", new Object[]{  }).booleanValue();
    }

    @Override
    public boolean isVisible() {
        return (Boolean) GoAbstractDispatch.invoke(
            handlerID, "isVisible", new Object[]{  }).booleanValue();
    }

    @Override
    public void refreshVisibility() {
        GoAbstractDispatch.invoke(
            handlerID, "refreshVisibility", new Object[]{  });
    }

    @Override
    public boolean onPerformDefaultAction() {
        return (Boolean) GoAbstractDispatch.invoke(
            handlerID, "onPerformDefaultAction", new Object[]{  }).booleanValue();
    }

    @Override
    public boolean hasSubMenu() {
        return (Boolean) GoAbstractDispatch.invoke(
            handlerID, "hasSubMenu", new Object[]{  }).booleanValue();
    }

    @Override
    public void onPrepareSubMenu(android.view.SubMenu arg0) {
        GoAbstractDispatch.invoke(
            handlerID, "onPrepareSubMenu", new Object[]{ arg0 });
    }

    @Override
    public void subUiVisibilityChanged(boolean arg0) {
        GoAbstractDispatch.invoke(
            handlerID, "subUiVisibilityChanged", new Object[]{ Boolean.valueOf(arg0) });
    }

    @Override
    public void setSubUiVisibilityListener(androidx.core.view.ActionProvider$SubUiVisibilityListener arg0) {
        GoAbstractDispatch.invoke(
            handlerID, "setSubUiVisibilityListener", new Object[]{ arg0 });
    }

    @Override
    public void setVisibilityListener(androidx.core.view.ActionProvider$VisibilityListener arg0) {
        GoAbstractDispatch.invoke(
            handlerID, "setVisibilityListener", new Object[]{ arg0 });
    }

    @Override
    public void reset() {
        GoAbstractDispatch.invoke(
            handlerID, "reset", new Object[]{  });
    }
}
