// Code generated by javagen. DO NOT EDIT.

package strictmode

import "github.com/AndroidGoLab/jni/androidx/fragment/app/strictmode/consts"

const (
	Instance                     = consts.Instance
	PenaltyLog                   = consts.PenaltyLog
	PenaltyDeath                 = consts.PenaltyDeath
	DetectFragmentReuse          = consts.DetectFragmentReuse
	DetectFragmentTagUsage       = consts.DetectFragmentTagUsage
	DetectRetainInstanceUsage    = consts.DetectRetainInstanceUsage
	DetectSetUserVisibleHint     = consts.DetectSetUserVisibleHint
	DetectTargetFragmentUsage    = consts.DetectTargetFragmentUsage
	DetectWrongFragmentContainer = consts.DetectWrongFragmentContainer
	Companion                    = consts.Companion
	Lax                          = consts.Lax
)
