// Code generated by javagen. DO NOT EDIT.

package text

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// DateIntervalInfo wraps android.icu.text.DateIntervalInfo.
type DateIntervalInfo struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// NewDateIntervalInfo creates a new android.icu.text.DateIntervalInfo instance.
func NewDateIntervalInfo(vm *jni.VM, arg0 *jni.Object) (*DateIntervalInfo, error) {
	var t DateIntervalInfo
	t.VM = vm

	err := vm.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			return err
		}
		if clsDateIntervalInfo == nil {
			return fmt.Errorf("android.icu.text.DateIntervalInfo is not available on this device")
		}
		if midDateIntervalInfoCtor == nil {
			return fmt.Errorf("android.icu.text.DateIntervalInfo constructor (Landroid/icu/util/ULocale;)V is not available on this device")
		}

		obj, err := env.NewObject((*jni.Class)(unsafe.Pointer(clsDateIntervalInfo)), midDateIntervalInfoCtor, jni.ObjectValue(arg0))
		if err != nil {
			return err
		}
		t.Obj = env.NewGlobalRef(obj)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// Clone calls android.icu.text.DateIntervalInfo.clone.
func (m *DateIntervalInfo) Clone() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDateIntervalInfoClone == nil {
			callErr = fmt.Errorf("android.icu.text.DateIntervalInfo.clone is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midDateIntervalInfoClone,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// CloneAsThawed calls android.icu.text.DateIntervalInfo.cloneAsThawed.
func (m *DateIntervalInfo) CloneAsThawed() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDateIntervalInfoCloneAsThawed == nil {
			callErr = fmt.Errorf("android.icu.text.DateIntervalInfo.cloneAsThawed is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midDateIntervalInfoCloneAsThawed,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// Equals calls android.icu.text.DateIntervalInfo.equals.
func (m *DateIntervalInfo) Equals(arg0 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDateIntervalInfoEquals == nil {
			callErr = fmt.Errorf("android.icu.text.DateIntervalInfo.equals is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midDateIntervalInfoEquals, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// Freeze calls android.icu.text.DateIntervalInfo.freeze.
func (m *DateIntervalInfo) Freeze() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDateIntervalInfoFreeze == nil {
			callErr = fmt.Errorf("android.icu.text.DateIntervalInfo.freeze is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midDateIntervalInfoFreeze,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetDefaultOrder calls android.icu.text.DateIntervalInfo.getDefaultOrder.
func (m *DateIntervalInfo) GetDefaultOrder() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDateIntervalInfoGetDefaultOrder == nil {
			callErr = fmt.Errorf("android.icu.text.DateIntervalInfo.getDefaultOrder is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midDateIntervalInfoGetDefaultOrder,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// GetFallbackIntervalPattern calls android.icu.text.DateIntervalInfo.getFallbackIntervalPattern.
func (m *DateIntervalInfo) GetFallbackIntervalPattern() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDateIntervalInfoGetFallbackIntervalPattern == nil {
			callErr = fmt.Errorf("android.icu.text.DateIntervalInfo.getFallbackIntervalPattern is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midDateIntervalInfoGetFallbackIntervalPattern,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// GetIntervalPattern calls android.icu.text.DateIntervalInfo.getIntervalPattern.
func (m *DateIntervalInfo) GetIntervalPattern(arg0 string, arg1 int32) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDateIntervalInfoGetIntervalPattern == nil {
			callErr = fmt.Errorf("android.icu.text.DateIntervalInfo.getIntervalPattern is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midDateIntervalInfoGetIntervalPattern, jni.ObjectValue(&jArg0.Object), jni.IntValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// HashCode calls android.icu.text.DateIntervalInfo.hashCode.
func (m *DateIntervalInfo) HashCode() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDateIntervalInfoHashCode == nil {
			callErr = fmt.Errorf("android.icu.text.DateIntervalInfo.hashCode is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midDateIntervalInfoHashCode,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// IsFrozen calls android.icu.text.DateIntervalInfo.isFrozen.
func (m *DateIntervalInfo) IsFrozen() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDateIntervalInfoIsFrozen == nil {
			callErr = fmt.Errorf("android.icu.text.DateIntervalInfo.isFrozen is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midDateIntervalInfoIsFrozen,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// SetFallbackIntervalPattern calls android.icu.text.DateIntervalInfo.setFallbackIntervalPattern.
func (m *DateIntervalInfo) SetFallbackIntervalPattern(arg0 string) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDateIntervalInfoSetFallbackIntervalPattern == nil {
			callErr = fmt.Errorf("android.icu.text.DateIntervalInfo.setFallbackIntervalPattern is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		callErr = env.CallVoidMethod(
			m.Obj,
			midDateIntervalInfoSetFallbackIntervalPattern, jni.ObjectValue(&jArg0.Object),
		)
		return callErr
	})
	return callErr
}

// SetIntervalPattern calls android.icu.text.DateIntervalInfo.setIntervalPattern.
func (m *DateIntervalInfo) SetIntervalPattern(
	arg0 string,
	arg1 int32,
	arg2 string,
) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDateIntervalInfoSetIntervalPattern == nil {
			callErr = fmt.Errorf("android.icu.text.DateIntervalInfo.setIntervalPattern is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		jArg2, err := env.NewStringUTF(arg2)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg2.Object)

		callErr = env.CallVoidMethod(
			m.Obj,
			midDateIntervalInfoSetIntervalPattern, jni.ObjectValue(&jArg0.Object), jni.IntValue(arg1), jni.ObjectValue(&jArg2.Object),
		)
		return callErr
	})
	return callErr
}

// ToString calls android.icu.text.DateIntervalInfo.toString.
func (m *DateIntervalInfo) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDateIntervalInfoToString == nil {
			callErr = fmt.Errorf("android.icu.text.DateIntervalInfo.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midDateIntervalInfoToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
