// Code generated by javagen. DO NOT EDIT.

package color

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// DynamicColorsPrecondition wraps com.google.android.material.color.DynamicColors$Precondition.
type DynamicColorsPrecondition struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// ShouldApplyDynamicColors calls com.google.android.material.color.DynamicColors$Precondition.shouldApplyDynamicColors.
func (m *DynamicColorsPrecondition) ShouldApplyDynamicColors(arg0 *jni.Object, arg1 int32) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDynamicColorsPreconditionShouldApplyDynamicColors == nil {
			callErr = fmt.Errorf("com.google.android.material.color.DynamicColors$Precondition.shouldApplyDynamicColors is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midDynamicColorsPreconditionShouldApplyDynamicColors, jni.ObjectValue(arg0), jni.IntValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// ToString calls com.google.android.material.color.DynamicColors$Precondition.toString.
func (m *DynamicColorsPrecondition) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDynamicColorsPreconditionToString == nil {
			callErr = fmt.Errorf("com.google.android.material.color.DynamicColors$Precondition.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midDynamicColorsPreconditionToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
