// Code generated by javagen. DO NOT EDIT.

package internal

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// ViewOverlayImpl wraps com.google.android.material.internal.ViewOverlayImpl.
type ViewOverlayImpl struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// Add calls com.google.android.material.internal.ViewOverlayImpl.add.
func (m *ViewOverlayImpl) Add(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midViewOverlayImplAdd == nil {
			callErr = fmt.Errorf("com.google.android.material.internal.ViewOverlayImpl.add is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midViewOverlayImplAdd, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// Remove calls com.google.android.material.internal.ViewOverlayImpl.remove.
func (m *ViewOverlayImpl) Remove(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midViewOverlayImplRemove == nil {
			callErr = fmt.Errorf("com.google.android.material.internal.ViewOverlayImpl.remove is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midViewOverlayImplRemove, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// ToString calls com.google.android.material.internal.ViewOverlayImpl.toString.
func (m *ViewOverlayImpl) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midViewOverlayImplToString == nil {
			callErr = fmt.Errorf("com.google.android.material.internal.ViewOverlayImpl.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midViewOverlayImplToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
