// Code generated by javagen. DO NOT EDIT.

package widget

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// Barrier wraps androidx.constraintlayout.widget.Barrier.
type Barrier struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// NewBarrier creates a new androidx.constraintlayout.widget.Barrier instance.
func NewBarrier(vm *jni.VM, arg0 *jni.Object) (*Barrier, error) {
	var t Barrier
	t.VM = vm

	err := vm.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			return err
		}

		obj, err := env.NewObject((*jni.Class)(unsafe.Pointer(clsBarrier)), midBarrierCtor, jni.ObjectValue(arg0))
		if err != nil {
			return err
		}
		t.Obj = env.NewGlobalRef(obj)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// GetType calls androidx.constraintlayout.widget.Barrier.getType.
func (m *Barrier) GetType() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midBarrierGetType == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.widget.Barrier.getType is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midBarrierGetType,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// SetType calls androidx.constraintlayout.widget.Barrier.setType.
func (m *Barrier) SetType(arg0 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midBarrierSetType == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.widget.Barrier.setType is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midBarrierSetType, jni.IntValue(arg0),
		)
		return callErr
	})
	return callErr
}

// ResolveRtl calls androidx.constraintlayout.widget.Barrier.resolveRtl.
func (m *Barrier) ResolveRtl(arg0 *jni.Object, arg1 bool) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midBarrierResolveRtl == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.widget.Barrier.resolveRtl is not available on this device")
			return callErr
		}

		var jArg1 uint8
		if arg1 {
			jArg1 = jniTrue
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midBarrierResolveRtl, jni.ObjectValue(arg0), jni.BooleanValue(jArg1),
		)
		return callErr
	})
	return callErr
}

// SetAllowsGoneWidget calls androidx.constraintlayout.widget.Barrier.setAllowsGoneWidget.
func (m *Barrier) SetAllowsGoneWidget(arg0 bool) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midBarrierSetAllowsGoneWidget == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.widget.Barrier.setAllowsGoneWidget is not available on this device")
			return callErr
		}
		var jArg0 uint8
		if arg0 {
			jArg0 = jniTrue
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midBarrierSetAllowsGoneWidget, jni.BooleanValue(jArg0),
		)
		return callErr
	})
	return callErr
}

// AllowsGoneWidget calls androidx.constraintlayout.widget.Barrier.allowsGoneWidget.
func (m *Barrier) AllowsGoneWidget() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midBarrierAllowsGoneWidget == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.widget.Barrier.allowsGoneWidget is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midBarrierAllowsGoneWidget,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// GetAllowsGoneWidget calls androidx.constraintlayout.widget.Barrier.getAllowsGoneWidget.
func (m *Barrier) GetAllowsGoneWidget() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midBarrierGetAllowsGoneWidget == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.widget.Barrier.getAllowsGoneWidget is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midBarrierGetAllowsGoneWidget,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// SetDpMargin calls androidx.constraintlayout.widget.Barrier.setDpMargin.
func (m *Barrier) SetDpMargin(arg0 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midBarrierSetDpMargin == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.widget.Barrier.setDpMargin is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midBarrierSetDpMargin, jni.IntValue(arg0),
		)
		return callErr
	})
	return callErr
}

// GetMargin calls androidx.constraintlayout.widget.Barrier.getMargin.
func (m *Barrier) GetMargin() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midBarrierGetMargin == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.widget.Barrier.getMargin is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midBarrierGetMargin,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// SetMargin calls androidx.constraintlayout.widget.Barrier.setMargin.
func (m *Barrier) SetMargin(arg0 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midBarrierSetMargin == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.widget.Barrier.setMargin is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midBarrierSetMargin, jni.IntValue(arg0),
		)
		return callErr
	})
	return callErr
}

// ToString calls androidx.constraintlayout.widget.Barrier.toString.
func (m *Barrier) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midBarrierToString == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.widget.Barrier.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midBarrierToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
