// Code generated by javagen. DO NOT EDIT.

package helpers

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// AlignVerticallyReference wraps androidx.constraintlayout.solver.state.helpers.AlignVerticallyReference.
type AlignVerticallyReference struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// NewAlignVerticallyReference creates a new androidx.constraintlayout.solver.state.helpers.AlignVerticallyReference instance.
func NewAlignVerticallyReference(vm *jni.VM, arg0 *jni.Object) (*AlignVerticallyReference, error) {
	var t AlignVerticallyReference
	t.VM = vm

	err := vm.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			return err
		}

		obj, err := env.NewObject((*jni.Class)(unsafe.Pointer(clsAlignVerticallyReference)), midAlignVerticallyReferenceCtor, jni.ObjectValue(arg0))
		if err != nil {
			return err
		}
		t.Obj = env.NewGlobalRef(obj)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// Apply calls androidx.constraintlayout.solver.state.helpers.AlignVerticallyReference.apply.
func (m *AlignVerticallyReference) Apply() error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midAlignVerticallyReferenceApply == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.solver.state.helpers.AlignVerticallyReference.apply is not available on this device")
			return callErr
		}
		callErr = env.CallVoidMethod(
			m.Obj,
			midAlignVerticallyReferenceApply,
		)
		return callErr
	})
	return callErr
}

// TopToTop calls androidx.constraintlayout.solver.state.helpers.AlignVerticallyReference.topToTop.
func (m *AlignVerticallyReference) TopToTop(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midAlignVerticallyReferenceTopToTop == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.solver.state.helpers.AlignVerticallyReference.topToTop is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midAlignVerticallyReferenceTopToTop, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// TopToBottom calls androidx.constraintlayout.solver.state.helpers.AlignVerticallyReference.topToBottom.
func (m *AlignVerticallyReference) TopToBottom(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midAlignVerticallyReferenceTopToBottom == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.solver.state.helpers.AlignVerticallyReference.topToBottom is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midAlignVerticallyReferenceTopToBottom, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// BottomToTop calls androidx.constraintlayout.solver.state.helpers.AlignVerticallyReference.bottomToTop.
func (m *AlignVerticallyReference) BottomToTop(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midAlignVerticallyReferenceBottomToTop == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.solver.state.helpers.AlignVerticallyReference.bottomToTop is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midAlignVerticallyReferenceBottomToTop, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// BottomToBottom calls androidx.constraintlayout.solver.state.helpers.AlignVerticallyReference.bottomToBottom.
func (m *AlignVerticallyReference) BottomToBottom(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midAlignVerticallyReferenceBottomToBottom == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.solver.state.helpers.AlignVerticallyReference.bottomToBottom is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midAlignVerticallyReferenceBottomToBottom, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// Bias calls androidx.constraintlayout.solver.state.helpers.AlignVerticallyReference.bias.
func (m *AlignVerticallyReference) Bias(arg0 float32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midAlignVerticallyReferenceBias == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.solver.state.helpers.AlignVerticallyReference.bias is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midAlignVerticallyReferenceBias, jni.FloatValue(arg0),
		)
		return callErr
	})
	return callErr
}

// ToString calls androidx.constraintlayout.solver.state.helpers.AlignVerticallyReference.toString.
func (m *AlignVerticallyReference) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midAlignVerticallyReferenceToString == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.solver.state.helpers.AlignVerticallyReference.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midAlignVerticallyReferenceToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
