// Code generated by javagen. DO NOT EDIT.

package widget

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// MotionLayoutTransitionListener wraps androidx.constraintlayout.motion.widget.MotionLayout$TransitionListener.
type MotionLayoutTransitionListener struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// OnTransitionStarted calls androidx.constraintlayout.motion.widget.MotionLayout$TransitionListener.onTransitionStarted.
func (m *MotionLayoutTransitionListener) OnTransitionStarted(
	arg0 *jni.Object,
	arg1 int32,
	arg2 int32,
) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midMotionLayoutTransitionListenerOnTransitionStarted == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.motion.widget.MotionLayout$TransitionListener.onTransitionStarted is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midMotionLayoutTransitionListenerOnTransitionStarted, jni.ObjectValue(arg0), jni.IntValue(arg1), jni.IntValue(arg2),
		)
		return callErr
	})
	return callErr
}

// OnTransitionChange calls androidx.constraintlayout.motion.widget.MotionLayout$TransitionListener.onTransitionChange.
func (m *MotionLayoutTransitionListener) OnTransitionChange(
	arg0 *jni.Object,
	arg1 int32,
	arg2 int32,
	arg3 float32,
) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midMotionLayoutTransitionListenerOnTransitionChange == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.motion.widget.MotionLayout$TransitionListener.onTransitionChange is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midMotionLayoutTransitionListenerOnTransitionChange, jni.ObjectValue(arg0), jni.IntValue(arg1), jni.IntValue(arg2), jni.FloatValue(arg3),
		)
		return callErr
	})
	return callErr
}

// OnTransitionCompleted calls androidx.constraintlayout.motion.widget.MotionLayout$TransitionListener.onTransitionCompleted.
func (m *MotionLayoutTransitionListener) OnTransitionCompleted(arg0 *jni.Object, arg1 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midMotionLayoutTransitionListenerOnTransitionCompleted == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.motion.widget.MotionLayout$TransitionListener.onTransitionCompleted is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midMotionLayoutTransitionListenerOnTransitionCompleted, jni.ObjectValue(arg0), jni.IntValue(arg1),
		)
		return callErr
	})
	return callErr
}

// OnTransitionTrigger calls androidx.constraintlayout.motion.widget.MotionLayout$TransitionListener.onTransitionTrigger.
func (m *MotionLayoutTransitionListener) OnTransitionTrigger(
	arg0 *jni.Object,
	arg1 int32,
	arg2 bool,
	arg3 float32,
) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midMotionLayoutTransitionListenerOnTransitionTrigger == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.motion.widget.MotionLayout$TransitionListener.onTransitionTrigger is not available on this device")
			return callErr
		}

		var jArg2 uint8
		if arg2 {
			jArg2 = jniTrue
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midMotionLayoutTransitionListenerOnTransitionTrigger, jni.ObjectValue(arg0), jni.IntValue(arg1), jni.BooleanValue(jArg2), jni.FloatValue(arg3),
		)
		return callErr
	})
	return callErr
}

// ToString calls androidx.constraintlayout.motion.widget.MotionLayout$TransitionListener.toString.
func (m *MotionLayoutTransitionListener) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midMotionLayoutTransitionListenerToString == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.motion.widget.MotionLayout$TransitionListener.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midMotionLayoutTransitionListenerToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
