// Code generated by javagen. DO NOT EDIT.

package widget

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// DrawerLayoutLayoutParams wraps androidx.drawerlayout.widget.DrawerLayout$LayoutParams.
type DrawerLayoutLayoutParams struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// NewDrawerLayoutLayoutParams creates a new androidx.drawerlayout.widget.DrawerLayout$LayoutParams instance.
func NewDrawerLayoutLayoutParams(vm *jni.VM, arg0 *jni.Object, arg1 *jni.Object) (*DrawerLayoutLayoutParams, error) {
	var t DrawerLayoutLayoutParams
	t.VM = vm

	err := vm.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			return err
		}
		if clsDrawerLayoutLayoutParams == nil {
			return fmt.Errorf("androidx.drawerlayout.widget.DrawerLayout$LayoutParams is not available on this device")
		}
		if midDrawerLayoutLayoutParamsCtor == nil {
			return fmt.Errorf("androidx.drawerlayout.widget.DrawerLayout$LayoutParams constructor (Landroid/content/Context;Landroid/util/AttributeSet;)V is not available on this device")
		}

		obj, err := env.NewObject((*jni.Class)(unsafe.Pointer(clsDrawerLayoutLayoutParams)), midDrawerLayoutLayoutParamsCtor, jni.ObjectValue(arg0), jni.ObjectValue(arg1))
		if err != nil {
			return err
		}
		t.Obj = env.NewGlobalRef(obj)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// ToString calls androidx.drawerlayout.widget.DrawerLayout$LayoutParams.toString.
func (m *DrawerLayoutLayoutParams) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDrawerLayoutLayoutParamsToString == nil {
			callErr = fmt.Errorf("androidx.drawerlayout.widget.DrawerLayout$LayoutParams.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midDrawerLayoutLayoutParamsToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
