// Code generated by javagen. DO NOT EDIT.

package content

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// IntentCompat wraps androidx.core.content.IntentCompat.
type IntentCompat struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// ToString calls androidx.core.content.IntentCompat.toString.
func (m *IntentCompat) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midIntentCompatToString == nil {
			callErr = fmt.Errorf("androidx.core.content.IntentCompat.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midIntentCompatToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// MakeMainSelectorActivity calls androidx.core.content.IntentCompat.makeMainSelectorActivity.
func (m *IntentCompat) MakeMainSelectorActivity(arg0 string, arg1 string) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midIntentCompatMakeMainSelectorActivity == nil {
			callErr = fmt.Errorf("androidx.core.content.IntentCompat.makeMainSelectorActivity is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		jArg1, err := env.NewStringUTF(arg1)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg1.Object)

		result, callErr = env.CallStaticObjectMethod(
			(*jni.Class)(unsafe.Pointer(clsIntentCompat)),
			midIntentCompatMakeMainSelectorActivity, jni.ObjectValue(&jArg0.Object), jni.ObjectValue(&jArg1.Object),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// CreateManageUnusedAppRestrictionsIntent calls androidx.core.content.IntentCompat.createManageUnusedAppRestrictionsIntent.
func (m *IntentCompat) CreateManageUnusedAppRestrictionsIntent(arg0 *jni.Object, arg1 string) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midIntentCompatCreateManageUnusedAppRestrictionsIntent == nil {
			callErr = fmt.Errorf("androidx.core.content.IntentCompat.createManageUnusedAppRestrictionsIntent is not available on this device")
			return callErr
		}

		jArg1, err := env.NewStringUTF(arg1)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg1.Object)

		result, callErr = env.CallStaticObjectMethod(
			(*jni.Class)(unsafe.Pointer(clsIntentCompat)),
			midIntentCompatCreateManageUnusedAppRestrictionsIntent, jni.ObjectValue(arg0), jni.ObjectValue(&jArg1.Object),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}
