// Code generated by javagen. DO NOT EDIT.

package content

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// Entity wraps android.content.Entity.
type Entity struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// NewEntity creates a new android.content.Entity instance.
func NewEntity(vm *jni.VM, arg0 *jni.Object) (*Entity, error) {
	var t Entity
	t.VM = vm

	err := vm.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			return err
		}
		if clsEntity == nil {
			return fmt.Errorf("android.content.Entity is not available on this device")
		}
		if midEntityCtor == nil {
			return fmt.Errorf("android.content.Entity constructor (Landroid/content/ContentValues;)V is not available on this device")
		}

		obj, err := env.NewObject((*jni.Class)(unsafe.Pointer(clsEntity)), midEntityCtor, jni.ObjectValue(arg0))
		if err != nil {
			return err
		}
		t.Obj = env.NewGlobalRef(obj)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// AddSubValue calls android.content.Entity.addSubValue.
func (m *Entity) AddSubValue(arg0 *jni.Object, arg1 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midEntityAddSubValue == nil {
			callErr = fmt.Errorf("android.content.Entity.addSubValue is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midEntityAddSubValue, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		return callErr
	})
	return callErr
}

// GetEntityValues calls android.content.Entity.getEntityValues.
func (m *Entity) GetEntityValues() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midEntityGetEntityValues == nil {
			callErr = fmt.Errorf("android.content.Entity.getEntityValues is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midEntityGetEntityValues,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetSubValues calls android.content.Entity.getSubValues.
func (m *Entity) GetSubValues() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midEntityGetSubValues == nil {
			callErr = fmt.Errorf("android.content.Entity.getSubValues is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midEntityGetSubValues,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// ToString calls android.content.Entity.toString.
func (m *Entity) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midEntityToString == nil {
			callErr = fmt.Errorf("android.content.Entity.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midEntityToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
