// Code generated by javagen. DO NOT EDIT.

package nfc

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// TagLostException wraps android.nfc.TagLostException.
type TagLostException struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// NewTagLostException creates a new android.nfc.TagLostException instance.
func NewTagLostException(vm *jni.VM) (*TagLostException, error) {
	var t TagLostException
	t.VM = vm

	err := vm.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			return err
		}
		if clsTagLostException == nil {
			return fmt.Errorf("android.nfc.TagLostException is not available on this device")
		}
		if midTagLostExceptionCtor == nil {
			return fmt.Errorf("android.nfc.TagLostException constructor ()V is not available on this device")
		}
		obj, err := env.NewObject((*jni.Class)(unsafe.Pointer(clsTagLostException)), midTagLostExceptionCtor)
		if err != nil {
			return err
		}
		t.Obj = env.NewGlobalRef(obj)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// ToString calls android.nfc.TagLostException.toString.
func (m *TagLostException) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midTagLostExceptionToString == nil {
			callErr = fmt.Errorf("android.nfc.TagLostException.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midTagLostExceptionToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
