// Code generated by javagen. DO NOT EDIT.

package consts

const (
	Creator                         int = 0
	ErrorCodeBadArguments           int = 7
	ErrorCodeBadAuthentication      int = 9
	ErrorCodeBadRequest             int = 8
	ErrorCodeCanceled               int = 4
	ErrorCodeInvalidResponse        int = 5
	ErrorCodeNetworkError           int = 3
	ErrorCodeRemoteException        int = 1
	ErrorCodeUnsupportedOperation   int = 6
	VisibilityNotVisible            int = 3
	VisibilityUndefined             int = 0
	VisibilityUserManagedNotVisible int = 4
	VisibilityUserManagedVisible    int = 2
	VisibilityVisible               int = 1
)

const (
	KeyCustomTokenExpiry            string = "android.accounts.expiry"
	ActionAccountRemoved            string = "android.accounts.action.ACCOUNT_REMOVED"
	ActionAuthenticatorIntent       string = "android.accounts.AccountAuthenticator"
	AuthenticatorAttributesName     string = "account-authenticator"
	AuthenticatorMetaDataName       string = "android.accounts.AccountAuthenticator"
	KeyAccounts                     string = "accounts"
	KeyAccountAuthenticatorResponse string = "accountAuthenticatorResponse"
	KeyAccountManagerResponse       string = "accountManagerResponse"
	KeyAccountName                  string = "authAccount"
	KeyAccountSessionBundle         string = "accountSessionBundle"
	KeyAccountStatusToken           string = "accountStatusToken"
	KeyAccountType                  string = "accountType"
	KeyAndroidPackageName           string = "androidPackageName"
	KeyAuthenticatorTypes           string = "authenticator_types"
	KeyAuthtoken                    string = "authtoken"
	KeyAuthFailedMessage            string = "authFailedMessage"
	KeyAuthTokenLabel               string = "authTokenLabelKey"
	KeyBooleanResult                string = "booleanResult"
	KeyCallerPid                    string = "callerPid"
	KeyCallerUid                    string = "callerUid"
	KeyErrorCode                    string = "errorCode"
	KeyErrorMessage                 string = "errorMessage"
	KeyIntent                       string = "intent"
	KeyLastAuthenticatedTime        string = "lastAuthenticatedTime"
	KeyPassword                     string = "password"
	KeyUserdata                     string = "userdata"
	LoginAccountsChangedAction      string = "android.accounts.LOGIN_ACCOUNTS_CHANGED"
	PackageNameKeyLegacyNotVisible  string = "android:accounts:key_legacy_not_visible"
	PackageNameKeyLegacyVisible     string = "android:accounts:key_legacy_visible"
)
