// Code generated by javagen. DO NOT EDIT.

package util

import (
	"fmt"
	"sync"
	"unsafe"

	"github.com/AndroidGoLab/jni"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

// jniTrue is the JNI representation of a true boolean value.
const jniTrue uint8 = 1

var (
	initOnce sync.Once
	initErr  error

	clsSparseIntArrayKt              *jni.GlobalRef
	midSparseIntArrayKtToString      jni.MethodID
	midSparseIntArrayKtGetSize       jni.MethodID
	midSparseIntArrayKtContains      jni.MethodID
	midSparseIntArrayKtSet           jni.MethodID
	midSparseIntArrayKtPlus          jni.MethodID
	midSparseIntArrayKtContainsKey   jni.MethodID
	midSparseIntArrayKtContainsValue jni.MethodID
	midSparseIntArrayKtGetOrDefault  jni.MethodID
	midSparseIntArrayKtIsEmpty       jni.MethodID
	midSparseIntArrayKtIsNotEmpty    jni.MethodID
	midSparseIntArrayKtRemove        jni.MethodID
	midSparseIntArrayKtPutAll        jni.MethodID
	midSparseIntArrayKtKeyIterator   jni.MethodID
	midSparseIntArrayKtValueIterator jni.MethodID

	clsPair         *jni.GlobalRef
	midPairCtor     jni.MethodID
	midPairEquals   jni.MethodID
	midPairHashCode jni.MethodID
	midPairToString jni.MethodID

	clsPatternsCompat         *jni.GlobalRef
	midPatternsCompatToString jni.MethodID

	clsSparseArrayKt         *jni.GlobalRef
	midSparseArrayKtToString jni.MethodID

	clsFunction         *jni.GlobalRef
	midFunctionToString jni.MethodID

	clsTimeUtils                  *jni.GlobalRef
	midTimeUtilsToString          jni.MethodID
	midTimeUtilsFormatDuration2   jni.MethodID
	midTimeUtilsFormatDuration3_1 jni.MethodID
	midTimeUtilsFormatDuration2_2 jni.MethodID
	midTimeUtilsFormatDuration3_3 jni.MethodID

	clsTypedValueCompat                            *jni.GlobalRef
	midTypedValueCompatToString                    jni.MethodID
	midTypedValueCompatGetUnitFromComplexDimension jni.MethodID
	midTypedValueCompatDeriveDimension             jni.MethodID
	midTypedValueCompatDpToPx                      jni.MethodID
	midTypedValueCompatPxToDp                      jni.MethodID
	midTypedValueCompatSpToPx                      jni.MethodID
	midTypedValueCompatPxToSp                      jni.MethodID

	clsTypedValueCompatComplexDimensionUnit         *jni.GlobalRef
	midTypedValueCompatComplexDimensionUnitToString jni.MethodID

	clsDebugUtils                   *jni.GlobalRef
	midDebugUtilsToString           jni.MethodID
	midDebugUtilsBuildShortClassTag jni.MethodID

	clsLruCacheKt         *jni.GlobalRef
	midLruCacheKtToString jni.MethodID

	clsSizeKt              *jni.GlobalRef
	midSizeKtToString      jni.MethodID
	midSizeKtComponent11   jni.MethodID
	midSizeKtComponent21   jni.MethodID
	midSizeKtComponent11_1 jni.MethodID
	midSizeKtComponent21_1 jni.MethodID
	midSizeKtComponent11_2 jni.MethodID
	midSizeKtComponent21_2 jni.MethodID

	clsAtomicFileKt           *jni.GlobalRef
	midAtomicFileKtToString   jni.MethodID
	midAtomicFileKtWriteBytes jni.MethodID
	midAtomicFileKtWriteText  jni.MethodID
	midAtomicFileKtReadBytes  jni.MethodID
	midAtomicFileKtReadText   jni.MethodID

	clsLogWriter         *jni.GlobalRef
	midLogWriterCtor     jni.MethodID
	midLogWriterClose    jni.MethodID
	midLogWriterFlush    jni.MethodID
	midLogWriterWrite    jni.MethodID
	midLogWriterToString jni.MethodID

	clsPreconditions                            *jni.GlobalRef
	midPreconditionsToString                    jni.MethodID
	midPreconditionsCheckArgument1              jni.MethodID
	midPreconditionsCheckArgument2_1            jni.MethodID
	midPreconditionsCheckArgument3_2            jni.MethodID
	midPreconditionsCheckState2                 jni.MethodID
	midPreconditionsCheckState1_1               jni.MethodID
	midPreconditionsCheckFlagsArgument          jni.MethodID
	midPreconditionsCheckArgumentNonnegative2   jni.MethodID
	midPreconditionsCheckArgumentNonnegative1_1 jni.MethodID
	midPreconditionsCheckArgumentInRange4       jni.MethodID
	midPreconditionsCheckArgumentInRange4_1     jni.MethodID
	midPreconditionsCheckArgumentInRange4_2     jni.MethodID
	midPreconditionsCheckArgumentInRange4_3     jni.MethodID
	midPreconditionsCheckArgumentFinite         jni.MethodID

	clsRangeKt         *jni.GlobalRef
	midRangeKtToString jni.MethodID

	clsSupplier         *jni.GlobalRef
	midSupplierToString jni.MethodID

	clsAtomicFile            *jni.GlobalRef
	midAtomicFileCtor        jni.MethodID
	midAtomicFileGetBaseFile jni.MethodID
	midAtomicFileDelete      jni.MethodID
	midAtomicFileStartWrite  jni.MethodID
	midAtomicFileFinishWrite jni.MethodID
	midAtomicFileFailWrite   jni.MethodID
	midAtomicFileOpenRead    jni.MethodID
	midAtomicFileReadFully   jni.MethodID
	midAtomicFileToString    jni.MethodID

	clsSizeFCompat              *jni.GlobalRef
	midSizeFCompatCtor          jni.MethodID
	midSizeFCompatGetWidth      jni.MethodID
	midSizeFCompatGetHeight     jni.MethodID
	midSizeFCompatEquals        jni.MethodID
	midSizeFCompatHashCode      jni.MethodID
	midSizeFCompatToString      jni.MethodID
	midSizeFCompatToSizeF       jni.MethodID
	midSizeFCompatToSizeFCompat jni.MethodID

	clsObjectsCompat         *jni.GlobalRef
	midObjectsCompatEquals   jni.MethodID
	midObjectsCompatHashCode jni.MethodID
	midObjectsCompatHash     jni.MethodID
	midObjectsCompatToString jni.MethodID

	clsPredicate         *jni.GlobalRef
	midPredicateToString jni.MethodID

	clsConsumer         *jni.GlobalRef
	midConsumerToString jni.MethodID

	clsPairKt         *jni.GlobalRef
	midPairKtToString jni.MethodID

	clsConsumerKt         *jni.GlobalRef
	midConsumerKtToString jni.MethodID

	clsSparseBooleanArrayKt              *jni.GlobalRef
	midSparseBooleanArrayKtToString      jni.MethodID
	midSparseBooleanArrayKtGetSize       jni.MethodID
	midSparseBooleanArrayKtContains      jni.MethodID
	midSparseBooleanArrayKtSet           jni.MethodID
	midSparseBooleanArrayKtPlus          jni.MethodID
	midSparseBooleanArrayKtContainsKey   jni.MethodID
	midSparseBooleanArrayKtContainsValue jni.MethodID
	midSparseBooleanArrayKtGetOrDefault  jni.MethodID
	midSparseBooleanArrayKtIsEmpty       jni.MethodID
	midSparseBooleanArrayKtIsNotEmpty    jni.MethodID
	midSparseBooleanArrayKtRemove        jni.MethodID
	midSparseBooleanArrayKtPutAll        jni.MethodID
	midSparseBooleanArrayKtKeyIterator   jni.MethodID
	midSparseBooleanArrayKtValueIterator jni.MethodID

	clsPools         *jni.GlobalRef
	midPoolsToString jni.MethodID

	clsPoolsPool         *jni.GlobalRef
	midPoolsPoolToString jni.MethodID

	clsPoolsSimplePool         *jni.GlobalRef
	midPoolsSimplePoolToString jni.MethodID

	clsPoolsSynchronizedPool         *jni.GlobalRef
	midPoolsSynchronizedPoolToString jni.MethodID

	clsRunnableKt         *jni.GlobalRef
	midRunnableKtToString jni.MethodID

	clsLongSparseArrayKt         *jni.GlobalRef
	midLongSparseArrayKtToString jni.MethodID

	clsHalfKt          *jni.GlobalRef
	midHalfKtToString  jni.MethodID
	midHalfKtToHalf1   jni.MethodID
	midHalfKtToHalf1_1 jni.MethodID
	midHalfKtToHalf1_2 jni.MethodID
	midHalfKtToHalf1_3 jni.MethodID

	clsSparseLongArrayKt              *jni.GlobalRef
	midSparseLongArrayKtToString      jni.MethodID
	midSparseLongArrayKtGetSize       jni.MethodID
	midSparseLongArrayKtContains      jni.MethodID
	midSparseLongArrayKtSet           jni.MethodID
	midSparseLongArrayKtPlus          jni.MethodID
	midSparseLongArrayKtContainsKey   jni.MethodID
	midSparseLongArrayKtContainsValue jni.MethodID
	midSparseLongArrayKtGetOrDefault  jni.MethodID
	midSparseLongArrayKtIsEmpty       jni.MethodID
	midSparseLongArrayKtIsNotEmpty    jni.MethodID
	midSparseLongArrayKtRemove        jni.MethodID
	midSparseLongArrayKtPutAll        jni.MethodID
	midSparseLongArrayKtKeyIterator   jni.MethodID
	midSparseLongArrayKtValueIterator jni.MethodID

	clsAndroidXConsumerKt         *jni.GlobalRef
	midAndroidXConsumerKtToString jni.MethodID
)

func ensureInit(env *jni.Env) error {
	initOnce.Do(func() {
		initErr = doInit(env)
	})
	return initErr
}

// Init resolves all JNI class and method references for this package.
// It is safe to call multiple times (uses sync.Once internally).
// Exported for E2E testing on Android.
func Init(env *jni.Env) error {
	return ensureInit(env)
}

func doInit(env *jni.Env) error {
	var c *jni.Class
	var err error

	c, err = env.FindClass("androidx/core/util/SparseIntArrayKt")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsSparseIntArrayKt = env.NewGlobalRef(&c.Object)

		midSparseIntArrayKtToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsSparseIntArrayKt)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseIntArrayKtGetSize, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseIntArrayKt)), "getSize", "(Landroid/util/SparseIntArray;)I")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseIntArrayKtContains, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseIntArrayKt)), "contains", "(Landroid/util/SparseIntArray;I)Z")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseIntArrayKtSet, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseIntArrayKt)), "set", "(Landroid/util/SparseIntArray;II)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseIntArrayKtPlus, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseIntArrayKt)), "plus", "(Landroid/util/SparseIntArray;Landroid/util/SparseIntArray;)Landroid/util/SparseIntArray;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseIntArrayKtContainsKey, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseIntArrayKt)), "containsKey", "(Landroid/util/SparseIntArray;I)Z")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseIntArrayKtContainsValue, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseIntArrayKt)), "containsValue", "(Landroid/util/SparseIntArray;I)Z")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseIntArrayKtGetOrDefault, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseIntArrayKt)), "getOrDefault", "(Landroid/util/SparseIntArray;II)I")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseIntArrayKtIsEmpty, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseIntArrayKt)), "isEmpty", "(Landroid/util/SparseIntArray;)Z")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseIntArrayKtIsNotEmpty, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseIntArrayKt)), "isNotEmpty", "(Landroid/util/SparseIntArray;)Z")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseIntArrayKtRemove, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseIntArrayKt)), "remove", "(Landroid/util/SparseIntArray;II)Z")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseIntArrayKtPutAll, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseIntArrayKt)), "putAll", "(Landroid/util/SparseIntArray;Landroid/util/SparseIntArray;)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseIntArrayKtKeyIterator, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseIntArrayKt)), "keyIterator", "(Landroid/util/SparseIntArray;)Lkotlin/collections/IntIterator;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseIntArrayKtValueIterator, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseIntArrayKt)), "valueIterator", "(Landroid/util/SparseIntArray;)Lkotlin/collections/IntIterator;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/Pair")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsPair = env.NewGlobalRef(&c.Object)
		midPairCtor, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsPair)), "<init>", "(Ljava/lang/F;Ljava/lang/S;)V")
		if err != nil {
			env.ExceptionClear()
		}

		midPairEquals, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsPair)), "equals", "(Ljava/lang/Object;)Z")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midPairHashCode, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsPair)), "hashCode", "()I")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midPairToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsPair)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/PatternsCompat")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsPatternsCompat = env.NewGlobalRef(&c.Object)

		midPatternsCompatToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsPatternsCompat)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/SparseArrayKt")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsSparseArrayKt = env.NewGlobalRef(&c.Object)

		midSparseArrayKtToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsSparseArrayKt)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/Function")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsFunction = env.NewGlobalRef(&c.Object)

		midFunctionToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsFunction)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/TimeUtils")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsTimeUtils = env.NewGlobalRef(&c.Object)

		midTimeUtilsToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsTimeUtils)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midTimeUtilsFormatDuration2, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsTimeUtils)), "formatDuration", "(JLjava/lang/StringBuilder;)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midTimeUtilsFormatDuration3_1, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsTimeUtils)), "formatDuration", "(JLjava/io/PrintWriter;I)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midTimeUtilsFormatDuration2_2, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsTimeUtils)), "formatDuration", "(JLjava/io/PrintWriter;)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midTimeUtilsFormatDuration3_3, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsTimeUtils)), "formatDuration", "(JJLjava/io/PrintWriter;)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/TypedValueCompat")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsTypedValueCompat = env.NewGlobalRef(&c.Object)

		midTypedValueCompatToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsTypedValueCompat)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midTypedValueCompatGetUnitFromComplexDimension, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsTypedValueCompat)), "getUnitFromComplexDimension", "(I)I")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midTypedValueCompatDeriveDimension, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsTypedValueCompat)), "deriveDimension", "(IFLandroid/util/DisplayMetrics;)F")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midTypedValueCompatDpToPx, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsTypedValueCompat)), "dpToPx", "(FLandroid/util/DisplayMetrics;)F")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midTypedValueCompatPxToDp, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsTypedValueCompat)), "pxToDp", "(FLandroid/util/DisplayMetrics;)F")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midTypedValueCompatSpToPx, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsTypedValueCompat)), "spToPx", "(FLandroid/util/DisplayMetrics;)F")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midTypedValueCompatPxToSp, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsTypedValueCompat)), "pxToSp", "(FLandroid/util/DisplayMetrics;)F")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/TypedValueCompat$ComplexDimensionUnit")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsTypedValueCompatComplexDimensionUnit = env.NewGlobalRef(&c.Object)

		midTypedValueCompatComplexDimensionUnitToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsTypedValueCompatComplexDimensionUnit)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/DebugUtils")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsDebugUtils = env.NewGlobalRef(&c.Object)

		midDebugUtilsToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDebugUtils)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midDebugUtilsBuildShortClassTag, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsDebugUtils)), "buildShortClassTag", "(Ljava/lang/Object;Ljava/lang/StringBuilder;)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/LruCacheKt")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsLruCacheKt = env.NewGlobalRef(&c.Object)

		midLruCacheKtToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsLruCacheKt)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/SizeKt")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsSizeKt = env.NewGlobalRef(&c.Object)

		midSizeKtToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsSizeKt)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSizeKtComponent11, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSizeKt)), "component1", "(Landroid/util/Size;)I")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSizeKtComponent21, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSizeKt)), "component2", "(Landroid/util/Size;)I")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSizeKtComponent11_1, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSizeKt)), "component1", "(Landroid/util/SizeF;)F")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSizeKtComponent21_1, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSizeKt)), "component2", "(Landroid/util/SizeF;)F")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSizeKtComponent11_2, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSizeKt)), "component1", "(Landroidx/core/util/SizeFCompat;)F")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSizeKtComponent21_2, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSizeKt)), "component2", "(Landroidx/core/util/SizeFCompat;)F")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/AtomicFileKt")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsAtomicFileKt = env.NewGlobalRef(&c.Object)

		midAtomicFileKtToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsAtomicFileKt)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midAtomicFileKtWriteBytes, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsAtomicFileKt)), "writeBytes", "(Landroid/util/AtomicFile;[B)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midAtomicFileKtWriteText, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsAtomicFileKt)), "writeText", "(Landroid/util/AtomicFile;Ljava/lang/String;Ljava/nio/charset/Charset;)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midAtomicFileKtReadBytes, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsAtomicFileKt)), "readBytes", "(Landroid/util/AtomicFile;)[B")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midAtomicFileKtReadText, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsAtomicFileKt)), "readText", "(Landroid/util/AtomicFile;Ljava/nio/charset/Charset;)Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/LogWriter")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsLogWriter = env.NewGlobalRef(&c.Object)
		midLogWriterCtor, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsLogWriter)), "<init>", "(Ljava/lang/String;)V")
		if err != nil {
			env.ExceptionClear()
		}

		midLogWriterClose, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsLogWriter)), "close", "()V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midLogWriterFlush, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsLogWriter)), "flush", "()V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midLogWriterWrite, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsLogWriter)), "write", "([CII)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midLogWriterToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsLogWriter)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/Preconditions")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsPreconditions = env.NewGlobalRef(&c.Object)

		midPreconditionsToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsPreconditions)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midPreconditionsCheckArgument1, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsPreconditions)), "checkArgument", "(Z)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midPreconditionsCheckArgument2_1, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsPreconditions)), "checkArgument", "(ZLjava/lang/Object;)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midPreconditionsCheckArgument3_2, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsPreconditions)), "checkArgument", "(ZLjava/lang/String;[Ljava/lang/Object;)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midPreconditionsCheckState2, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsPreconditions)), "checkState", "(ZLjava/lang/String;)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midPreconditionsCheckState1_1, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsPreconditions)), "checkState", "(Z)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midPreconditionsCheckFlagsArgument, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsPreconditions)), "checkFlagsArgument", "(II)I")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midPreconditionsCheckArgumentNonnegative2, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsPreconditions)), "checkArgumentNonnegative", "(ILjava/lang/String;)I")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midPreconditionsCheckArgumentNonnegative1_1, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsPreconditions)), "checkArgumentNonnegative", "(I)I")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midPreconditionsCheckArgumentInRange4, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsPreconditions)), "checkArgumentInRange", "(IIILjava/lang/String;)I")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midPreconditionsCheckArgumentInRange4_1, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsPreconditions)), "checkArgumentInRange", "(JJJLjava/lang/String;)J")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midPreconditionsCheckArgumentInRange4_2, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsPreconditions)), "checkArgumentInRange", "(FFFLjava/lang/String;)F")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midPreconditionsCheckArgumentInRange4_3, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsPreconditions)), "checkArgumentInRange", "(DDDLjava/lang/String;)D")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midPreconditionsCheckArgumentFinite, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsPreconditions)), "checkArgumentFinite", "(FLjava/lang/String;)F")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/RangeKt")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsRangeKt = env.NewGlobalRef(&c.Object)

		midRangeKtToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsRangeKt)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/Supplier")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsSupplier = env.NewGlobalRef(&c.Object)

		midSupplierToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsSupplier)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/AtomicFile")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsAtomicFile = env.NewGlobalRef(&c.Object)
		midAtomicFileCtor, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsAtomicFile)), "<init>", "(Ljava/io/File;)V")
		if err != nil {
			env.ExceptionClear()
		}

		midAtomicFileGetBaseFile, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsAtomicFile)), "getBaseFile", "()Ljava/io/File;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midAtomicFileDelete, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsAtomicFile)), "delete", "()V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midAtomicFileStartWrite, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsAtomicFile)), "startWrite", "()Ljava/io/FileOutputStream;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midAtomicFileFinishWrite, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsAtomicFile)), "finishWrite", "(Ljava/io/FileOutputStream;)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midAtomicFileFailWrite, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsAtomicFile)), "failWrite", "(Ljava/io/FileOutputStream;)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midAtomicFileOpenRead, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsAtomicFile)), "openRead", "()Ljava/io/FileInputStream;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midAtomicFileReadFully, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsAtomicFile)), "readFully", "()[B")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midAtomicFileToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsAtomicFile)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/SizeFCompat")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsSizeFCompat = env.NewGlobalRef(&c.Object)
		midSizeFCompatCtor, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsSizeFCompat)), "<init>", "(FF)V")
		if err != nil {
			env.ExceptionClear()
		}

		midSizeFCompatGetWidth, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsSizeFCompat)), "getWidth", "()F")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSizeFCompatGetHeight, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsSizeFCompat)), "getHeight", "()F")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSizeFCompatEquals, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsSizeFCompat)), "equals", "(Ljava/lang/Object;)Z")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSizeFCompatHashCode, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsSizeFCompat)), "hashCode", "()I")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSizeFCompatToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsSizeFCompat)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSizeFCompatToSizeF, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsSizeFCompat)), "toSizeF", "()Landroid/util/SizeF;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSizeFCompatToSizeFCompat, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSizeFCompat)), "toSizeFCompat", "(Landroid/util/SizeF;)Landroidx/core/util/SizeFCompat;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/ObjectsCompat")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsObjectsCompat = env.NewGlobalRef(&c.Object)

		midObjectsCompatEquals, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsObjectsCompat)), "equals", "(Ljava/lang/Object;Ljava/lang/Object;)Z")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midObjectsCompatHashCode, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsObjectsCompat)), "hashCode", "(Ljava/lang/Object;)I")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midObjectsCompatHash, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsObjectsCompat)), "hash", "([Ljava/lang/Object;)I")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midObjectsCompatToString, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsObjectsCompat)), "toString", "(Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/Predicate")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsPredicate = env.NewGlobalRef(&c.Object)

		midPredicateToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsPredicate)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/Consumer")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsConsumer = env.NewGlobalRef(&c.Object)

		midConsumerToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsConsumer)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/PairKt")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsPairKt = env.NewGlobalRef(&c.Object)

		midPairKtToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsPairKt)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/ConsumerKt")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsConsumerKt = env.NewGlobalRef(&c.Object)

		midConsumerKtToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsConsumerKt)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/SparseBooleanArrayKt")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsSparseBooleanArrayKt = env.NewGlobalRef(&c.Object)

		midSparseBooleanArrayKtToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsSparseBooleanArrayKt)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseBooleanArrayKtGetSize, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseBooleanArrayKt)), "getSize", "(Landroid/util/SparseBooleanArray;)I")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseBooleanArrayKtContains, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseBooleanArrayKt)), "contains", "(Landroid/util/SparseBooleanArray;I)Z")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseBooleanArrayKtSet, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseBooleanArrayKt)), "set", "(Landroid/util/SparseBooleanArray;IZ)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseBooleanArrayKtPlus, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseBooleanArrayKt)), "plus", "(Landroid/util/SparseBooleanArray;Landroid/util/SparseBooleanArray;)Landroid/util/SparseBooleanArray;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseBooleanArrayKtContainsKey, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseBooleanArrayKt)), "containsKey", "(Landroid/util/SparseBooleanArray;I)Z")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseBooleanArrayKtContainsValue, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseBooleanArrayKt)), "containsValue", "(Landroid/util/SparseBooleanArray;Z)Z")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseBooleanArrayKtGetOrDefault, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseBooleanArrayKt)), "getOrDefault", "(Landroid/util/SparseBooleanArray;IZ)Z")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseBooleanArrayKtIsEmpty, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseBooleanArrayKt)), "isEmpty", "(Landroid/util/SparseBooleanArray;)Z")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseBooleanArrayKtIsNotEmpty, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseBooleanArrayKt)), "isNotEmpty", "(Landroid/util/SparseBooleanArray;)Z")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseBooleanArrayKtRemove, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseBooleanArrayKt)), "remove", "(Landroid/util/SparseBooleanArray;IZ)Z")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseBooleanArrayKtPutAll, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseBooleanArrayKt)), "putAll", "(Landroid/util/SparseBooleanArray;Landroid/util/SparseBooleanArray;)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseBooleanArrayKtKeyIterator, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseBooleanArrayKt)), "keyIterator", "(Landroid/util/SparseBooleanArray;)Lkotlin/collections/IntIterator;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseBooleanArrayKtValueIterator, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseBooleanArrayKt)), "valueIterator", "(Landroid/util/SparseBooleanArray;)Lkotlin/collections/BooleanIterator;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/Pools")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsPools = env.NewGlobalRef(&c.Object)

		midPoolsToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsPools)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/Pools$Pool")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsPoolsPool = env.NewGlobalRef(&c.Object)

		midPoolsPoolToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsPoolsPool)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/Pools$SimplePool")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsPoolsSimplePool = env.NewGlobalRef(&c.Object)

		midPoolsSimplePoolToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsPoolsSimplePool)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/Pools$SynchronizedPool")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsPoolsSynchronizedPool = env.NewGlobalRef(&c.Object)

		midPoolsSynchronizedPoolToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsPoolsSynchronizedPool)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/RunnableKt")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsRunnableKt = env.NewGlobalRef(&c.Object)

		midRunnableKtToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsRunnableKt)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/LongSparseArrayKt")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsLongSparseArrayKt = env.NewGlobalRef(&c.Object)

		midLongSparseArrayKtToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsLongSparseArrayKt)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/HalfKt")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsHalfKt = env.NewGlobalRef(&c.Object)

		midHalfKtToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsHalfKt)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midHalfKtToHalf1, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsHalfKt)), "toHalf", "(S)Landroid/util/Half;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midHalfKtToHalf1_1, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsHalfKt)), "toHalf", "(F)Landroid/util/Half;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midHalfKtToHalf1_2, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsHalfKt)), "toHalf", "(D)Landroid/util/Half;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midHalfKtToHalf1_3, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsHalfKt)), "toHalf", "(Ljava/lang/String;)Landroid/util/Half;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/SparseLongArrayKt")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsSparseLongArrayKt = env.NewGlobalRef(&c.Object)

		midSparseLongArrayKtToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsSparseLongArrayKt)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseLongArrayKtGetSize, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseLongArrayKt)), "getSize", "(Landroid/util/SparseLongArray;)I")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseLongArrayKtContains, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseLongArrayKt)), "contains", "(Landroid/util/SparseLongArray;I)Z")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseLongArrayKtSet, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseLongArrayKt)), "set", "(Landroid/util/SparseLongArray;IJ)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseLongArrayKtPlus, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseLongArrayKt)), "plus", "(Landroid/util/SparseLongArray;Landroid/util/SparseLongArray;)Landroid/util/SparseLongArray;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseLongArrayKtContainsKey, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseLongArrayKt)), "containsKey", "(Landroid/util/SparseLongArray;I)Z")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseLongArrayKtContainsValue, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseLongArrayKt)), "containsValue", "(Landroid/util/SparseLongArray;J)Z")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseLongArrayKtGetOrDefault, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseLongArrayKt)), "getOrDefault", "(Landroid/util/SparseLongArray;IJ)J")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseLongArrayKtIsEmpty, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseLongArrayKt)), "isEmpty", "(Landroid/util/SparseLongArray;)Z")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseLongArrayKtIsNotEmpty, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseLongArrayKt)), "isNotEmpty", "(Landroid/util/SparseLongArray;)Z")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseLongArrayKtRemove, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseLongArrayKt)), "remove", "(Landroid/util/SparseLongArray;IJ)Z")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseLongArrayKtPutAll, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseLongArrayKt)), "putAll", "(Landroid/util/SparseLongArray;Landroid/util/SparseLongArray;)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseLongArrayKtKeyIterator, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseLongArrayKt)), "keyIterator", "(Landroid/util/SparseLongArray;)Lkotlin/collections/IntIterator;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midSparseLongArrayKtValueIterator, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsSparseLongArrayKt)), "valueIterator", "(Landroid/util/SparseLongArray;)Lkotlin/collections/LongIterator;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("androidx/core/util/AndroidXConsumerKt")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsAndroidXConsumerKt = env.NewGlobalRef(&c.Object)

		midAndroidXConsumerKtToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsAndroidXConsumerKt)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	return nil
}
