// Code generated by javagen. DO NOT EDIT.

package accessibility

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// NodeInfoCompatCollectionItemInfoCompat wraps androidx.core.view.accessibility.AccessibilityNodeInfoCompat$CollectionItemInfoCompat.
type NodeInfoCompatCollectionItemInfoCompat struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// GetColumnIndex calls androidx.core.view.accessibility.AccessibilityNodeInfoCompat$CollectionItemInfoCompat.getColumnIndex.
func (m *NodeInfoCompatCollectionItemInfoCompat) GetColumnIndex() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midNodeInfoCompatCollectionItemInfoCompatGetColumnIndex == nil {
			callErr = fmt.Errorf("androidx.core.view.accessibility.AccessibilityNodeInfoCompat$CollectionItemInfoCompat.getColumnIndex is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midNodeInfoCompatCollectionItemInfoCompatGetColumnIndex,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetColumnSpan calls androidx.core.view.accessibility.AccessibilityNodeInfoCompat$CollectionItemInfoCompat.getColumnSpan.
func (m *NodeInfoCompatCollectionItemInfoCompat) GetColumnSpan() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midNodeInfoCompatCollectionItemInfoCompatGetColumnSpan == nil {
			callErr = fmt.Errorf("androidx.core.view.accessibility.AccessibilityNodeInfoCompat$CollectionItemInfoCompat.getColumnSpan is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midNodeInfoCompatCollectionItemInfoCompatGetColumnSpan,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetRowIndex calls androidx.core.view.accessibility.AccessibilityNodeInfoCompat$CollectionItemInfoCompat.getRowIndex.
func (m *NodeInfoCompatCollectionItemInfoCompat) GetRowIndex() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midNodeInfoCompatCollectionItemInfoCompatGetRowIndex == nil {
			callErr = fmt.Errorf("androidx.core.view.accessibility.AccessibilityNodeInfoCompat$CollectionItemInfoCompat.getRowIndex is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midNodeInfoCompatCollectionItemInfoCompatGetRowIndex,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetRowSpan calls androidx.core.view.accessibility.AccessibilityNodeInfoCompat$CollectionItemInfoCompat.getRowSpan.
func (m *NodeInfoCompatCollectionItemInfoCompat) GetRowSpan() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midNodeInfoCompatCollectionItemInfoCompatGetRowSpan == nil {
			callErr = fmt.Errorf("androidx.core.view.accessibility.AccessibilityNodeInfoCompat$CollectionItemInfoCompat.getRowSpan is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midNodeInfoCompatCollectionItemInfoCompatGetRowSpan,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// IsHeading calls androidx.core.view.accessibility.AccessibilityNodeInfoCompat$CollectionItemInfoCompat.isHeading.
func (m *NodeInfoCompatCollectionItemInfoCompat) IsHeading() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midNodeInfoCompatCollectionItemInfoCompatIsHeading == nil {
			callErr = fmt.Errorf("androidx.core.view.accessibility.AccessibilityNodeInfoCompat$CollectionItemInfoCompat.isHeading is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midNodeInfoCompatCollectionItemInfoCompatIsHeading,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// IsSelected calls androidx.core.view.accessibility.AccessibilityNodeInfoCompat$CollectionItemInfoCompat.isSelected.
func (m *NodeInfoCompatCollectionItemInfoCompat) IsSelected() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midNodeInfoCompatCollectionItemInfoCompatIsSelected == nil {
			callErr = fmt.Errorf("androidx.core.view.accessibility.AccessibilityNodeInfoCompat$CollectionItemInfoCompat.isSelected is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midNodeInfoCompatCollectionItemInfoCompatIsSelected,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// GetRowTitle calls androidx.core.view.accessibility.AccessibilityNodeInfoCompat$CollectionItemInfoCompat.getRowTitle.
func (m *NodeInfoCompatCollectionItemInfoCompat) GetRowTitle() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midNodeInfoCompatCollectionItemInfoCompatGetRowTitle == nil {
			callErr = fmt.Errorf("androidx.core.view.accessibility.AccessibilityNodeInfoCompat$CollectionItemInfoCompat.getRowTitle is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midNodeInfoCompatCollectionItemInfoCompatGetRowTitle,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// GetColumnTitle calls androidx.core.view.accessibility.AccessibilityNodeInfoCompat$CollectionItemInfoCompat.getColumnTitle.
func (m *NodeInfoCompatCollectionItemInfoCompat) GetColumnTitle() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midNodeInfoCompatCollectionItemInfoCompatGetColumnTitle == nil {
			callErr = fmt.Errorf("androidx.core.view.accessibility.AccessibilityNodeInfoCompat$CollectionItemInfoCompat.getColumnTitle is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midNodeInfoCompatCollectionItemInfoCompatGetColumnTitle,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// ToString calls androidx.core.view.accessibility.AccessibilityNodeInfoCompat$CollectionItemInfoCompat.toString.
func (m *NodeInfoCompatCollectionItemInfoCompat) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midNodeInfoCompatCollectionItemInfoCompatToString == nil {
			callErr = fmt.Errorf("androidx.core.view.accessibility.AccessibilityNodeInfoCompat$CollectionItemInfoCompat.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midNodeInfoCompatCollectionItemInfoCompatToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// Obtain6 calls androidx.core.view.accessibility.AccessibilityNodeInfoCompat$CollectionItemInfoCompat.obtain.
func (m *NodeInfoCompatCollectionItemInfoCompat) Obtain6(
	arg0 int32,
	arg1 int32,
	arg2 int32,
	arg3 int32,
	arg4 bool,
	arg5 bool,
) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midNodeInfoCompatCollectionItemInfoCompatObtain6 == nil {
			callErr = fmt.Errorf("androidx.core.view.accessibility.AccessibilityNodeInfoCompat$CollectionItemInfoCompat.obtain is not available on this device")
			return callErr
		}

		var jArg4 uint8
		if arg4 {
			jArg4 = jniTrue
		}

		var jArg5 uint8
		if arg5 {
			jArg5 = jniTrue
		}

		result, callErr = env.CallStaticObjectMethod(
			(*jni.Class)(unsafe.Pointer(clsNodeInfoCompatCollectionItemInfoCompat)),
			midNodeInfoCompatCollectionItemInfoCompatObtain6, jni.IntValue(arg0), jni.IntValue(arg1), jni.IntValue(arg2), jni.IntValue(arg3), jni.BooleanValue(jArg4), jni.BooleanValue(jArg5),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// Obtain5_1 calls androidx.core.view.accessibility.AccessibilityNodeInfoCompat$CollectionItemInfoCompat.obtain.
func (m *NodeInfoCompatCollectionItemInfoCompat) Obtain5_1(
	arg0 int32,
	arg1 int32,
	arg2 int32,
	arg3 int32,
	arg4 bool,
) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midNodeInfoCompatCollectionItemInfoCompatObtain5_1 == nil {
			callErr = fmt.Errorf("androidx.core.view.accessibility.AccessibilityNodeInfoCompat$CollectionItemInfoCompat.obtain is not available on this device")
			return callErr
		}

		var jArg4 uint8
		if arg4 {
			jArg4 = jniTrue
		}

		result, callErr = env.CallStaticObjectMethod(
			(*jni.Class)(unsafe.Pointer(clsNodeInfoCompatCollectionItemInfoCompat)),
			midNodeInfoCompatCollectionItemInfoCompatObtain5_1, jni.IntValue(arg0), jni.IntValue(arg1), jni.IntValue(arg2), jni.IntValue(arg3), jni.BooleanValue(jArg4),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}
