// Code generated by javagen. DO NOT EDIT.

package media

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// AudioDescriptor wraps android.media.AudioDescriptor.
type AudioDescriptor struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// DescribeContents calls android.media.AudioDescriptor.describeContents.
func (m *AudioDescriptor) DescribeContents() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midAudioDescriptorDescribeContents == nil {
			callErr = fmt.Errorf("android.media.AudioDescriptor.describeContents is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midAudioDescriptorDescribeContents,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// Equals calls android.media.AudioDescriptor.equals.
func (m *AudioDescriptor) Equals(arg0 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midAudioDescriptorEquals == nil {
			callErr = fmt.Errorf("android.media.AudioDescriptor.equals is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midAudioDescriptorEquals, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// GetDescriptor calls android.media.AudioDescriptor.getDescriptor.
func (m *AudioDescriptor) GetDescriptor() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midAudioDescriptorGetDescriptor == nil {
			callErr = fmt.Errorf("android.media.AudioDescriptor.getDescriptor is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midAudioDescriptorGetDescriptor,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetEncapsulationType calls android.media.AudioDescriptor.getEncapsulationType.
func (m *AudioDescriptor) GetEncapsulationType() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midAudioDescriptorGetEncapsulationType == nil {
			callErr = fmt.Errorf("android.media.AudioDescriptor.getEncapsulationType is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midAudioDescriptorGetEncapsulationType,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetStandard calls android.media.AudioDescriptor.getStandard.
func (m *AudioDescriptor) GetStandard() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midAudioDescriptorGetStandard == nil {
			callErr = fmt.Errorf("android.media.AudioDescriptor.getStandard is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midAudioDescriptorGetStandard,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// HashCode calls android.media.AudioDescriptor.hashCode.
func (m *AudioDescriptor) HashCode() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midAudioDescriptorHashCode == nil {
			callErr = fmt.Errorf("android.media.AudioDescriptor.hashCode is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midAudioDescriptorHashCode,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// ToString calls android.media.AudioDescriptor.toString.
func (m *AudioDescriptor) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midAudioDescriptorToString == nil {
			callErr = fmt.Errorf("android.media.AudioDescriptor.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midAudioDescriptorToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// WriteToParcel calls android.media.AudioDescriptor.writeToParcel.
func (m *AudioDescriptor) WriteToParcel(arg0 *jni.Object, arg1 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midAudioDescriptorWriteToParcel == nil {
			callErr = fmt.Errorf("android.media.AudioDescriptor.writeToParcel is not available on this device")
			return callErr
		}

		callErr = env.CallStaticVoidMethod(
			(*jni.Class)(unsafe.Pointer(clsAudioDescriptor)),
			midAudioDescriptorWriteToParcel, jni.ObjectValue(arg0), jni.IntValue(arg1),
		)
		return callErr
	})
	return callErr
}
