// Code generated by javagen. DO NOT EDIT.

package media

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// DrmSessionException wraps android.media.MediaDrm$SessionException.
type DrmSessionException struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// NewDrmSessionException creates a new android.media.MediaDrm$SessionException instance.
func NewDrmSessionException(vm *jni.VM, arg0 int32, arg1 string) (*DrmSessionException, error) {
	var t DrmSessionException
	t.VM = vm

	err := vm.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			return err
		}
		if clsDrmSessionException == nil {
			return fmt.Errorf("android.media.MediaDrm$SessionException is not available on this device")
		}
		if midDrmSessionExceptionCtor == nil {
			return fmt.Errorf("android.media.MediaDrm$SessionException constructor (ILjava/lang/String;)V is not available on this device")
		}

		jArg1, err := env.NewStringUTF(arg1)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg1.Object)

		obj, err := env.NewObject((*jni.Class)(unsafe.Pointer(clsDrmSessionException)), midDrmSessionExceptionCtor, jni.IntValue(arg0), jni.ObjectValue(&jArg1.Object))
		if err != nil {
			return err
		}
		t.Obj = env.NewGlobalRef(obj)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// GetErrorCode calls android.media.MediaDrm$SessionException.getErrorCode.
func (m *DrmSessionException) GetErrorCode() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDrmSessionExceptionGetErrorCode == nil {
			callErr = fmt.Errorf("android.media.MediaDrm$SessionException.getErrorCode is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midDrmSessionExceptionGetErrorCode,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetErrorContext calls android.media.MediaDrm$SessionException.getErrorContext.
func (m *DrmSessionException) GetErrorContext() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDrmSessionExceptionGetErrorContext == nil {
			callErr = fmt.Errorf("android.media.MediaDrm$SessionException.getErrorContext is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midDrmSessionExceptionGetErrorContext,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetOemError calls android.media.MediaDrm$SessionException.getOemError.
func (m *DrmSessionException) GetOemError() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDrmSessionExceptionGetOemError == nil {
			callErr = fmt.Errorf("android.media.MediaDrm$SessionException.getOemError is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midDrmSessionExceptionGetOemError,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetVendorError calls android.media.MediaDrm$SessionException.getVendorError.
func (m *DrmSessionException) GetVendorError() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDrmSessionExceptionGetVendorError == nil {
			callErr = fmt.Errorf("android.media.MediaDrm$SessionException.getVendorError is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midDrmSessionExceptionGetVendorError,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// IsTransient calls android.media.MediaDrm$SessionException.isTransient.
func (m *DrmSessionException) IsTransient() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDrmSessionExceptionIsTransient == nil {
			callErr = fmt.Errorf("android.media.MediaDrm$SessionException.isTransient is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midDrmSessionExceptionIsTransient,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// ToString calls android.media.MediaDrm$SessionException.toString.
func (m *DrmSessionException) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDrmSessionExceptionToString == nil {
			callErr = fmt.Errorf("android.media.MediaDrm$SessionException.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midDrmSessionExceptionToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
