// Code generated by javagen. DO NOT EDIT.

package media

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// Session2CommandGroup wraps android.media.Session2CommandGroup.
type Session2CommandGroup struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// DescribeContents calls android.media.Session2CommandGroup.describeContents.
func (m *Session2CommandGroup) DescribeContents() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSession2CommandGroupDescribeContents == nil {
			callErr = fmt.Errorf("android.media.Session2CommandGroup.describeContents is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midSession2CommandGroupDescribeContents,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetCommands calls android.media.Session2CommandGroup.getCommands.
func (m *Session2CommandGroup) GetCommands() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSession2CommandGroupGetCommands == nil {
			callErr = fmt.Errorf("android.media.Session2CommandGroup.getCommands is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midSession2CommandGroupGetCommands,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// HasCommand1 calls android.media.Session2CommandGroup.hasCommand.
func (m *Session2CommandGroup) HasCommand1(arg0 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSession2CommandGroupHasCommand1 == nil {
			callErr = fmt.Errorf("android.media.Session2CommandGroup.hasCommand is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midSession2CommandGroupHasCommand1, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// HasCommand1_1 calls android.media.Session2CommandGroup.hasCommand.
func (m *Session2CommandGroup) HasCommand1_1(arg0 int32) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSession2CommandGroupHasCommand1_1 == nil {
			callErr = fmt.Errorf("android.media.Session2CommandGroup.hasCommand is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midSession2CommandGroupHasCommand1_1, jni.IntValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// ToString calls android.media.Session2CommandGroup.toString.
func (m *Session2CommandGroup) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSession2CommandGroupToString == nil {
			callErr = fmt.Errorf("android.media.Session2CommandGroup.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midSession2CommandGroupToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// WriteToParcel calls android.media.Session2CommandGroup.writeToParcel.
func (m *Session2CommandGroup) WriteToParcel(arg0 *jni.Object, arg1 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSession2CommandGroupWriteToParcel == nil {
			callErr = fmt.Errorf("android.media.Session2CommandGroup.writeToParcel is not available on this device")
			return callErr
		}

		callErr = env.CallStaticVoidMethod(
			(*jni.Class)(unsafe.Pointer(clsSession2CommandGroup)),
			midSession2CommandGroupWriteToParcel, jni.ObjectValue(arg0), jni.IntValue(arg1),
		)
		return callErr
	})
	return callErr
}
