// Code generated by javagen. DO NOT EDIT.

package media

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// SoundPoolBuilder wraps android.media.SoundPool$Builder.
type SoundPoolBuilder struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// NewSoundPoolBuilder creates a new android.media.SoundPool$Builder instance.
func NewSoundPoolBuilder(vm *jni.VM) (*SoundPoolBuilder, error) {
	var t SoundPoolBuilder
	t.VM = vm

	err := vm.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			return err
		}
		if clsSoundPoolBuilder == nil {
			return fmt.Errorf("android.media.SoundPool$Builder is not available on this device")
		}
		if midSoundPoolBuilderCtor == nil {
			return fmt.Errorf("android.media.SoundPool$Builder constructor ()V is not available on this device")
		}
		obj, err := env.NewObject((*jni.Class)(unsafe.Pointer(clsSoundPoolBuilder)), midSoundPoolBuilderCtor)
		if err != nil {
			return err
		}
		t.Obj = env.NewGlobalRef(obj)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// Build calls android.media.SoundPool$Builder.build.
func (m *SoundPoolBuilder) Build() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSoundPoolBuilderBuild == nil {
			callErr = fmt.Errorf("android.media.SoundPool$Builder.build is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midSoundPoolBuilderBuild,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetAudioAttributes calls android.media.SoundPool$Builder.setAudioAttributes.
func (m *SoundPoolBuilder) SetAudioAttributes(arg0 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSoundPoolBuilderSetAudioAttributes == nil {
			callErr = fmt.Errorf("android.media.SoundPool$Builder.setAudioAttributes is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midSoundPoolBuilderSetAudioAttributes, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetAudioSessionId calls android.media.SoundPool$Builder.setAudioSessionId.
func (m *SoundPoolBuilder) SetAudioSessionId(arg0 int32) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSoundPoolBuilderSetAudioSessionId == nil {
			callErr = fmt.Errorf("android.media.SoundPool$Builder.setAudioSessionId is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midSoundPoolBuilderSetAudioSessionId, jni.IntValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetContext calls android.media.SoundPool$Builder.setContext.
func (m *SoundPoolBuilder) SetContext(arg0 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSoundPoolBuilderSetContext == nil {
			callErr = fmt.Errorf("android.media.SoundPool$Builder.setContext is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midSoundPoolBuilderSetContext, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetMaxStreams calls android.media.SoundPool$Builder.setMaxStreams.
func (m *SoundPoolBuilder) SetMaxStreams(arg0 int32) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSoundPoolBuilderSetMaxStreams == nil {
			callErr = fmt.Errorf("android.media.SoundPool$Builder.setMaxStreams is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midSoundPoolBuilderSetMaxStreams, jni.IntValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// ToString calls android.media.SoundPool$Builder.toString.
func (m *SoundPoolBuilder) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSoundPoolBuilderToString == nil {
			callErr = fmt.Errorf("android.media.SoundPool$Builder.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midSoundPoolBuilderToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
