// Code generated by javagen. DO NOT EDIT.

package aware

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// Characteristics wraps android.net.wifi.aware.Characteristics.
type Characteristics struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// DescribeContents calls android.net.wifi.aware.Characteristics.describeContents.
func (m *Characteristics) DescribeContents() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCharacteristicsDescribeContents == nil {
			callErr = fmt.Errorf("android.net.wifi.aware.Characteristics.describeContents is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midCharacteristicsDescribeContents,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetMaxMatchFilterLength calls android.net.wifi.aware.Characteristics.getMaxMatchFilterLength.
func (m *Characteristics) GetMaxMatchFilterLength() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCharacteristicsGetMaxMatchFilterLength == nil {
			callErr = fmt.Errorf("android.net.wifi.aware.Characteristics.getMaxMatchFilterLength is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midCharacteristicsGetMaxMatchFilterLength,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetMaxServiceNameLength calls android.net.wifi.aware.Characteristics.getMaxServiceNameLength.
func (m *Characteristics) GetMaxServiceNameLength() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCharacteristicsGetMaxServiceNameLength == nil {
			callErr = fmt.Errorf("android.net.wifi.aware.Characteristics.getMaxServiceNameLength is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midCharacteristicsGetMaxServiceNameLength,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetMaxServiceSpecificInfoLength calls android.net.wifi.aware.Characteristics.getMaxServiceSpecificInfoLength.
func (m *Characteristics) GetMaxServiceSpecificInfoLength() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCharacteristicsGetMaxServiceSpecificInfoLength == nil {
			callErr = fmt.Errorf("android.net.wifi.aware.Characteristics.getMaxServiceSpecificInfoLength is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midCharacteristicsGetMaxServiceSpecificInfoLength,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetNumberOfSupportedDataInterfaces calls android.net.wifi.aware.Characteristics.getNumberOfSupportedDataInterfaces.
func (m *Characteristics) GetNumberOfSupportedDataInterfaces() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCharacteristicsGetNumberOfSupportedDataInterfaces == nil {
			callErr = fmt.Errorf("android.net.wifi.aware.Characteristics.getNumberOfSupportedDataInterfaces is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midCharacteristicsGetNumberOfSupportedDataInterfaces,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetNumberOfSupportedDataPaths calls android.net.wifi.aware.Characteristics.getNumberOfSupportedDataPaths.
func (m *Characteristics) GetNumberOfSupportedDataPaths() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCharacteristicsGetNumberOfSupportedDataPaths == nil {
			callErr = fmt.Errorf("android.net.wifi.aware.Characteristics.getNumberOfSupportedDataPaths is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midCharacteristicsGetNumberOfSupportedDataPaths,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetNumberOfSupportedPublishSessions calls android.net.wifi.aware.Characteristics.getNumberOfSupportedPublishSessions.
func (m *Characteristics) GetNumberOfSupportedPublishSessions() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCharacteristicsGetNumberOfSupportedPublishSessions == nil {
			callErr = fmt.Errorf("android.net.wifi.aware.Characteristics.getNumberOfSupportedPublishSessions is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midCharacteristicsGetNumberOfSupportedPublishSessions,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetNumberOfSupportedSubscribeSessions calls android.net.wifi.aware.Characteristics.getNumberOfSupportedSubscribeSessions.
func (m *Characteristics) GetNumberOfSupportedSubscribeSessions() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCharacteristicsGetNumberOfSupportedSubscribeSessions == nil {
			callErr = fmt.Errorf("android.net.wifi.aware.Characteristics.getNumberOfSupportedSubscribeSessions is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midCharacteristicsGetNumberOfSupportedSubscribeSessions,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetSupportedCipherSuites calls android.net.wifi.aware.Characteristics.getSupportedCipherSuites.
func (m *Characteristics) GetSupportedCipherSuites() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCharacteristicsGetSupportedCipherSuites == nil {
			callErr = fmt.Errorf("android.net.wifi.aware.Characteristics.getSupportedCipherSuites is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midCharacteristicsGetSupportedCipherSuites,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetSupportedPairingCipherSuites calls android.net.wifi.aware.Characteristics.getSupportedPairingCipherSuites.
func (m *Characteristics) GetSupportedPairingCipherSuites() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCharacteristicsGetSupportedPairingCipherSuites == nil {
			callErr = fmt.Errorf("android.net.wifi.aware.Characteristics.getSupportedPairingCipherSuites is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midCharacteristicsGetSupportedPairingCipherSuites,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// IsAwarePairingSupported calls android.net.wifi.aware.Characteristics.isAwarePairingSupported.
func (m *Characteristics) IsAwarePairingSupported() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCharacteristicsIsAwarePairingSupported == nil {
			callErr = fmt.Errorf("android.net.wifi.aware.Characteristics.isAwarePairingSupported is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midCharacteristicsIsAwarePairingSupported,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// IsInstantCommunicationModeSupported calls android.net.wifi.aware.Characteristics.isInstantCommunicationModeSupported.
func (m *Characteristics) IsInstantCommunicationModeSupported() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCharacteristicsIsInstantCommunicationModeSupported == nil {
			callErr = fmt.Errorf("android.net.wifi.aware.Characteristics.isInstantCommunicationModeSupported is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midCharacteristicsIsInstantCommunicationModeSupported,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// IsSuspensionSupported calls android.net.wifi.aware.Characteristics.isSuspensionSupported.
func (m *Characteristics) IsSuspensionSupported() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCharacteristicsIsSuspensionSupported == nil {
			callErr = fmt.Errorf("android.net.wifi.aware.Characteristics.isSuspensionSupported is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midCharacteristicsIsSuspensionSupported,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// ToString calls android.net.wifi.aware.Characteristics.toString.
func (m *Characteristics) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCharacteristicsToString == nil {
			callErr = fmt.Errorf("android.net.wifi.aware.Characteristics.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midCharacteristicsToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// WriteToParcel calls android.net.wifi.aware.Characteristics.writeToParcel.
func (m *Characteristics) WriteToParcel(arg0 *jni.Object, arg1 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCharacteristicsWriteToParcel == nil {
			callErr = fmt.Errorf("android.net.wifi.aware.Characteristics.writeToParcel is not available on this device")
			return callErr
		}

		callErr = env.CallStaticVoidMethod(
			(*jni.Class)(unsafe.Pointer(clsCharacteristics)),
			midCharacteristicsWriteToParcel, jni.ObjectValue(arg0), jni.IntValue(arg1),
		)
		return callErr
	})
	return callErr
}
