// Code generated by javagen. DO NOT EDIT.

package aware

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// SubscribeConfig wraps android.net.wifi.aware.SubscribeConfig.
type SubscribeConfig struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// DescribeContents calls android.net.wifi.aware.SubscribeConfig.describeContents.
func (m *SubscribeConfig) DescribeContents() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSubscribeConfigDescribeContents == nil {
			callErr = fmt.Errorf("android.net.wifi.aware.SubscribeConfig.describeContents is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midSubscribeConfigDescribeContents,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// Equals calls android.net.wifi.aware.SubscribeConfig.equals.
func (m *SubscribeConfig) Equals(arg0 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSubscribeConfigEquals == nil {
			callErr = fmt.Errorf("android.net.wifi.aware.SubscribeConfig.equals is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midSubscribeConfigEquals, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// GetInstantCommunicationBand calls android.net.wifi.aware.SubscribeConfig.getInstantCommunicationBand.
func (m *SubscribeConfig) GetInstantCommunicationBand() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSubscribeConfigGetInstantCommunicationBand == nil {
			callErr = fmt.Errorf("android.net.wifi.aware.SubscribeConfig.getInstantCommunicationBand is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midSubscribeConfigGetInstantCommunicationBand,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetPairingConfig calls android.net.wifi.aware.SubscribeConfig.getPairingConfig.
func (m *SubscribeConfig) GetPairingConfig() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSubscribeConfigGetPairingConfig == nil {
			callErr = fmt.Errorf("android.net.wifi.aware.SubscribeConfig.getPairingConfig is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midSubscribeConfigGetPairingConfig,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// HashCode calls android.net.wifi.aware.SubscribeConfig.hashCode.
func (m *SubscribeConfig) HashCode() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSubscribeConfigHashCode == nil {
			callErr = fmt.Errorf("android.net.wifi.aware.SubscribeConfig.hashCode is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midSubscribeConfigHashCode,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// IsInstantCommunicationModeEnabled calls android.net.wifi.aware.SubscribeConfig.isInstantCommunicationModeEnabled.
func (m *SubscribeConfig) IsInstantCommunicationModeEnabled() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSubscribeConfigIsInstantCommunicationModeEnabled == nil {
			callErr = fmt.Errorf("android.net.wifi.aware.SubscribeConfig.isInstantCommunicationModeEnabled is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midSubscribeConfigIsInstantCommunicationModeEnabled,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// ToString calls android.net.wifi.aware.SubscribeConfig.toString.
func (m *SubscribeConfig) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSubscribeConfigToString == nil {
			callErr = fmt.Errorf("android.net.wifi.aware.SubscribeConfig.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midSubscribeConfigToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// WriteToParcel calls android.net.wifi.aware.SubscribeConfig.writeToParcel.
func (m *SubscribeConfig) WriteToParcel(arg0 *jni.Object, arg1 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSubscribeConfigWriteToParcel == nil {
			callErr = fmt.Errorf("android.net.wifi.aware.SubscribeConfig.writeToParcel is not available on this device")
			return callErr
		}

		callErr = env.CallStaticVoidMethod(
			(*jni.Class)(unsafe.Pointer(clsSubscribeConfig)),
			midSubscribeConfigWriteToParcel, jni.ObjectValue(arg0), jni.IntValue(arg1),
		)
		return callErr
	})
	return callErr
}
