// Code generated by javagen. DO NOT EDIT.

package center.dx.jni.generated;

import androidx.recyclerview.widget.RecyclerView$ViewHolder;
import center.dx.jni.internal.GoAbstractDispatch;

public class RecyclerView$ViewHolderAdapter extends androidx.recyclerview.widget.RecyclerView$ViewHolder {
    private final long handlerID;

    public RecyclerView$ViewHolderAdapter(long handlerID) {
        this.handlerID = handlerID;
    }

    @Override
    public int getPosition() {
        return (Integer) GoAbstractDispatch.invoke(
            handlerID, "getPosition", new Object[]{  }).intValue();
    }

    @Override
    public int getLayoutPosition() {
        return (Integer) GoAbstractDispatch.invoke(
            handlerID, "getLayoutPosition", new Object[]{  }).intValue();
    }

    @Override
    public int getAdapterPosition() {
        return (Integer) GoAbstractDispatch.invoke(
            handlerID, "getAdapterPosition", new Object[]{  }).intValue();
    }

    @Override
    public int getBindingAdapterPosition() {
        return (Integer) GoAbstractDispatch.invoke(
            handlerID, "getBindingAdapterPosition", new Object[]{  }).intValue();
    }

    @Override
    public int getAbsoluteAdapterPosition() {
        return (Integer) GoAbstractDispatch.invoke(
            handlerID, "getAbsoluteAdapterPosition", new Object[]{  }).intValue();
    }

    @Override
    public int getOldPosition() {
        return (Integer) GoAbstractDispatch.invoke(
            handlerID, "getOldPosition", new Object[]{  }).intValue();
    }

    @Override
    public long getItemId() {
        return (Long) GoAbstractDispatch.invoke(
            handlerID, "getItemId", new Object[]{  }).longValue();
    }

    @Override
    public int getItemViewType() {
        return (Integer) GoAbstractDispatch.invoke(
            handlerID, "getItemViewType", new Object[]{  }).intValue();
    }

    @Override
    public String toString() {
        return (String) GoAbstractDispatch.invoke(
            handlerID, "toString", new Object[]{  });
    }

    @Override
    public void setIsRecyclable(boolean arg0) {
        GoAbstractDispatch.invoke(
            handlerID, "setIsRecyclable", new Object[]{ Boolean.valueOf(arg0) });
    }

    @Override
    public boolean isRecyclable() {
        return (Boolean) GoAbstractDispatch.invoke(
            handlerID, "isRecyclable", new Object[]{  }).booleanValue();
    }
}
