// Code generated by javagen. DO NOT EDIT.

package widget

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// ActionMenuViewActionMenuChildView wraps androidx.appcompat.widget.ActionMenuView$ActionMenuChildView.
type ActionMenuViewActionMenuChildView struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// NeedsDividerBefore calls androidx.appcompat.widget.ActionMenuView$ActionMenuChildView.needsDividerBefore.
func (m *ActionMenuViewActionMenuChildView) NeedsDividerBefore() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midActionMenuViewActionMenuChildViewNeedsDividerBefore == nil {
			callErr = fmt.Errorf("androidx.appcompat.widget.ActionMenuView$ActionMenuChildView.needsDividerBefore is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midActionMenuViewActionMenuChildViewNeedsDividerBefore,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// NeedsDividerAfter calls androidx.appcompat.widget.ActionMenuView$ActionMenuChildView.needsDividerAfter.
func (m *ActionMenuViewActionMenuChildView) NeedsDividerAfter() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midActionMenuViewActionMenuChildViewNeedsDividerAfter == nil {
			callErr = fmt.Errorf("androidx.appcompat.widget.ActionMenuView$ActionMenuChildView.needsDividerAfter is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midActionMenuViewActionMenuChildViewNeedsDividerAfter,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// ToString calls androidx.appcompat.widget.ActionMenuView$ActionMenuChildView.toString.
func (m *ActionMenuViewActionMenuChildView) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midActionMenuViewActionMenuChildViewToString == nil {
			callErr = fmt.Errorf("androidx.appcompat.widget.ActionMenuView$ActionMenuChildView.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midActionMenuViewActionMenuChildViewToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
