// Code generated by javagen. DO NOT EDIT.

package widget

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// DecorContentParent wraps androidx.appcompat.widget.DecorContentParent.
type DecorContentParent struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// SetWindowCallback calls androidx.appcompat.widget.DecorContentParent.setWindowCallback.
func (m *DecorContentParent) SetWindowCallback(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDecorContentParentSetWindowCallback == nil {
			callErr = fmt.Errorf("androidx.appcompat.widget.DecorContentParent.setWindowCallback is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midDecorContentParentSetWindowCallback, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// SetWindowTitle calls androidx.appcompat.widget.DecorContentParent.setWindowTitle.
func (m *DecorContentParent) SetWindowTitle(arg0 string) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDecorContentParentSetWindowTitle == nil {
			callErr = fmt.Errorf("androidx.appcompat.widget.DecorContentParent.setWindowTitle is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		callErr = env.CallVoidMethod(
			m.Obj,
			midDecorContentParentSetWindowTitle, jni.ObjectValue(&jArg0.Object),
		)
		return callErr
	})
	return callErr
}

// GetTitle calls androidx.appcompat.widget.DecorContentParent.getTitle.
func (m *DecorContentParent) GetTitle() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDecorContentParentGetTitle == nil {
			callErr = fmt.Errorf("androidx.appcompat.widget.DecorContentParent.getTitle is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midDecorContentParentGetTitle,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// InitFeature calls androidx.appcompat.widget.DecorContentParent.initFeature.
func (m *DecorContentParent) InitFeature(arg0 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDecorContentParentInitFeature == nil {
			callErr = fmt.Errorf("androidx.appcompat.widget.DecorContentParent.initFeature is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midDecorContentParentInitFeature, jni.IntValue(arg0),
		)
		return callErr
	})
	return callErr
}

// SetUiOptions calls androidx.appcompat.widget.DecorContentParent.setUiOptions.
func (m *DecorContentParent) SetUiOptions(arg0 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDecorContentParentSetUiOptions == nil {
			callErr = fmt.Errorf("androidx.appcompat.widget.DecorContentParent.setUiOptions is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midDecorContentParentSetUiOptions, jni.IntValue(arg0),
		)
		return callErr
	})
	return callErr
}

// HasIcon calls androidx.appcompat.widget.DecorContentParent.hasIcon.
func (m *DecorContentParent) HasIcon() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDecorContentParentHasIcon == nil {
			callErr = fmt.Errorf("androidx.appcompat.widget.DecorContentParent.hasIcon is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midDecorContentParentHasIcon,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// HasLogo calls androidx.appcompat.widget.DecorContentParent.hasLogo.
func (m *DecorContentParent) HasLogo() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDecorContentParentHasLogo == nil {
			callErr = fmt.Errorf("androidx.appcompat.widget.DecorContentParent.hasLogo is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midDecorContentParentHasLogo,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// SetIcon1 calls androidx.appcompat.widget.DecorContentParent.setIcon.
func (m *DecorContentParent) SetIcon1(arg0 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDecorContentParentSetIcon1 == nil {
			callErr = fmt.Errorf("androidx.appcompat.widget.DecorContentParent.setIcon is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midDecorContentParentSetIcon1, jni.IntValue(arg0),
		)
		return callErr
	})
	return callErr
}

// SetIcon1_1 calls androidx.appcompat.widget.DecorContentParent.setIcon.
func (m *DecorContentParent) SetIcon1_1(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDecorContentParentSetIcon1_1 == nil {
			callErr = fmt.Errorf("androidx.appcompat.widget.DecorContentParent.setIcon is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midDecorContentParentSetIcon1_1, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// SetLogo calls androidx.appcompat.widget.DecorContentParent.setLogo.
func (m *DecorContentParent) SetLogo(arg0 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDecorContentParentSetLogo == nil {
			callErr = fmt.Errorf("androidx.appcompat.widget.DecorContentParent.setLogo is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midDecorContentParentSetLogo, jni.IntValue(arg0),
		)
		return callErr
	})
	return callErr
}

// CanShowOverflowMenu calls androidx.appcompat.widget.DecorContentParent.canShowOverflowMenu.
func (m *DecorContentParent) CanShowOverflowMenu() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDecorContentParentCanShowOverflowMenu == nil {
			callErr = fmt.Errorf("androidx.appcompat.widget.DecorContentParent.canShowOverflowMenu is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midDecorContentParentCanShowOverflowMenu,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// IsOverflowMenuShowing calls androidx.appcompat.widget.DecorContentParent.isOverflowMenuShowing.
func (m *DecorContentParent) IsOverflowMenuShowing() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDecorContentParentIsOverflowMenuShowing == nil {
			callErr = fmt.Errorf("androidx.appcompat.widget.DecorContentParent.isOverflowMenuShowing is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midDecorContentParentIsOverflowMenuShowing,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// IsOverflowMenuShowPending calls androidx.appcompat.widget.DecorContentParent.isOverflowMenuShowPending.
func (m *DecorContentParent) IsOverflowMenuShowPending() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDecorContentParentIsOverflowMenuShowPending == nil {
			callErr = fmt.Errorf("androidx.appcompat.widget.DecorContentParent.isOverflowMenuShowPending is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midDecorContentParentIsOverflowMenuShowPending,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// ShowOverflowMenu calls androidx.appcompat.widget.DecorContentParent.showOverflowMenu.
func (m *DecorContentParent) ShowOverflowMenu() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDecorContentParentShowOverflowMenu == nil {
			callErr = fmt.Errorf("androidx.appcompat.widget.DecorContentParent.showOverflowMenu is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midDecorContentParentShowOverflowMenu,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// HideOverflowMenu calls androidx.appcompat.widget.DecorContentParent.hideOverflowMenu.
func (m *DecorContentParent) HideOverflowMenu() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDecorContentParentHideOverflowMenu == nil {
			callErr = fmt.Errorf("androidx.appcompat.widget.DecorContentParent.hideOverflowMenu is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midDecorContentParentHideOverflowMenu,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// SetMenuPrepared calls androidx.appcompat.widget.DecorContentParent.setMenuPrepared.
func (m *DecorContentParent) SetMenuPrepared() error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDecorContentParentSetMenuPrepared == nil {
			callErr = fmt.Errorf("androidx.appcompat.widget.DecorContentParent.setMenuPrepared is not available on this device")
			return callErr
		}
		callErr = env.CallVoidMethod(
			m.Obj,
			midDecorContentParentSetMenuPrepared,
		)
		return callErr
	})
	return callErr
}

// SetMenu calls androidx.appcompat.widget.DecorContentParent.setMenu.
func (m *DecorContentParent) SetMenu(arg0 *jni.Object, arg1 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDecorContentParentSetMenu == nil {
			callErr = fmt.Errorf("androidx.appcompat.widget.DecorContentParent.setMenu is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midDecorContentParentSetMenu, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		return callErr
	})
	return callErr
}

// DismissPopups calls androidx.appcompat.widget.DecorContentParent.dismissPopups.
func (m *DecorContentParent) DismissPopups() error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDecorContentParentDismissPopups == nil {
			callErr = fmt.Errorf("androidx.appcompat.widget.DecorContentParent.dismissPopups is not available on this device")
			return callErr
		}
		callErr = env.CallVoidMethod(
			m.Obj,
			midDecorContentParentDismissPopups,
		)
		return callErr
	})
	return callErr
}

// ToString calls androidx.appcompat.widget.DecorContentParent.toString.
func (m *DecorContentParent) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDecorContentParentToString == nil {
			callErr = fmt.Errorf("androidx.appcompat.widget.DecorContentParent.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midDecorContentParentToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
