// Code generated by javagen. DO NOT EDIT.

package location

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// Kt wraps androidx.core.location.LocationKt.
type Kt struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// ToString calls androidx.core.location.LocationKt.toString.
func (m *Kt) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midKtToString == nil {
			callErr = fmt.Errorf("androidx.core.location.LocationKt.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midKtToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// Component1 calls androidx.core.location.LocationKt.component1.
func (m *Kt) Component1(arg0 *jni.Object) (float64, error) {
	var result float64
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midKtComponent1 == nil {
			callErr = fmt.Errorf("androidx.core.location.LocationKt.component1 is not available on this device")
			return callErr
		}

		result, callErr = env.CallStaticDoubleMethod(
			(*jni.Class)(unsafe.Pointer(clsKt)),
			midKtComponent1, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// Component2 calls androidx.core.location.LocationKt.component2.
func (m *Kt) Component2(arg0 *jni.Object) (float64, error) {
	var result float64
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midKtComponent2 == nil {
			callErr = fmt.Errorf("androidx.core.location.LocationKt.component2 is not available on this device")
			return callErr
		}

		result, callErr = env.CallStaticDoubleMethod(
			(*jni.Class)(unsafe.Pointer(clsKt)),
			midKtComponent2, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}
