// Code generated by javagen. DO NOT EDIT.

package widget

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// RadioButton wraps android.widget.RadioButton.
type RadioButton struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// NewRadioButton creates a new android.widget.RadioButton instance.
func NewRadioButton(vm *jni.VM, arg0 *jni.Object) (*RadioButton, error) {
	var t RadioButton
	t.VM = vm

	err := vm.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			return err
		}
		if clsRadioButton == nil {
			return fmt.Errorf("android.widget.RadioButton is not available on this device")
		}
		if midRadioButtonCtor == nil {
			return fmt.Errorf("android.widget.RadioButton constructor (Landroid/content/Context;)V is not available on this device")
		}

		obj, err := env.NewObject((*jni.Class)(unsafe.Pointer(clsRadioButton)), midRadioButtonCtor, jni.ObjectValue(arg0))
		if err != nil {
			return err
		}
		t.Obj = env.NewGlobalRef(obj)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// GetAccessibilityClassName calls android.widget.RadioButton.getAccessibilityClassName.
func (m *RadioButton) GetAccessibilityClassName() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRadioButtonGetAccessibilityClassName == nil {
			callErr = fmt.Errorf("android.widget.RadioButton.getAccessibilityClassName is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midRadioButtonGetAccessibilityClassName,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// OnInitializeAccessibilityNodeInfo calls android.widget.RadioButton.onInitializeAccessibilityNodeInfo.
func (m *RadioButton) OnInitializeAccessibilityNodeInfo(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRadioButtonOnInitializeAccessibilityNodeInfo == nil {
			callErr = fmt.Errorf("android.widget.RadioButton.onInitializeAccessibilityNodeInfo is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midRadioButtonOnInitializeAccessibilityNodeInfo, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// Toggle calls android.widget.RadioButton.toggle.
func (m *RadioButton) Toggle() error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRadioButtonToggle == nil {
			callErr = fmt.Errorf("android.widget.RadioButton.toggle is not available on this device")
			return callErr
		}
		callErr = env.CallVoidMethod(
			m.Obj,
			midRadioButtonToggle,
		)
		return callErr
	})
	return callErr
}

// ToString calls android.widget.RadioButton.toString.
func (m *RadioButton) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRadioButtonToString == nil {
			callErr = fmt.Errorf("android.widget.RadioButton.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midRadioButtonToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
