// Code generated by javagen. DO NOT EDIT.

package widget

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// VideoView wraps android.widget.VideoView.
type VideoView struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// NewVideoView creates a new android.widget.VideoView instance.
func NewVideoView(vm *jni.VM, arg0 *jni.Object) (*VideoView, error) {
	var t VideoView
	t.VM = vm

	err := vm.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			return err
		}
		if clsVideoView == nil {
			return fmt.Errorf("android.widget.VideoView is not available on this device")
		}
		if midVideoViewCtor == nil {
			return fmt.Errorf("android.widget.VideoView constructor (Landroid/content/Context;)V is not available on this device")
		}

		obj, err := env.NewObject((*jni.Class)(unsafe.Pointer(clsVideoView)), midVideoViewCtor, jni.ObjectValue(arg0))
		if err != nil {
			return err
		}
		t.Obj = env.NewGlobalRef(obj)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// AddSubtitleSource calls android.widget.VideoView.addSubtitleSource.
func (m *VideoView) AddSubtitleSource(arg0 *jni.Object, arg1 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewAddSubtitleSource == nil {
			callErr = fmt.Errorf("android.widget.VideoView.addSubtitleSource is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midVideoViewAddSubtitleSource, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		return callErr
	})
	return callErr
}

// CanPause calls android.widget.VideoView.canPause.
func (m *VideoView) CanPause() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewCanPause == nil {
			callErr = fmt.Errorf("android.widget.VideoView.canPause is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midVideoViewCanPause,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// CanSeekBackward calls android.widget.VideoView.canSeekBackward.
func (m *VideoView) CanSeekBackward() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewCanSeekBackward == nil {
			callErr = fmt.Errorf("android.widget.VideoView.canSeekBackward is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midVideoViewCanSeekBackward,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// CanSeekForward calls android.widget.VideoView.canSeekForward.
func (m *VideoView) CanSeekForward() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewCanSeekForward == nil {
			callErr = fmt.Errorf("android.widget.VideoView.canSeekForward is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midVideoViewCanSeekForward,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// Draw calls android.widget.VideoView.draw.
func (m *VideoView) Draw(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewDraw == nil {
			callErr = fmt.Errorf("android.widget.VideoView.draw is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midVideoViewDraw, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// GetAccessibilityClassName calls android.widget.VideoView.getAccessibilityClassName.
func (m *VideoView) GetAccessibilityClassName() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewGetAccessibilityClassName == nil {
			callErr = fmt.Errorf("android.widget.VideoView.getAccessibilityClassName is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midVideoViewGetAccessibilityClassName,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetAudioSessionId calls android.widget.VideoView.getAudioSessionId.
func (m *VideoView) GetAudioSessionId() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewGetAudioSessionId == nil {
			callErr = fmt.Errorf("android.widget.VideoView.getAudioSessionId is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midVideoViewGetAudioSessionId,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetBufferPercentage calls android.widget.VideoView.getBufferPercentage.
func (m *VideoView) GetBufferPercentage() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewGetBufferPercentage == nil {
			callErr = fmt.Errorf("android.widget.VideoView.getBufferPercentage is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midVideoViewGetBufferPercentage,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetCurrentPosition calls android.widget.VideoView.getCurrentPosition.
func (m *VideoView) GetCurrentPosition() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewGetCurrentPosition == nil {
			callErr = fmt.Errorf("android.widget.VideoView.getCurrentPosition is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midVideoViewGetCurrentPosition,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetDuration calls android.widget.VideoView.getDuration.
func (m *VideoView) GetDuration() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewGetDuration == nil {
			callErr = fmt.Errorf("android.widget.VideoView.getDuration is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midVideoViewGetDuration,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// IsPlaying calls android.widget.VideoView.isPlaying.
func (m *VideoView) IsPlaying() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewIsPlaying == nil {
			callErr = fmt.Errorf("android.widget.VideoView.isPlaying is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midVideoViewIsPlaying,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// OnKeyDown calls android.widget.VideoView.onKeyDown.
func (m *VideoView) OnKeyDown(arg0 int32, arg1 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewOnKeyDown == nil {
			callErr = fmt.Errorf("android.widget.VideoView.onKeyDown is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midVideoViewOnKeyDown, jni.IntValue(arg0), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// OnTouchEvent calls android.widget.VideoView.onTouchEvent.
func (m *VideoView) OnTouchEvent(arg0 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewOnTouchEvent == nil {
			callErr = fmt.Errorf("android.widget.VideoView.onTouchEvent is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midVideoViewOnTouchEvent, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// OnTrackballEvent calls android.widget.VideoView.onTrackballEvent.
func (m *VideoView) OnTrackballEvent(arg0 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewOnTrackballEvent == nil {
			callErr = fmt.Errorf("android.widget.VideoView.onTrackballEvent is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midVideoViewOnTrackballEvent, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// Pause calls android.widget.VideoView.pause.
func (m *VideoView) Pause() error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewPause == nil {
			callErr = fmt.Errorf("android.widget.VideoView.pause is not available on this device")
			return callErr
		}
		callErr = env.CallVoidMethod(
			m.Obj,
			midVideoViewPause,
		)
		return callErr
	})
	return callErr
}

// ResolveAdjustedSize calls android.widget.VideoView.resolveAdjustedSize.
func (m *VideoView) ResolveAdjustedSize(arg0 int32, arg1 int32) (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewResolveAdjustedSize == nil {
			callErr = fmt.Errorf("android.widget.VideoView.resolveAdjustedSize is not available on this device")
			return callErr
		}

		result, callErr = env.CallIntMethod(
			m.Obj,
			midVideoViewResolveAdjustedSize, jni.IntValue(arg0), jni.IntValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// Resume calls android.widget.VideoView.resume.
func (m *VideoView) Resume() error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewResume == nil {
			callErr = fmt.Errorf("android.widget.VideoView.resume is not available on this device")
			return callErr
		}
		callErr = env.CallVoidMethod(
			m.Obj,
			midVideoViewResume,
		)
		return callErr
	})
	return callErr
}

// SeekTo calls android.widget.VideoView.seekTo.
func (m *VideoView) SeekTo(arg0 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewSeekTo == nil {
			callErr = fmt.Errorf("android.widget.VideoView.seekTo is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midVideoViewSeekTo, jni.IntValue(arg0),
		)
		return callErr
	})
	return callErr
}

// SetAudioAttributes calls android.widget.VideoView.setAudioAttributes.
func (m *VideoView) SetAudioAttributes(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewSetAudioAttributes == nil {
			callErr = fmt.Errorf("android.widget.VideoView.setAudioAttributes is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midVideoViewSetAudioAttributes, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// SetAudioFocusRequest calls android.widget.VideoView.setAudioFocusRequest.
func (m *VideoView) SetAudioFocusRequest(arg0 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewSetAudioFocusRequest == nil {
			callErr = fmt.Errorf("android.widget.VideoView.setAudioFocusRequest is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midVideoViewSetAudioFocusRequest, jni.IntValue(arg0),
		)
		return callErr
	})
	return callErr
}

// SetMediaController calls android.widget.VideoView.setMediaController.
func (m *VideoView) SetMediaController(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewSetMediaController == nil {
			callErr = fmt.Errorf("android.widget.VideoView.setMediaController is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midVideoViewSetMediaController, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// SetOnCompletionListener calls android.widget.VideoView.setOnCompletionListener.
func (m *VideoView) SetOnCompletionListener(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewSetOnCompletionListener == nil {
			callErr = fmt.Errorf("android.widget.VideoView.setOnCompletionListener is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midVideoViewSetOnCompletionListener, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// SetOnErrorListener calls android.widget.VideoView.setOnErrorListener.
func (m *VideoView) SetOnErrorListener(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewSetOnErrorListener == nil {
			callErr = fmt.Errorf("android.widget.VideoView.setOnErrorListener is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midVideoViewSetOnErrorListener, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// SetOnInfoListener calls android.widget.VideoView.setOnInfoListener.
func (m *VideoView) SetOnInfoListener(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewSetOnInfoListener == nil {
			callErr = fmt.Errorf("android.widget.VideoView.setOnInfoListener is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midVideoViewSetOnInfoListener, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// SetOnPreparedListener calls android.widget.VideoView.setOnPreparedListener.
func (m *VideoView) SetOnPreparedListener(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewSetOnPreparedListener == nil {
			callErr = fmt.Errorf("android.widget.VideoView.setOnPreparedListener is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midVideoViewSetOnPreparedListener, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// SetVideoPath calls android.widget.VideoView.setVideoPath.
func (m *VideoView) SetVideoPath(arg0 string) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewSetVideoPath == nil {
			callErr = fmt.Errorf("android.widget.VideoView.setVideoPath is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		callErr = env.CallVoidMethod(
			m.Obj,
			midVideoViewSetVideoPath, jni.ObjectValue(&jArg0.Object),
		)
		return callErr
	})
	return callErr
}

// SetVideoURI calls android.widget.VideoView.setVideoURI.
func (m *VideoView) SetVideoURI(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewSetVideoURI == nil {
			callErr = fmt.Errorf("android.widget.VideoView.setVideoURI is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midVideoViewSetVideoURI, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// Start calls android.widget.VideoView.start.
func (m *VideoView) Start() error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewStart == nil {
			callErr = fmt.Errorf("android.widget.VideoView.start is not available on this device")
			return callErr
		}
		callErr = env.CallVoidMethod(
			m.Obj,
			midVideoViewStart,
		)
		return callErr
	})
	return callErr
}

// StopPlayback calls android.widget.VideoView.stopPlayback.
func (m *VideoView) StopPlayback() error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewStopPlayback == nil {
			callErr = fmt.Errorf("android.widget.VideoView.stopPlayback is not available on this device")
			return callErr
		}
		callErr = env.CallVoidMethod(
			m.Obj,
			midVideoViewStopPlayback,
		)
		return callErr
	})
	return callErr
}

// Suspend calls android.widget.VideoView.suspend.
func (m *VideoView) Suspend() error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewSuspend == nil {
			callErr = fmt.Errorf("android.widget.VideoView.suspend is not available on this device")
			return callErr
		}
		callErr = env.CallVoidMethod(
			m.Obj,
			midVideoViewSuspend,
		)
		return callErr
	})
	return callErr
}

// ToString calls android.widget.VideoView.toString.
func (m *VideoView) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVideoViewToString == nil {
			callErr = fmt.Errorf("android.widget.VideoView.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midVideoViewToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
