// Code generated by javagen. DO NOT EDIT.

package datepicker

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// MaterialDatePickerBuilder wraps com.google.android.material.datepicker.MaterialDatePicker$Builder.
type MaterialDatePickerBuilder struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// SetTextInputFormat calls com.google.android.material.datepicker.MaterialDatePicker$Builder.setTextInputFormat.
func (m *MaterialDatePickerBuilder) SetTextInputFormat(arg0 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midMaterialDatePickerBuilderSetTextInputFormat == nil {
			callErr = fmt.Errorf("com.google.android.material.datepicker.MaterialDatePicker$Builder.setTextInputFormat is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midMaterialDatePickerBuilderSetTextInputFormat, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetTheme calls com.google.android.material.datepicker.MaterialDatePicker$Builder.setTheme.
func (m *MaterialDatePickerBuilder) SetTheme(arg0 int32) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midMaterialDatePickerBuilderSetTheme == nil {
			callErr = fmt.Errorf("com.google.android.material.datepicker.MaterialDatePicker$Builder.setTheme is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midMaterialDatePickerBuilderSetTheme, jni.IntValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetCalendarConstraints calls com.google.android.material.datepicker.MaterialDatePicker$Builder.setCalendarConstraints.
func (m *MaterialDatePickerBuilder) SetCalendarConstraints(arg0 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midMaterialDatePickerBuilderSetCalendarConstraints == nil {
			callErr = fmt.Errorf("com.google.android.material.datepicker.MaterialDatePicker$Builder.setCalendarConstraints is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midMaterialDatePickerBuilderSetCalendarConstraints, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetDayViewDecorator calls com.google.android.material.datepicker.MaterialDatePicker$Builder.setDayViewDecorator.
func (m *MaterialDatePickerBuilder) SetDayViewDecorator(arg0 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midMaterialDatePickerBuilderSetDayViewDecorator == nil {
			callErr = fmt.Errorf("com.google.android.material.datepicker.MaterialDatePicker$Builder.setDayViewDecorator is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midMaterialDatePickerBuilderSetDayViewDecorator, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetTitleText1 calls com.google.android.material.datepicker.MaterialDatePicker$Builder.setTitleText.
func (m *MaterialDatePickerBuilder) SetTitleText1(arg0 int32) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midMaterialDatePickerBuilderSetTitleText1 == nil {
			callErr = fmt.Errorf("com.google.android.material.datepicker.MaterialDatePicker$Builder.setTitleText is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midMaterialDatePickerBuilderSetTitleText1, jni.IntValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetTitleText1_1 calls com.google.android.material.datepicker.MaterialDatePicker$Builder.setTitleText.
func (m *MaterialDatePickerBuilder) SetTitleText1_1(arg0 string) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midMaterialDatePickerBuilderSetTitleText1_1 == nil {
			callErr = fmt.Errorf("com.google.android.material.datepicker.MaterialDatePicker$Builder.setTitleText is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midMaterialDatePickerBuilderSetTitleText1_1, jni.ObjectValue(&jArg0.Object),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetPositiveButtonText1 calls com.google.android.material.datepicker.MaterialDatePicker$Builder.setPositiveButtonText.
func (m *MaterialDatePickerBuilder) SetPositiveButtonText1(arg0 int32) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midMaterialDatePickerBuilderSetPositiveButtonText1 == nil {
			callErr = fmt.Errorf("com.google.android.material.datepicker.MaterialDatePicker$Builder.setPositiveButtonText is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midMaterialDatePickerBuilderSetPositiveButtonText1, jni.IntValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetPositiveButtonText1_1 calls com.google.android.material.datepicker.MaterialDatePicker$Builder.setPositiveButtonText.
func (m *MaterialDatePickerBuilder) SetPositiveButtonText1_1(arg0 string) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midMaterialDatePickerBuilderSetPositiveButtonText1_1 == nil {
			callErr = fmt.Errorf("com.google.android.material.datepicker.MaterialDatePicker$Builder.setPositiveButtonText is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midMaterialDatePickerBuilderSetPositiveButtonText1_1, jni.ObjectValue(&jArg0.Object),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetPositiveButtonContentDescription1 calls com.google.android.material.datepicker.MaterialDatePicker$Builder.setPositiveButtonContentDescription.
func (m *MaterialDatePickerBuilder) SetPositiveButtonContentDescription1(arg0 int32) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midMaterialDatePickerBuilderSetPositiveButtonContentDescription1 == nil {
			callErr = fmt.Errorf("com.google.android.material.datepicker.MaterialDatePicker$Builder.setPositiveButtonContentDescription is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midMaterialDatePickerBuilderSetPositiveButtonContentDescription1, jni.IntValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetPositiveButtonContentDescription1_1 calls com.google.android.material.datepicker.MaterialDatePicker$Builder.setPositiveButtonContentDescription.
func (m *MaterialDatePickerBuilder) SetPositiveButtonContentDescription1_1(arg0 string) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midMaterialDatePickerBuilderSetPositiveButtonContentDescription1_1 == nil {
			callErr = fmt.Errorf("com.google.android.material.datepicker.MaterialDatePicker$Builder.setPositiveButtonContentDescription is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midMaterialDatePickerBuilderSetPositiveButtonContentDescription1_1, jni.ObjectValue(&jArg0.Object),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetNegativeButtonText1 calls com.google.android.material.datepicker.MaterialDatePicker$Builder.setNegativeButtonText.
func (m *MaterialDatePickerBuilder) SetNegativeButtonText1(arg0 int32) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midMaterialDatePickerBuilderSetNegativeButtonText1 == nil {
			callErr = fmt.Errorf("com.google.android.material.datepicker.MaterialDatePicker$Builder.setNegativeButtonText is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midMaterialDatePickerBuilderSetNegativeButtonText1, jni.IntValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetNegativeButtonText1_1 calls com.google.android.material.datepicker.MaterialDatePicker$Builder.setNegativeButtonText.
func (m *MaterialDatePickerBuilder) SetNegativeButtonText1_1(arg0 string) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midMaterialDatePickerBuilderSetNegativeButtonText1_1 == nil {
			callErr = fmt.Errorf("com.google.android.material.datepicker.MaterialDatePicker$Builder.setNegativeButtonText is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midMaterialDatePickerBuilderSetNegativeButtonText1_1, jni.ObjectValue(&jArg0.Object),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetNegativeButtonContentDescription1 calls com.google.android.material.datepicker.MaterialDatePicker$Builder.setNegativeButtonContentDescription.
func (m *MaterialDatePickerBuilder) SetNegativeButtonContentDescription1(arg0 int32) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midMaterialDatePickerBuilderSetNegativeButtonContentDescription1 == nil {
			callErr = fmt.Errorf("com.google.android.material.datepicker.MaterialDatePicker$Builder.setNegativeButtonContentDescription is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midMaterialDatePickerBuilderSetNegativeButtonContentDescription1, jni.IntValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetNegativeButtonContentDescription1_1 calls com.google.android.material.datepicker.MaterialDatePicker$Builder.setNegativeButtonContentDescription.
func (m *MaterialDatePickerBuilder) SetNegativeButtonContentDescription1_1(arg0 string) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midMaterialDatePickerBuilderSetNegativeButtonContentDescription1_1 == nil {
			callErr = fmt.Errorf("com.google.android.material.datepicker.MaterialDatePicker$Builder.setNegativeButtonContentDescription is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midMaterialDatePickerBuilderSetNegativeButtonContentDescription1_1, jni.ObjectValue(&jArg0.Object),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetInputMode calls com.google.android.material.datepicker.MaterialDatePicker$Builder.setInputMode.
func (m *MaterialDatePickerBuilder) SetInputMode(arg0 int32) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midMaterialDatePickerBuilderSetInputMode == nil {
			callErr = fmt.Errorf("com.google.android.material.datepicker.MaterialDatePicker$Builder.setInputMode is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midMaterialDatePickerBuilderSetInputMode, jni.IntValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// Build calls com.google.android.material.datepicker.MaterialDatePicker$Builder.build.
func (m *MaterialDatePickerBuilder) Build() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midMaterialDatePickerBuilderBuild == nil {
			callErr = fmt.Errorf("com.google.android.material.datepicker.MaterialDatePicker$Builder.build is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midMaterialDatePickerBuilderBuild,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// ToString calls com.google.android.material.datepicker.MaterialDatePicker$Builder.toString.
func (m *MaterialDatePickerBuilder) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midMaterialDatePickerBuilderToString == nil {
			callErr = fmt.Errorf("com.google.android.material.datepicker.MaterialDatePicker$Builder.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midMaterialDatePickerBuilderToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// DatePicker calls com.google.android.material.datepicker.MaterialDatePicker$Builder.datePicker.
func (m *MaterialDatePickerBuilder) DatePicker() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midMaterialDatePickerBuilderDatePicker == nil {
			callErr = fmt.Errorf("com.google.android.material.datepicker.MaterialDatePicker$Builder.datePicker is not available on this device")
			return callErr
		}
		result, callErr = env.CallStaticObjectMethod(
			(*jni.Class)(unsafe.Pointer(clsMaterialDatePickerBuilder)),
			midMaterialDatePickerBuilderDatePicker,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}
