// Code generated by javagen. DO NOT EDIT.

package center.dx.jni.generated.android.app.job;


import android.app.job.JobScheduler;
import center.dx.jni.internal.GoAbstractDispatch;


public class JobSchedulerAdapter extends android.app.job.JobScheduler {
    private final long handlerID;

    public JobSchedulerAdapter(long handlerID) {
        this.handlerID = handlerID;
    }

    @Override
    public boolean canRunUserInitiatedJobs() {
        return ((Boolean) GoAbstractDispatch.invoke(
            handlerID, "canRunUserInitiatedJobs", new Object[]{  })).booleanValue();
    }

    @Override
    public void cancel(int arg0) {
        GoAbstractDispatch.invoke(
            handlerID, "cancel", new Object[]{ Integer.valueOf(arg0) });
    }

    @Override
    public void cancelAll() {
        GoAbstractDispatch.invoke(
            handlerID, "cancelAll", new Object[]{  });
    }

    @Override
    public void cancelInAllNamespaces() {
        GoAbstractDispatch.invoke(
            handlerID, "cancelInAllNamespaces", new Object[]{  });
    }

    @Override
    public int enqueue(android.app.job.JobInfo arg0, android.app.job.JobWorkItem arg1) {
        return ((Integer) GoAbstractDispatch.invoke(
            handlerID, "enqueue", new Object[]{ arg0, arg1 })).intValue();
    }

    @Override
    public android.app.job.JobScheduler forNamespace(String arg0) {
        return (android.app.job.JobScheduler) GoAbstractDispatch.invoke(
            handlerID, "forNamespace", new Object[]{ arg0 });
    }

    @Override
    public java.util.List<android.app.job.JobInfo> getAllPendingJobs() {
        return (java.util.List<android.app.job.JobInfo>) GoAbstractDispatch.invoke(
            handlerID, "getAllPendingJobs", new Object[]{  });
    }

    @Override
    public String getNamespace() {
        return (String) GoAbstractDispatch.invoke(
            handlerID, "getNamespace", new Object[]{  });
    }

    @Override
    public android.app.job.JobInfo getPendingJob(int arg0) {
        return (android.app.job.JobInfo) GoAbstractDispatch.invoke(
            handlerID, "getPendingJob", new Object[]{ Integer.valueOf(arg0) });
    }

    @Override
    public int getPendingJobReason(int arg0) {
        return ((Integer) GoAbstractDispatch.invoke(
            handlerID, "getPendingJobReason", new Object[]{ Integer.valueOf(arg0) })).intValue();
    }

    @Override
    public int[] getPendingJobReasons(int arg0) {
        return (int[]) GoAbstractDispatch.invoke(
            handlerID, "getPendingJobReasons", new Object[]{ Integer.valueOf(arg0) });
    }

    @Override
    public java.util.List<android.app.job.PendingJobReasonsInfo> getPendingJobReasonsHistory(int arg0) {
        return (java.util.List<android.app.job.PendingJobReasonsInfo>) GoAbstractDispatch.invoke(
            handlerID, "getPendingJobReasonsHistory", new Object[]{ Integer.valueOf(arg0) });
    }

    @Override
    public int schedule(android.app.job.JobInfo arg0) {
        return ((Integer) GoAbstractDispatch.invoke(
            handlerID, "schedule", new Object[]{ arg0 })).intValue();
    }
}
