// Code generated by javagen. DO NOT EDIT.

package lifecycle

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// ViewModelStore wraps androidx.lifecycle.ViewModelStore.
type ViewModelStore struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// NewViewModelStore creates a new androidx.lifecycle.ViewModelStore instance.
func NewViewModelStore(vm *jni.VM) (*ViewModelStore, error) {
	var t ViewModelStore
	t.VM = vm

	err := vm.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			return err
		}
		obj, err := env.NewObject((*jni.Class)(unsafe.Pointer(clsViewModelStore)), midViewModelStoreCtor)
		if err != nil {
			return err
		}
		t.Obj = env.NewGlobalRef(obj)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// Put calls androidx.lifecycle.ViewModelStore.put.
func (m *ViewModelStore) Put(arg0 string, arg1 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midViewModelStorePut == nil {
			callErr = fmt.Errorf("androidx.lifecycle.ViewModelStore.put is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		callErr = env.CallVoidMethod(
			m.Obj,
			midViewModelStorePut, jni.ObjectValue(&jArg0.Object), jni.ObjectValue(arg1),
		)
		return callErr
	})
	return callErr
}

// Get calls androidx.lifecycle.ViewModelStore.get.
func (m *ViewModelStore) Get(arg0 string) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midViewModelStoreGet == nil {
			callErr = fmt.Errorf("androidx.lifecycle.ViewModelStore.get is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midViewModelStoreGet, jni.ObjectValue(&jArg0.Object),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// Keys calls androidx.lifecycle.ViewModelStore.keys.
func (m *ViewModelStore) Keys() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midViewModelStoreKeys == nil {
			callErr = fmt.Errorf("androidx.lifecycle.ViewModelStore.keys is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midViewModelStoreKeys,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// Clear calls androidx.lifecycle.ViewModelStore.clear.
func (m *ViewModelStore) Clear() error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midViewModelStoreClear == nil {
			callErr = fmt.Errorf("androidx.lifecycle.ViewModelStore.clear is not available on this device")
			return callErr
		}
		callErr = env.CallVoidMethod(
			m.Obj,
			midViewModelStoreClear,
		)
		return callErr
	})
	return callErr
}

// ToString calls androidx.lifecycle.ViewModelStore.toString.
func (m *ViewModelStore) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midViewModelStoreToString == nil {
			callErr = fmt.Errorf("androidx.lifecycle.ViewModelStore.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midViewModelStoreToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
