// Code generated by javagen. DO NOT EDIT.

package util

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// AndroidRuntimeException wraps android.util.AndroidRuntimeException.
type AndroidRuntimeException struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// NewAndroidRuntimeException creates a new android.util.AndroidRuntimeException instance.
func NewAndroidRuntimeException(vm *jni.VM) (*AndroidRuntimeException, error) {
	var t AndroidRuntimeException
	t.VM = vm

	err := vm.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			return err
		}
		if clsAndroidRuntimeException == nil {
			return fmt.Errorf("android.util.AndroidRuntimeException is not available on this device")
		}
		if midAndroidRuntimeExceptionCtor == nil {
			return fmt.Errorf("android.util.AndroidRuntimeException constructor ()V is not available on this device")
		}
		obj, err := env.NewObject((*jni.Class)(unsafe.Pointer(clsAndroidRuntimeException)), midAndroidRuntimeExceptionCtor)
		if err != nil {
			return err
		}
		t.Obj = env.NewGlobalRef(obj)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// ToString calls android.util.AndroidRuntimeException.toString.
func (m *AndroidRuntimeException) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midAndroidRuntimeExceptionToString == nil {
			callErr = fmt.Errorf("android.util.AndroidRuntimeException.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midAndroidRuntimeExceptionToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
