// Code generated by javagen. DO NOT EDIT.

package analyzer

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// DependencyGraph wraps androidx.constraintlayout.core.widgets.analyzer.DependencyGraph.
type DependencyGraph struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// NewDependencyGraph creates a new androidx.constraintlayout.core.widgets.analyzer.DependencyGraph instance.
func NewDependencyGraph(vm *jni.VM, arg0 *jni.Object) (*DependencyGraph, error) {
	var t DependencyGraph
	t.VM = vm

	err := vm.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			return err
		}
		if clsDependencyGraph == nil {
			return fmt.Errorf("androidx.constraintlayout.core.widgets.analyzer.DependencyGraph is not available on this device")
		}
		if midDependencyGraphCtor == nil {
			return fmt.Errorf("androidx.constraintlayout.core.widgets.analyzer.DependencyGraph constructor (Landroidx/constraintlayout/core/widgets/ConstraintWidgetContainer;)V is not available on this device")
		}

		obj, err := env.NewObject((*jni.Class)(unsafe.Pointer(clsDependencyGraph)), midDependencyGraphCtor, jni.ObjectValue(arg0))
		if err != nil {
			return err
		}
		t.Obj = env.NewGlobalRef(obj)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// SetMeasurer calls androidx.constraintlayout.core.widgets.analyzer.DependencyGraph.setMeasurer.
func (m *DependencyGraph) SetMeasurer(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDependencyGraphSetMeasurer == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.core.widgets.analyzer.DependencyGraph.setMeasurer is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midDependencyGraphSetMeasurer, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// DefineTerminalWidgets calls androidx.constraintlayout.core.widgets.analyzer.DependencyGraph.defineTerminalWidgets.
func (m *DependencyGraph) DefineTerminalWidgets(arg0 *jni.Object, arg1 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDependencyGraphDefineTerminalWidgets == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.core.widgets.analyzer.DependencyGraph.defineTerminalWidgets is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midDependencyGraphDefineTerminalWidgets, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		return callErr
	})
	return callErr
}

// DirectMeasure calls androidx.constraintlayout.core.widgets.analyzer.DependencyGraph.directMeasure.
func (m *DependencyGraph) DirectMeasure(arg0 bool) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDependencyGraphDirectMeasure == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.core.widgets.analyzer.DependencyGraph.directMeasure is not available on this device")
			return callErr
		}
		var jArg0 uint8
		if arg0 {
			jArg0 = jniTrue
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midDependencyGraphDirectMeasure, jni.BooleanValue(jArg0),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// DirectMeasureSetup calls androidx.constraintlayout.core.widgets.analyzer.DependencyGraph.directMeasureSetup.
func (m *DependencyGraph) DirectMeasureSetup(arg0 bool) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDependencyGraphDirectMeasureSetup == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.core.widgets.analyzer.DependencyGraph.directMeasureSetup is not available on this device")
			return callErr
		}
		var jArg0 uint8
		if arg0 {
			jArg0 = jniTrue
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midDependencyGraphDirectMeasureSetup, jni.BooleanValue(jArg0),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// DirectMeasureWithOrientation calls androidx.constraintlayout.core.widgets.analyzer.DependencyGraph.directMeasureWithOrientation.
func (m *DependencyGraph) DirectMeasureWithOrientation(arg0 bool, arg1 int32) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDependencyGraphDirectMeasureWithOrientation == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.core.widgets.analyzer.DependencyGraph.directMeasureWithOrientation is not available on this device")
			return callErr
		}
		var jArg0 uint8
		if arg0 {
			jArg0 = jniTrue
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midDependencyGraphDirectMeasureWithOrientation, jni.BooleanValue(jArg0), jni.IntValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// MeasureWidgets calls androidx.constraintlayout.core.widgets.analyzer.DependencyGraph.measureWidgets.
func (m *DependencyGraph) MeasureWidgets() error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDependencyGraphMeasureWidgets == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.core.widgets.analyzer.DependencyGraph.measureWidgets is not available on this device")
			return callErr
		}
		callErr = env.CallVoidMethod(
			m.Obj,
			midDependencyGraphMeasureWidgets,
		)
		return callErr
	})
	return callErr
}

// InvalidateGraph calls androidx.constraintlayout.core.widgets.analyzer.DependencyGraph.invalidateGraph.
func (m *DependencyGraph) InvalidateGraph() error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDependencyGraphInvalidateGraph == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.core.widgets.analyzer.DependencyGraph.invalidateGraph is not available on this device")
			return callErr
		}
		callErr = env.CallVoidMethod(
			m.Obj,
			midDependencyGraphInvalidateGraph,
		)
		return callErr
	})
	return callErr
}

// InvalidateMeasures calls androidx.constraintlayout.core.widgets.analyzer.DependencyGraph.invalidateMeasures.
func (m *DependencyGraph) InvalidateMeasures() error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDependencyGraphInvalidateMeasures == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.core.widgets.analyzer.DependencyGraph.invalidateMeasures is not available on this device")
			return callErr
		}
		callErr = env.CallVoidMethod(
			m.Obj,
			midDependencyGraphInvalidateMeasures,
		)
		return callErr
	})
	return callErr
}

// BuildGraph calls androidx.constraintlayout.core.widgets.analyzer.DependencyGraph.buildGraph.
func (m *DependencyGraph) BuildGraph() error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDependencyGraphBuildGraph == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.core.widgets.analyzer.DependencyGraph.buildGraph is not available on this device")
			return callErr
		}
		callErr = env.CallVoidMethod(
			m.Obj,
			midDependencyGraphBuildGraph,
		)
		return callErr
	})
	return callErr
}

// ToString calls androidx.constraintlayout.core.widgets.analyzer.DependencyGraph.toString.
func (m *DependencyGraph) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDependencyGraphToString == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.core.widgets.analyzer.DependencyGraph.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midDependencyGraphToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
