// Code generated by javagen. DO NOT EDIT.

package text

import "github.com/AndroidGoLab/jni/androidx/emoji2/text/consts"

const (
	EditorInfoMetaversionKey = consts.EditorInfoMetaversionKey
	EditorInfoReplaceAllKey  = consts.EditorInfoReplaceAllKey
)

const (
	LoadStateDefault           = consts.LoadStateDefault
	LoadStateLoading           = consts.LoadStateLoading
	LoadStateSucceeded         = consts.LoadStateSucceeded
	LoadStateFailed            = consts.LoadStateFailed
	ReplaceStrategyDefault     = consts.ReplaceStrategyDefault
	ReplaceStrategyAll         = consts.ReplaceStrategyAll
	ReplaceStrategyNonExistent = consts.ReplaceStrategyNonExistent
	LoadStrategyDefault        = consts.LoadStrategyDefault
	LoadStrategyManual         = consts.LoadStrategyManual
	EmojiUnsupported           = consts.EmojiUnsupported
	EmojiSupported             = consts.EmojiSupported
	EmojiFallback              = consts.EmojiFallback
	MaxEmojiCount              = consts.MaxEmojiCount
)
