// Code generated by javagen. DO NOT EDIT.

package inputmethod

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// CursorAnchorInfo wraps android.view.inputmethod.CursorAnchorInfo.
type CursorAnchorInfo struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// NewCursorAnchorInfo creates a new android.view.inputmethod.CursorAnchorInfo instance.
func NewCursorAnchorInfo(vm *jni.VM, arg0 *jni.Object) (*CursorAnchorInfo, error) {
	var t CursorAnchorInfo
	t.VM = vm

	err := vm.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			return err
		}
		if clsCursorAnchorInfo == nil {
			return fmt.Errorf("android.view.inputmethod.CursorAnchorInfo is not available on this device")
		}
		if midCursorAnchorInfoCtor == nil {
			return fmt.Errorf("android.view.inputmethod.CursorAnchorInfo constructor (Landroid/os/Parcel;)V is not available on this device")
		}

		obj, err := env.NewObject((*jni.Class)(unsafe.Pointer(clsCursorAnchorInfo)), midCursorAnchorInfoCtor, jni.ObjectValue(arg0))
		if err != nil {
			return err
		}
		t.Obj = env.NewGlobalRef(obj)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// DescribeContents calls android.view.inputmethod.CursorAnchorInfo.describeContents.
func (m *CursorAnchorInfo) DescribeContents() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCursorAnchorInfoDescribeContents == nil {
			callErr = fmt.Errorf("android.view.inputmethod.CursorAnchorInfo.describeContents is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midCursorAnchorInfoDescribeContents,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// Equals calls android.view.inputmethod.CursorAnchorInfo.equals.
func (m *CursorAnchorInfo) Equals(arg0 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCursorAnchorInfoEquals == nil {
			callErr = fmt.Errorf("android.view.inputmethod.CursorAnchorInfo.equals is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midCursorAnchorInfoEquals, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// GetCharacterBounds calls android.view.inputmethod.CursorAnchorInfo.getCharacterBounds.
func (m *CursorAnchorInfo) GetCharacterBounds(arg0 int32) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCursorAnchorInfoGetCharacterBounds == nil {
			callErr = fmt.Errorf("android.view.inputmethod.CursorAnchorInfo.getCharacterBounds is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midCursorAnchorInfoGetCharacterBounds, jni.IntValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetCharacterBoundsFlags calls android.view.inputmethod.CursorAnchorInfo.getCharacterBoundsFlags.
func (m *CursorAnchorInfo) GetCharacterBoundsFlags(arg0 int32) (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCursorAnchorInfoGetCharacterBoundsFlags == nil {
			callErr = fmt.Errorf("android.view.inputmethod.CursorAnchorInfo.getCharacterBoundsFlags is not available on this device")
			return callErr
		}

		result, callErr = env.CallIntMethod(
			m.Obj,
			midCursorAnchorInfoGetCharacterBoundsFlags, jni.IntValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetComposingText calls android.view.inputmethod.CursorAnchorInfo.getComposingText.
func (m *CursorAnchorInfo) GetComposingText() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCursorAnchorInfoGetComposingText == nil {
			callErr = fmt.Errorf("android.view.inputmethod.CursorAnchorInfo.getComposingText is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midCursorAnchorInfoGetComposingText,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetComposingTextStart calls android.view.inputmethod.CursorAnchorInfo.getComposingTextStart.
func (m *CursorAnchorInfo) GetComposingTextStart() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCursorAnchorInfoGetComposingTextStart == nil {
			callErr = fmt.Errorf("android.view.inputmethod.CursorAnchorInfo.getComposingTextStart is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midCursorAnchorInfoGetComposingTextStart,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetEditorBoundsInfo calls android.view.inputmethod.CursorAnchorInfo.getEditorBoundsInfo.
func (m *CursorAnchorInfo) GetEditorBoundsInfo() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCursorAnchorInfoGetEditorBoundsInfo == nil {
			callErr = fmt.Errorf("android.view.inputmethod.CursorAnchorInfo.getEditorBoundsInfo is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midCursorAnchorInfoGetEditorBoundsInfo,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetInsertionMarkerBaseline calls android.view.inputmethod.CursorAnchorInfo.getInsertionMarkerBaseline.
func (m *CursorAnchorInfo) GetInsertionMarkerBaseline() (float32, error) {
	var result float32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCursorAnchorInfoGetInsertionMarkerBaseline == nil {
			callErr = fmt.Errorf("android.view.inputmethod.CursorAnchorInfo.getInsertionMarkerBaseline is not available on this device")
			return callErr
		}
		result, callErr = env.CallFloatMethod(
			m.Obj,
			midCursorAnchorInfoGetInsertionMarkerBaseline,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetInsertionMarkerBottom calls android.view.inputmethod.CursorAnchorInfo.getInsertionMarkerBottom.
func (m *CursorAnchorInfo) GetInsertionMarkerBottom() (float32, error) {
	var result float32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCursorAnchorInfoGetInsertionMarkerBottom == nil {
			callErr = fmt.Errorf("android.view.inputmethod.CursorAnchorInfo.getInsertionMarkerBottom is not available on this device")
			return callErr
		}
		result, callErr = env.CallFloatMethod(
			m.Obj,
			midCursorAnchorInfoGetInsertionMarkerBottom,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetInsertionMarkerFlags calls android.view.inputmethod.CursorAnchorInfo.getInsertionMarkerFlags.
func (m *CursorAnchorInfo) GetInsertionMarkerFlags() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCursorAnchorInfoGetInsertionMarkerFlags == nil {
			callErr = fmt.Errorf("android.view.inputmethod.CursorAnchorInfo.getInsertionMarkerFlags is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midCursorAnchorInfoGetInsertionMarkerFlags,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetInsertionMarkerHorizontal calls android.view.inputmethod.CursorAnchorInfo.getInsertionMarkerHorizontal.
func (m *CursorAnchorInfo) GetInsertionMarkerHorizontal() (float32, error) {
	var result float32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCursorAnchorInfoGetInsertionMarkerHorizontal == nil {
			callErr = fmt.Errorf("android.view.inputmethod.CursorAnchorInfo.getInsertionMarkerHorizontal is not available on this device")
			return callErr
		}
		result, callErr = env.CallFloatMethod(
			m.Obj,
			midCursorAnchorInfoGetInsertionMarkerHorizontal,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetInsertionMarkerTop calls android.view.inputmethod.CursorAnchorInfo.getInsertionMarkerTop.
func (m *CursorAnchorInfo) GetInsertionMarkerTop() (float32, error) {
	var result float32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCursorAnchorInfoGetInsertionMarkerTop == nil {
			callErr = fmt.Errorf("android.view.inputmethod.CursorAnchorInfo.getInsertionMarkerTop is not available on this device")
			return callErr
		}
		result, callErr = env.CallFloatMethod(
			m.Obj,
			midCursorAnchorInfoGetInsertionMarkerTop,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetMatrix calls android.view.inputmethod.CursorAnchorInfo.getMatrix.
func (m *CursorAnchorInfo) GetMatrix() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCursorAnchorInfoGetMatrix == nil {
			callErr = fmt.Errorf("android.view.inputmethod.CursorAnchorInfo.getMatrix is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midCursorAnchorInfoGetMatrix,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetSelectionEnd calls android.view.inputmethod.CursorAnchorInfo.getSelectionEnd.
func (m *CursorAnchorInfo) GetSelectionEnd() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCursorAnchorInfoGetSelectionEnd == nil {
			callErr = fmt.Errorf("android.view.inputmethod.CursorAnchorInfo.getSelectionEnd is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midCursorAnchorInfoGetSelectionEnd,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetSelectionStart calls android.view.inputmethod.CursorAnchorInfo.getSelectionStart.
func (m *CursorAnchorInfo) GetSelectionStart() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCursorAnchorInfoGetSelectionStart == nil {
			callErr = fmt.Errorf("android.view.inputmethod.CursorAnchorInfo.getSelectionStart is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midCursorAnchorInfoGetSelectionStart,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetTextAppearanceInfo calls android.view.inputmethod.CursorAnchorInfo.getTextAppearanceInfo.
func (m *CursorAnchorInfo) GetTextAppearanceInfo() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCursorAnchorInfoGetTextAppearanceInfo == nil {
			callErr = fmt.Errorf("android.view.inputmethod.CursorAnchorInfo.getTextAppearanceInfo is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midCursorAnchorInfoGetTextAppearanceInfo,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetVisibleLineBounds calls android.view.inputmethod.CursorAnchorInfo.getVisibleLineBounds.
func (m *CursorAnchorInfo) GetVisibleLineBounds() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCursorAnchorInfoGetVisibleLineBounds == nil {
			callErr = fmt.Errorf("android.view.inputmethod.CursorAnchorInfo.getVisibleLineBounds is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midCursorAnchorInfoGetVisibleLineBounds,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// HashCode calls android.view.inputmethod.CursorAnchorInfo.hashCode.
func (m *CursorAnchorInfo) HashCode() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCursorAnchorInfoHashCode == nil {
			callErr = fmt.Errorf("android.view.inputmethod.CursorAnchorInfo.hashCode is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midCursorAnchorInfoHashCode,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// ToString calls android.view.inputmethod.CursorAnchorInfo.toString.
func (m *CursorAnchorInfo) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCursorAnchorInfoToString == nil {
			callErr = fmt.Errorf("android.view.inputmethod.CursorAnchorInfo.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midCursorAnchorInfoToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// WriteToParcel calls android.view.inputmethod.CursorAnchorInfo.writeToParcel.
func (m *CursorAnchorInfo) WriteToParcel(arg0 *jni.Object, arg1 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midCursorAnchorInfoWriteToParcel == nil {
			callErr = fmt.Errorf("android.view.inputmethod.CursorAnchorInfo.writeToParcel is not available on this device")
			return callErr
		}

		callErr = env.CallStaticVoidMethod(
			(*jni.Class)(unsafe.Pointer(clsCursorAnchorInfo)),
			midCursorAnchorInfoWriteToParcel, jni.ObjectValue(arg0), jni.IntValue(arg1),
		)
		return callErr
	})
	return callErr
}
