// Code generated by javagen. DO NOT EDIT.

package inputmethod

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// EditorBoundsInfoBuilder wraps android.view.inputmethod.EditorBoundsInfo$Builder.
type EditorBoundsInfoBuilder struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// NewEditorBoundsInfoBuilder creates a new android.view.inputmethod.EditorBoundsInfo$Builder instance.
func NewEditorBoundsInfoBuilder(vm *jni.VM) (*EditorBoundsInfoBuilder, error) {
	var t EditorBoundsInfoBuilder
	t.VM = vm

	err := vm.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			return err
		}
		if clsEditorBoundsInfoBuilder == nil {
			return fmt.Errorf("android.view.inputmethod.EditorBoundsInfo$Builder is not available on this device")
		}
		if midEditorBoundsInfoBuilderCtor == nil {
			return fmt.Errorf("android.view.inputmethod.EditorBoundsInfo$Builder constructor ()V is not available on this device")
		}
		obj, err := env.NewObject((*jni.Class)(unsafe.Pointer(clsEditorBoundsInfoBuilder)), midEditorBoundsInfoBuilderCtor)
		if err != nil {
			return err
		}
		t.Obj = env.NewGlobalRef(obj)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// Build calls android.view.inputmethod.EditorBoundsInfo$Builder.build.
func (m *EditorBoundsInfoBuilder) Build() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midEditorBoundsInfoBuilderBuild == nil {
			callErr = fmt.Errorf("android.view.inputmethod.EditorBoundsInfo$Builder.build is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midEditorBoundsInfoBuilderBuild,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetEditorBounds calls android.view.inputmethod.EditorBoundsInfo$Builder.setEditorBounds.
func (m *EditorBoundsInfoBuilder) SetEditorBounds(arg0 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midEditorBoundsInfoBuilderSetEditorBounds == nil {
			callErr = fmt.Errorf("android.view.inputmethod.EditorBoundsInfo$Builder.setEditorBounds is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midEditorBoundsInfoBuilderSetEditorBounds, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetHandwritingBounds calls android.view.inputmethod.EditorBoundsInfo$Builder.setHandwritingBounds.
func (m *EditorBoundsInfoBuilder) SetHandwritingBounds(arg0 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midEditorBoundsInfoBuilderSetHandwritingBounds == nil {
			callErr = fmt.Errorf("android.view.inputmethod.EditorBoundsInfo$Builder.setHandwritingBounds is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midEditorBoundsInfoBuilderSetHandwritingBounds, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// ToString calls android.view.inputmethod.EditorBoundsInfo$Builder.toString.
func (m *EditorBoundsInfoBuilder) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midEditorBoundsInfoBuilderToString == nil {
			callErr = fmt.Errorf("android.view.inputmethod.EditorBoundsInfo$Builder.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midEditorBoundsInfoBuilderToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
