// Code generated by javagen. DO NOT EDIT.

// Package widget provides Go bindings for androidx.core.widget.
package widget

import (
	"fmt"
	"sync"
	"unsafe"

	"github.com/AndroidGoLab/jni"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ sync.Once
	_ = unsafe.Pointer(nil)
	_ *jni.Env
)
