// Code generated by javagen. DO NOT EDIT.

package widget

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// ScrollerCompat wraps androidx.core.widget.ScrollerCompat.
type ScrollerCompat struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// IsFinished calls androidx.core.widget.ScrollerCompat.isFinished.
func (m *ScrollerCompat) IsFinished() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midScrollerCompatIsFinished == nil {
			callErr = fmt.Errorf("androidx.core.widget.ScrollerCompat.isFinished is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midScrollerCompatIsFinished,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// GetCurrX calls androidx.core.widget.ScrollerCompat.getCurrX.
func (m *ScrollerCompat) GetCurrX() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midScrollerCompatGetCurrX == nil {
			callErr = fmt.Errorf("androidx.core.widget.ScrollerCompat.getCurrX is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midScrollerCompatGetCurrX,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetCurrY calls androidx.core.widget.ScrollerCompat.getCurrY.
func (m *ScrollerCompat) GetCurrY() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midScrollerCompatGetCurrY == nil {
			callErr = fmt.Errorf("androidx.core.widget.ScrollerCompat.getCurrY is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midScrollerCompatGetCurrY,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetFinalX calls androidx.core.widget.ScrollerCompat.getFinalX.
func (m *ScrollerCompat) GetFinalX() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midScrollerCompatGetFinalX == nil {
			callErr = fmt.Errorf("androidx.core.widget.ScrollerCompat.getFinalX is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midScrollerCompatGetFinalX,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetFinalY calls androidx.core.widget.ScrollerCompat.getFinalY.
func (m *ScrollerCompat) GetFinalY() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midScrollerCompatGetFinalY == nil {
			callErr = fmt.Errorf("androidx.core.widget.ScrollerCompat.getFinalY is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midScrollerCompatGetFinalY,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetCurrVelocity calls androidx.core.widget.ScrollerCompat.getCurrVelocity.
func (m *ScrollerCompat) GetCurrVelocity() (float32, error) {
	var result float32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midScrollerCompatGetCurrVelocity == nil {
			callErr = fmt.Errorf("androidx.core.widget.ScrollerCompat.getCurrVelocity is not available on this device")
			return callErr
		}
		result, callErr = env.CallFloatMethod(
			m.Obj,
			midScrollerCompatGetCurrVelocity,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// ComputeScrollOffset calls androidx.core.widget.ScrollerCompat.computeScrollOffset.
func (m *ScrollerCompat) ComputeScrollOffset() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midScrollerCompatComputeScrollOffset == nil {
			callErr = fmt.Errorf("androidx.core.widget.ScrollerCompat.computeScrollOffset is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midScrollerCompatComputeScrollOffset,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// StartScroll4 calls androidx.core.widget.ScrollerCompat.startScroll.
func (m *ScrollerCompat) StartScroll4(
	arg0 int32,
	arg1 int32,
	arg2 int32,
	arg3 int32,
) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midScrollerCompatStartScroll4 == nil {
			callErr = fmt.Errorf("androidx.core.widget.ScrollerCompat.startScroll is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midScrollerCompatStartScroll4, jni.IntValue(arg0), jni.IntValue(arg1), jni.IntValue(arg2), jni.IntValue(arg3),
		)
		return callErr
	})
	return callErr
}

// StartScroll5_1 calls androidx.core.widget.ScrollerCompat.startScroll.
func (m *ScrollerCompat) StartScroll5_1(
	arg0 int32,
	arg1 int32,
	arg2 int32,
	arg3 int32,
	arg4 int32,
) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midScrollerCompatStartScroll5_1 == nil {
			callErr = fmt.Errorf("androidx.core.widget.ScrollerCompat.startScroll is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midScrollerCompatStartScroll5_1, jni.IntValue(arg0), jni.IntValue(arg1), jni.IntValue(arg2), jni.IntValue(arg3), jni.IntValue(arg4),
		)
		return callErr
	})
	return callErr
}

// Fling8 calls androidx.core.widget.ScrollerCompat.fling.
func (m *ScrollerCompat) Fling8(
	arg0 int32,
	arg1 int32,
	arg2 int32,
	arg3 int32,
	arg4 int32,
	arg5 int32,
	arg6 int32,
	arg7 int32,
) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midScrollerCompatFling8 == nil {
			callErr = fmt.Errorf("androidx.core.widget.ScrollerCompat.fling is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midScrollerCompatFling8, jni.IntValue(arg0), jni.IntValue(arg1), jni.IntValue(arg2), jni.IntValue(arg3), jni.IntValue(arg4), jni.IntValue(arg5), jni.IntValue(arg6), jni.IntValue(arg7),
		)
		return callErr
	})
	return callErr
}

// Fling10_1 calls androidx.core.widget.ScrollerCompat.fling.
func (m *ScrollerCompat) Fling10_1(
	arg0 int32,
	arg1 int32,
	arg2 int32,
	arg3 int32,
	arg4 int32,
	arg5 int32,
	arg6 int32,
	arg7 int32,
	arg8 int32,
	arg9 int32,
) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midScrollerCompatFling10_1 == nil {
			callErr = fmt.Errorf("androidx.core.widget.ScrollerCompat.fling is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midScrollerCompatFling10_1, jni.IntValue(arg0), jni.IntValue(arg1), jni.IntValue(arg2), jni.IntValue(arg3), jni.IntValue(arg4), jni.IntValue(arg5), jni.IntValue(arg6), jni.IntValue(arg7), jni.IntValue(arg8), jni.IntValue(arg9),
		)
		return callErr
	})
	return callErr
}

// SpringBack calls androidx.core.widget.ScrollerCompat.springBack.
func (m *ScrollerCompat) SpringBack(
	arg0 int32,
	arg1 int32,
	arg2 int32,
	arg3 int32,
	arg4 int32,
	arg5 int32,
) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midScrollerCompatSpringBack == nil {
			callErr = fmt.Errorf("androidx.core.widget.ScrollerCompat.springBack is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midScrollerCompatSpringBack, jni.IntValue(arg0), jni.IntValue(arg1), jni.IntValue(arg2), jni.IntValue(arg3), jni.IntValue(arg4), jni.IntValue(arg5),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// AbortAnimation calls androidx.core.widget.ScrollerCompat.abortAnimation.
func (m *ScrollerCompat) AbortAnimation() error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midScrollerCompatAbortAnimation == nil {
			callErr = fmt.Errorf("androidx.core.widget.ScrollerCompat.abortAnimation is not available on this device")
			return callErr
		}
		callErr = env.CallVoidMethod(
			m.Obj,
			midScrollerCompatAbortAnimation,
		)
		return callErr
	})
	return callErr
}

// NotifyHorizontalEdgeReached calls androidx.core.widget.ScrollerCompat.notifyHorizontalEdgeReached.
func (m *ScrollerCompat) NotifyHorizontalEdgeReached(
	arg0 int32,
	arg1 int32,
	arg2 int32,
) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midScrollerCompatNotifyHorizontalEdgeReached == nil {
			callErr = fmt.Errorf("androidx.core.widget.ScrollerCompat.notifyHorizontalEdgeReached is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midScrollerCompatNotifyHorizontalEdgeReached, jni.IntValue(arg0), jni.IntValue(arg1), jni.IntValue(arg2),
		)
		return callErr
	})
	return callErr
}

// NotifyVerticalEdgeReached calls androidx.core.widget.ScrollerCompat.notifyVerticalEdgeReached.
func (m *ScrollerCompat) NotifyVerticalEdgeReached(
	arg0 int32,
	arg1 int32,
	arg2 int32,
) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midScrollerCompatNotifyVerticalEdgeReached == nil {
			callErr = fmt.Errorf("androidx.core.widget.ScrollerCompat.notifyVerticalEdgeReached is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midScrollerCompatNotifyVerticalEdgeReached, jni.IntValue(arg0), jni.IntValue(arg1), jni.IntValue(arg2),
		)
		return callErr
	})
	return callErr
}

// IsOverScrolled calls androidx.core.widget.ScrollerCompat.isOverScrolled.
func (m *ScrollerCompat) IsOverScrolled() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midScrollerCompatIsOverScrolled == nil {
			callErr = fmt.Errorf("androidx.core.widget.ScrollerCompat.isOverScrolled is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midScrollerCompatIsOverScrolled,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// ToString calls androidx.core.widget.ScrollerCompat.toString.
func (m *ScrollerCompat) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midScrollerCompatToString == nil {
			callErr = fmt.Errorf("androidx.core.widget.ScrollerCompat.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midScrollerCompatToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// Create1 calls androidx.core.widget.ScrollerCompat.create.
func (m *ScrollerCompat) Create1(arg0 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midScrollerCompatCreate1 == nil {
			callErr = fmt.Errorf("androidx.core.widget.ScrollerCompat.create is not available on this device")
			return callErr
		}

		result, callErr = env.CallStaticObjectMethod(
			(*jni.Class)(unsafe.Pointer(clsScrollerCompat)),
			midScrollerCompatCreate1, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// Create2_1 calls androidx.core.widget.ScrollerCompat.create.
func (m *ScrollerCompat) Create2_1(arg0 *jni.Object, arg1 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midScrollerCompatCreate2_1 == nil {
			callErr = fmt.Errorf("androidx.core.widget.ScrollerCompat.create is not available on this device")
			return callErr
		}

		result, callErr = env.CallStaticObjectMethod(
			(*jni.Class)(unsafe.Pointer(clsScrollerCompat)),
			midScrollerCompatCreate2_1, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}
