// Code generated by javagen. DO NOT EDIT.

package strictmode

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// IncorrectContextUseViolation wraps android.os.strictmode.IncorrectContextUseViolation.
type IncorrectContextUseViolation struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// NewIncorrectContextUseViolation creates a new android.os.strictmode.IncorrectContextUseViolation instance.
func NewIncorrectContextUseViolation(vm *jni.VM, arg0 string, arg1 *jni.Object) (*IncorrectContextUseViolation, error) {
	var t IncorrectContextUseViolation
	t.VM = vm

	err := vm.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			return err
		}
		if clsIncorrectContextUseViolation == nil {
			return fmt.Errorf("android.os.strictmode.IncorrectContextUseViolation is not available on this device")
		}
		if midIncorrectContextUseViolationCtor == nil {
			return fmt.Errorf("android.os.strictmode.IncorrectContextUseViolation constructor (Ljava/lang/String;Ljava/lang/Throwable;)V is not available on this device")
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		obj, err := env.NewObject((*jni.Class)(unsafe.Pointer(clsIncorrectContextUseViolation)), midIncorrectContextUseViolationCtor, jni.ObjectValue(&jArg0.Object), jni.ObjectValue(arg1))
		if err != nil {
			return err
		}
		t.Obj = env.NewGlobalRef(obj)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// ToString calls android.os.strictmode.IncorrectContextUseViolation.toString.
func (m *IncorrectContextUseViolation) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midIncorrectContextUseViolationToString == nil {
			callErr = fmt.Errorf("android.os.strictmode.IncorrectContextUseViolation.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midIncorrectContextUseViolationToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
