// Code generated by javagen. DO NOT EDIT.

package utilities

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// PointProviderLab wraps com.google.android.material.color.utilities.PointProviderLab.
type PointProviderLab struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// NewPointProviderLab creates a new com.google.android.material.color.utilities.PointProviderLab instance.
func NewPointProviderLab(vm *jni.VM) (*PointProviderLab, error) {
	var t PointProviderLab
	t.VM = vm

	err := vm.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			return err
		}
		if clsPointProviderLab == nil {
			return fmt.Errorf("com.google.android.material.color.utilities.PointProviderLab is not available on this device")
		}
		if midPointProviderLabCtor == nil {
			return fmt.Errorf("com.google.android.material.color.utilities.PointProviderLab constructor ()V is not available on this device")
		}
		obj, err := env.NewObject((*jni.Class)(unsafe.Pointer(clsPointProviderLab)), midPointProviderLabCtor)
		if err != nil {
			return err
		}
		t.Obj = env.NewGlobalRef(obj)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// FromInt calls com.google.android.material.color.utilities.PointProviderLab.fromInt.
func (m *PointProviderLab) FromInt(arg0 int32) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPointProviderLabFromInt == nil {
			callErr = fmt.Errorf("com.google.android.material.color.utilities.PointProviderLab.fromInt is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midPointProviderLabFromInt, jni.IntValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// ToInt calls com.google.android.material.color.utilities.PointProviderLab.toInt.
func (m *PointProviderLab) ToInt(arg0 *jni.Object) (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPointProviderLabToInt == nil {
			callErr = fmt.Errorf("com.google.android.material.color.utilities.PointProviderLab.toInt is not available on this device")
			return callErr
		}

		result, callErr = env.CallIntMethod(
			m.Obj,
			midPointProviderLabToInt, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// Distance calls com.google.android.material.color.utilities.PointProviderLab.distance.
func (m *PointProviderLab) Distance(arg0 *jni.Object, arg1 *jni.Object) (float64, error) {
	var result float64
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPointProviderLabDistance == nil {
			callErr = fmt.Errorf("com.google.android.material.color.utilities.PointProviderLab.distance is not available on this device")
			return callErr
		}

		result, callErr = env.CallDoubleMethod(
			m.Obj,
			midPointProviderLabDistance, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// ToString calls com.google.android.material.color.utilities.PointProviderLab.toString.
func (m *PointProviderLab) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPointProviderLabToString == nil {
			callErr = fmt.Errorf("com.google.android.material.color.utilities.PointProviderLab.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midPointProviderLabToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
