// Code generated by javagen. DO NOT EDIT.

package resources

import (
	"fmt"
	"sync"
	"unsafe"

	"github.com/AndroidGoLab/jni"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

// jniTrue is the JNI representation of a true boolean value.
const jniTrue uint8 = 1

var (
	initOnce sync.Once
	initErr  error

	clsTextAppearance                            *jni.GlobalRef
	midTextAppearanceCtor                        jni.MethodID
	midTextAppearanceGetFont                     jni.MethodID
	midTextAppearanceGetFontAsync2               jni.MethodID
	midTextAppearanceGetFontAsync3_1             jni.MethodID
	midTextAppearanceGetFallbackFont             jni.MethodID
	midTextAppearanceUpdateDrawState             jni.MethodID
	midTextAppearanceUpdateMeasureState          jni.MethodID
	midTextAppearanceUpdateTextPaintMeasureState jni.MethodID
	midTextAppearanceGetTextColor                jni.MethodID
	midTextAppearanceSetTextColor                jni.MethodID
	midTextAppearanceGetTextSize                 jni.MethodID
	midTextAppearanceToString                    jni.MethodID

	clsTypefaceUtils                                     *jni.GlobalRef
	midTypefaceUtilsToString                             jni.MethodID
	midTypefaceUtilsMaybeCopyWithFontWeightAdjustment2   jni.MethodID
	midTypefaceUtilsMaybeCopyWithFontWeightAdjustment2_1 jni.MethodID

	clsCancelableFontCallback                      *jni.GlobalRef
	midCancelableFontCallbackCtor                  jni.MethodID
	midCancelableFontCallbackOnFontRetrieved       jni.MethodID
	midCancelableFontCallbackOnFontRetrievalFailed jni.MethodID
	midCancelableFontCallbackCancel                jni.MethodID
	midCancelableFontCallbackToString              jni.MethodID

	clsCancelableFontCallbackApplyFont         *jni.GlobalRef
	midCancelableFontCallbackApplyFontApply    jni.MethodID
	midCancelableFontCallbackApplyFontToString jni.MethodID

	clsMaterialResources                      *jni.GlobalRef
	midMaterialResourcesToString              jni.MethodID
	midMaterialResourcesGetColorStateList3    jni.MethodID
	midMaterialResourcesGetColorStateList3_1  jni.MethodID
	midMaterialResourcesGetDrawable           jni.MethodID
	midMaterialResourcesGetTextAppearance     jni.MethodID
	midMaterialResourcesGetDimensionPixelSize jni.MethodID
	midMaterialResourcesIsFontScaleAtLeast13  jni.MethodID
	midMaterialResourcesIsFontScaleAtLeast20  jni.MethodID
	midMaterialResourcesGetFontScale          jni.MethodID
	midMaterialResourcesGetUnscaledTextSize   jni.MethodID

	clsMaterialAttributes                                    *jni.GlobalRef
	midMaterialAttributesCtor                                jni.MethodID
	midMaterialAttributesToString                            jni.MethodID
	midMaterialAttributesResolve                             jni.MethodID
	midMaterialAttributesResolveTypedValueOrThrow2           jni.MethodID
	midMaterialAttributesResolveTypedValueOrThrow3_1         jni.MethodID
	midMaterialAttributesResolveOrThrow3                     jni.MethodID
	midMaterialAttributesResolveOrThrow2_1                   jni.MethodID
	midMaterialAttributesResolveBooleanOrThrow               jni.MethodID
	midMaterialAttributesResolveBoolean                      jni.MethodID
	midMaterialAttributesResolveInteger                      jni.MethodID
	midMaterialAttributesResolveMinimumAccessibleTouchTarget jni.MethodID
	midMaterialAttributesResolveDimension                    jni.MethodID

	clsTextAppearanceConfig                               *jni.GlobalRef
	midTextAppearanceConfigCtor                           jni.MethodID
	midTextAppearanceConfigToString                       jni.MethodID
	midTextAppearanceConfigSetShouldLoadFontSynchronously jni.MethodID
	midTextAppearanceConfigShouldLoadFontSynchronously    jni.MethodID

	clsTextAppearanceFontCallback                      *jni.GlobalRef
	midTextAppearanceFontCallbackOnFontRetrieved       jni.MethodID
	midTextAppearanceFontCallbackOnFontRetrievalFailed jni.MethodID
	midTextAppearanceFontCallbackToString              jni.MethodID
)

func ensureInit(env *jni.Env) error {
	initOnce.Do(func() {
		initErr = doInit(env)
	})
	return initErr
}

// Init resolves all JNI class and method references for this package.
// It is safe to call multiple times (uses sync.Once internally).
// Exported for E2E testing on Android.
func Init(env *jni.Env) error {
	return ensureInit(env)
}

func doInit(env *jni.Env) error {
	var c *jni.Class
	var err error

	c, err = env.FindClass("com/google/android/material/resources/TextAppearance")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsTextAppearance = env.NewGlobalRef(&c.Object)
		midTextAppearanceCtor, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsTextAppearance)), "<init>", "(Landroid/content/Context;I)V")
		if err != nil {
			env.ExceptionClear()
		}

		midTextAppearanceGetFont, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsTextAppearance)), "getFont", "(Landroid/content/Context;)Landroid/graphics/Typeface;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midTextAppearanceGetFontAsync2, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsTextAppearance)), "getFontAsync", "(Landroid/content/Context;Lcom/google/android/material/resources/TextAppearanceFontCallback;)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midTextAppearanceGetFontAsync3_1, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsTextAppearance)), "getFontAsync", "(Landroid/content/Context;Landroid/text/TextPaint;Lcom/google/android/material/resources/TextAppearanceFontCallback;)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midTextAppearanceGetFallbackFont, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsTextAppearance)), "getFallbackFont", "()Landroid/graphics/Typeface;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midTextAppearanceUpdateDrawState, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsTextAppearance)), "updateDrawState", "(Landroid/content/Context;Landroid/text/TextPaint;Lcom/google/android/material/resources/TextAppearanceFontCallback;)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midTextAppearanceUpdateMeasureState, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsTextAppearance)), "updateMeasureState", "(Landroid/content/Context;Landroid/text/TextPaint;Lcom/google/android/material/resources/TextAppearanceFontCallback;)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midTextAppearanceUpdateTextPaintMeasureState, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsTextAppearance)), "updateTextPaintMeasureState", "(Landroid/content/Context;Landroid/text/TextPaint;Landroid/graphics/Typeface;)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midTextAppearanceGetTextColor, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsTextAppearance)), "getTextColor", "()Landroid/content/res/ColorStateList;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midTextAppearanceSetTextColor, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsTextAppearance)), "setTextColor", "(Landroid/content/res/ColorStateList;)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midTextAppearanceGetTextSize, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsTextAppearance)), "getTextSize", "()F")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midTextAppearanceToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsTextAppearance)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("com/google/android/material/resources/TypefaceUtils")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsTypefaceUtils = env.NewGlobalRef(&c.Object)

		midTypefaceUtilsToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsTypefaceUtils)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midTypefaceUtilsMaybeCopyWithFontWeightAdjustment2, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsTypefaceUtils)), "maybeCopyWithFontWeightAdjustment", "(Landroid/content/Context;Landroid/graphics/Typeface;)Landroid/graphics/Typeface;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midTypefaceUtilsMaybeCopyWithFontWeightAdjustment2_1, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsTypefaceUtils)), "maybeCopyWithFontWeightAdjustment", "(Landroid/content/res/Configuration;Landroid/graphics/Typeface;)Landroid/graphics/Typeface;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("com/google/android/material/resources/CancelableFontCallback")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsCancelableFontCallback = env.NewGlobalRef(&c.Object)
		midCancelableFontCallbackCtor, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsCancelableFontCallback)), "<init>", "(Lcom/google/android/material/resources/CancelableFontCallback$ApplyFont;Landroid/graphics/Typeface;)V")
		if err != nil {
			env.ExceptionClear()
		}

		midCancelableFontCallbackOnFontRetrieved, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsCancelableFontCallback)), "onFontRetrieved", "(Landroid/graphics/Typeface;Z)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midCancelableFontCallbackOnFontRetrievalFailed, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsCancelableFontCallback)), "onFontRetrievalFailed", "(I)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midCancelableFontCallbackCancel, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsCancelableFontCallback)), "cancel", "()V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midCancelableFontCallbackToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsCancelableFontCallback)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("com/google/android/material/resources/CancelableFontCallback$ApplyFont")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsCancelableFontCallbackApplyFont = env.NewGlobalRef(&c.Object)

		midCancelableFontCallbackApplyFontApply, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsCancelableFontCallbackApplyFont)), "apply", "(Landroid/graphics/Typeface;)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midCancelableFontCallbackApplyFontToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsCancelableFontCallbackApplyFont)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("com/google/android/material/resources/MaterialResources")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsMaterialResources = env.NewGlobalRef(&c.Object)

		midMaterialResourcesToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsMaterialResources)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midMaterialResourcesGetColorStateList3, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsMaterialResources)), "getColorStateList", "(Landroid/content/Context;Landroid/content/res/TypedArray;I)Landroid/content/res/ColorStateList;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midMaterialResourcesGetColorStateList3_1, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsMaterialResources)), "getColorStateList", "(Landroid/content/Context;Landroidx/appcompat/widget/TintTypedArray;I)Landroid/content/res/ColorStateList;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midMaterialResourcesGetDrawable, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsMaterialResources)), "getDrawable", "(Landroid/content/Context;Landroid/content/res/TypedArray;I)Landroid/graphics/drawable/Drawable;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midMaterialResourcesGetTextAppearance, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsMaterialResources)), "getTextAppearance", "(Landroid/content/Context;Landroid/content/res/TypedArray;I)Lcom/google/android/material/resources/TextAppearance;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midMaterialResourcesGetDimensionPixelSize, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsMaterialResources)), "getDimensionPixelSize", "(Landroid/content/Context;Landroid/content/res/TypedArray;II)I")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midMaterialResourcesIsFontScaleAtLeast13, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsMaterialResources)), "isFontScaleAtLeast1_3", "(Landroid/content/Context;)Z")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midMaterialResourcesIsFontScaleAtLeast20, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsMaterialResources)), "isFontScaleAtLeast2_0", "(Landroid/content/Context;)Z")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midMaterialResourcesGetFontScale, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsMaterialResources)), "getFontScale", "(Landroid/content/Context;)F")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midMaterialResourcesGetUnscaledTextSize, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsMaterialResources)), "getUnscaledTextSize", "(Landroid/content/Context;II)I")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("com/google/android/material/resources/MaterialAttributes")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsMaterialAttributes = env.NewGlobalRef(&c.Object)
		midMaterialAttributesCtor, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsMaterialAttributes)), "<init>", "()V")
		if err != nil {
			env.ExceptionClear()
		}

		midMaterialAttributesToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsMaterialAttributes)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midMaterialAttributesResolve, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsMaterialAttributes)), "resolve", "(Landroid/content/Context;I)Landroid/util/TypedValue;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midMaterialAttributesResolveTypedValueOrThrow2, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsMaterialAttributes)), "resolveTypedValueOrThrow", "(Landroid/view/View;I)Landroid/util/TypedValue;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midMaterialAttributesResolveTypedValueOrThrow3_1, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsMaterialAttributes)), "resolveTypedValueOrThrow", "(Landroid/content/Context;ILjava/lang/String;)Landroid/util/TypedValue;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midMaterialAttributesResolveOrThrow3, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsMaterialAttributes)), "resolveOrThrow", "(Landroid/content/Context;ILjava/lang/String;)I")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midMaterialAttributesResolveOrThrow2_1, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsMaterialAttributes)), "resolveOrThrow", "(Landroid/view/View;I)I")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midMaterialAttributesResolveBooleanOrThrow, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsMaterialAttributes)), "resolveBooleanOrThrow", "(Landroid/content/Context;ILjava/lang/String;)Z")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midMaterialAttributesResolveBoolean, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsMaterialAttributes)), "resolveBoolean", "(Landroid/content/Context;IZ)Z")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midMaterialAttributesResolveInteger, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsMaterialAttributes)), "resolveInteger", "(Landroid/content/Context;II)I")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midMaterialAttributesResolveMinimumAccessibleTouchTarget, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsMaterialAttributes)), "resolveMinimumAccessibleTouchTarget", "(Landroid/content/Context;)I")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midMaterialAttributesResolveDimension, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsMaterialAttributes)), "resolveDimension", "(Landroid/content/Context;II)I")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("com/google/android/material/resources/TextAppearanceConfig")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsTextAppearanceConfig = env.NewGlobalRef(&c.Object)
		midTextAppearanceConfigCtor, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsTextAppearanceConfig)), "<init>", "()V")
		if err != nil {
			env.ExceptionClear()
		}

		midTextAppearanceConfigToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsTextAppearanceConfig)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midTextAppearanceConfigSetShouldLoadFontSynchronously, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsTextAppearanceConfig)), "setShouldLoadFontSynchronously", "(Z)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midTextAppearanceConfigShouldLoadFontSynchronously, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsTextAppearanceConfig)), "shouldLoadFontSynchronously", "()Z")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	c, err = env.FindClass("com/google/android/material/resources/TextAppearanceFontCallback")
	if err != nil {
		// Class may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	} else {
		clsTextAppearanceFontCallback = env.NewGlobalRef(&c.Object)

		midTextAppearanceFontCallbackOnFontRetrieved, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsTextAppearanceFontCallback)), "onFontRetrieved", "(Landroid/graphics/Typeface;Z)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midTextAppearanceFontCallbackOnFontRetrievalFailed, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsTextAppearanceFontCallback)), "onFontRetrievalFailed", "(I)V")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

		midTextAppearanceFontCallbackToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsTextAppearanceFontCallback)), "toString", "()Ljava/lang/String;")
		if err != nil {
			// Method may not exist on this device's API level; skip and
			// report at invocation time instead of failing the entire init.
			env.ExceptionClear()
		}

	}

	return nil
}
