// Code generated by javagen. DO NOT EDIT.

package app

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

// AlarmManagerCompat wraps androidx.core.app.AlarmManagerCompat.
type AlarmManagerCompat struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// ToString calls androidx.core.app.AlarmManagerCompat.toString.
func (m *AlarmManagerCompat) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midAlarmManagerCompatToString == nil {
			callErr = fmt.Errorf("androidx.core.app.AlarmManagerCompat.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midAlarmManagerCompatToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// SetAlarmClock calls androidx.core.app.AlarmManagerCompat.setAlarmClock.
func (m *AlarmManagerCompat) SetAlarmClock(
	arg0 *jni.Object,
	arg1 int64,
	arg2 *jni.Object,
	arg3 *jni.Object,
) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midAlarmManagerCompatSetAlarmClock == nil {
			callErr = fmt.Errorf("androidx.core.app.AlarmManagerCompat.setAlarmClock is not available on this device")
			return callErr
		}

		callErr = env.CallStaticVoidMethod(
			(*jni.Class)(unsafe.Pointer(clsAlarmManagerCompat)),
			midAlarmManagerCompatSetAlarmClock, jni.ObjectValue(arg0), jni.LongValue(arg1), jni.ObjectValue(arg2), jni.ObjectValue(arg3),
		)
		return callErr
	})
	return callErr
}

// SetAndAllowWhileIdle calls androidx.core.app.AlarmManagerCompat.setAndAllowWhileIdle.
func (m *AlarmManagerCompat) SetAndAllowWhileIdle(
	arg0 *jni.Object,
	arg1 int32,
	arg2 int64,
	arg3 *jni.Object,
) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midAlarmManagerCompatSetAndAllowWhileIdle == nil {
			callErr = fmt.Errorf("androidx.core.app.AlarmManagerCompat.setAndAllowWhileIdle is not available on this device")
			return callErr
		}

		callErr = env.CallStaticVoidMethod(
			(*jni.Class)(unsafe.Pointer(clsAlarmManagerCompat)),
			midAlarmManagerCompatSetAndAllowWhileIdle, jni.ObjectValue(arg0), jni.IntValue(arg1), jni.LongValue(arg2), jni.ObjectValue(arg3),
		)
		return callErr
	})
	return callErr
}

// SetExact calls androidx.core.app.AlarmManagerCompat.setExact.
func (m *AlarmManagerCompat) SetExact(
	arg0 *jni.Object,
	arg1 int32,
	arg2 int64,
	arg3 *jni.Object,
) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midAlarmManagerCompatSetExact == nil {
			callErr = fmt.Errorf("androidx.core.app.AlarmManagerCompat.setExact is not available on this device")
			return callErr
		}

		callErr = env.CallStaticVoidMethod(
			(*jni.Class)(unsafe.Pointer(clsAlarmManagerCompat)),
			midAlarmManagerCompatSetExact, jni.ObjectValue(arg0), jni.IntValue(arg1), jni.LongValue(arg2), jni.ObjectValue(arg3),
		)
		return callErr
	})
	return callErr
}

// SetExactAndAllowWhileIdle calls androidx.core.app.AlarmManagerCompat.setExactAndAllowWhileIdle.
func (m *AlarmManagerCompat) SetExactAndAllowWhileIdle(
	arg0 *jni.Object,
	arg1 int32,
	arg2 int64,
	arg3 *jni.Object,
) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midAlarmManagerCompatSetExactAndAllowWhileIdle == nil {
			callErr = fmt.Errorf("androidx.core.app.AlarmManagerCompat.setExactAndAllowWhileIdle is not available on this device")
			return callErr
		}

		callErr = env.CallStaticVoidMethod(
			(*jni.Class)(unsafe.Pointer(clsAlarmManagerCompat)),
			midAlarmManagerCompatSetExactAndAllowWhileIdle, jni.ObjectValue(arg0), jni.IntValue(arg1), jni.LongValue(arg2), jni.ObjectValue(arg3),
		)
		return callErr
	})
	return callErr
}

// CanScheduleExactAlarms calls androidx.core.app.AlarmManagerCompat.canScheduleExactAlarms.
func (m *AlarmManagerCompat) CanScheduleExactAlarms(arg0 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midAlarmManagerCompatCanScheduleExactAlarms == nil {
			callErr = fmt.Errorf("androidx.core.app.AlarmManagerCompat.canScheduleExactAlarms is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallStaticBooleanMethod(
			(*jni.Class)(unsafe.Pointer(clsAlarmManagerCompat)),
			midAlarmManagerCompatCanScheduleExactAlarms, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}
