// Code generated by javagen. DO NOT EDIT.

package app

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

// NotificationCompatMessagingStyle wraps androidx.core.app.NotificationCompat$MessagingStyle.
type NotificationCompatMessagingStyle struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// GetUserDisplayName calls androidx.core.app.NotificationCompat$MessagingStyle.getUserDisplayName.
func (m *NotificationCompatMessagingStyle) GetUserDisplayName() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midNotificationCompatMessagingStyleGetUserDisplayName == nil {
			callErr = fmt.Errorf("androidx.core.app.NotificationCompat$MessagingStyle.getUserDisplayName is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midNotificationCompatMessagingStyleGetUserDisplayName,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetUser calls androidx.core.app.NotificationCompat$MessagingStyle.getUser.
func (m *NotificationCompatMessagingStyle) GetUser() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midNotificationCompatMessagingStyleGetUser == nil {
			callErr = fmt.Errorf("androidx.core.app.NotificationCompat$MessagingStyle.getUser is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midNotificationCompatMessagingStyleGetUser,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetConversationTitle calls androidx.core.app.NotificationCompat$MessagingStyle.setConversationTitle.
func (m *NotificationCompatMessagingStyle) SetConversationTitle(arg0 string) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midNotificationCompatMessagingStyleSetConversationTitle == nil {
			callErr = fmt.Errorf("androidx.core.app.NotificationCompat$MessagingStyle.setConversationTitle is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midNotificationCompatMessagingStyleSetConversationTitle, jni.ObjectValue(&jArg0.Object),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetConversationTitle calls androidx.core.app.NotificationCompat$MessagingStyle.getConversationTitle.
func (m *NotificationCompatMessagingStyle) GetConversationTitle() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midNotificationCompatMessagingStyleGetConversationTitle == nil {
			callErr = fmt.Errorf("androidx.core.app.NotificationCompat$MessagingStyle.getConversationTitle is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midNotificationCompatMessagingStyleGetConversationTitle,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// AddMessage3 calls androidx.core.app.NotificationCompat$MessagingStyle.addMessage.
func (m *NotificationCompatMessagingStyle) AddMessage3(
	arg0 string,
	arg1 int64,
	arg2 string,
) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midNotificationCompatMessagingStyleAddMessage3 == nil {
			callErr = fmt.Errorf("androidx.core.app.NotificationCompat$MessagingStyle.addMessage is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		jArg2, err := env.NewStringUTF(arg2)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg2.Object)

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midNotificationCompatMessagingStyleAddMessage3, jni.ObjectValue(&jArg0.Object), jni.LongValue(arg1), jni.ObjectValue(&jArg2.Object),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// AddMessage3_1 calls androidx.core.app.NotificationCompat$MessagingStyle.addMessage.
func (m *NotificationCompatMessagingStyle) AddMessage3_1(
	arg0 string,
	arg1 int64,
	arg2 *jni.Object,
) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midNotificationCompatMessagingStyleAddMessage3_1 == nil {
			callErr = fmt.Errorf("androidx.core.app.NotificationCompat$MessagingStyle.addMessage is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midNotificationCompatMessagingStyleAddMessage3_1, jni.ObjectValue(&jArg0.Object), jni.LongValue(arg1), jni.ObjectValue(arg2),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// AddMessage1_2 calls androidx.core.app.NotificationCompat$MessagingStyle.addMessage.
func (m *NotificationCompatMessagingStyle) AddMessage1_2(arg0 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midNotificationCompatMessagingStyleAddMessage1_2 == nil {
			callErr = fmt.Errorf("androidx.core.app.NotificationCompat$MessagingStyle.addMessage is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midNotificationCompatMessagingStyleAddMessage1_2, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// AddHistoricMessage calls androidx.core.app.NotificationCompat$MessagingStyle.addHistoricMessage.
func (m *NotificationCompatMessagingStyle) AddHistoricMessage(arg0 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midNotificationCompatMessagingStyleAddHistoricMessage == nil {
			callErr = fmt.Errorf("androidx.core.app.NotificationCompat$MessagingStyle.addHistoricMessage is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midNotificationCompatMessagingStyleAddHistoricMessage, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetMessages calls androidx.core.app.NotificationCompat$MessagingStyle.getMessages.
func (m *NotificationCompatMessagingStyle) GetMessages() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midNotificationCompatMessagingStyleGetMessages == nil {
			callErr = fmt.Errorf("androidx.core.app.NotificationCompat$MessagingStyle.getMessages is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midNotificationCompatMessagingStyleGetMessages,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetHistoricMessages calls androidx.core.app.NotificationCompat$MessagingStyle.getHistoricMessages.
func (m *NotificationCompatMessagingStyle) GetHistoricMessages() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midNotificationCompatMessagingStyleGetHistoricMessages == nil {
			callErr = fmt.Errorf("androidx.core.app.NotificationCompat$MessagingStyle.getHistoricMessages is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midNotificationCompatMessagingStyleGetHistoricMessages,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetGroupConversation calls androidx.core.app.NotificationCompat$MessagingStyle.setGroupConversation.
func (m *NotificationCompatMessagingStyle) SetGroupConversation(arg0 bool) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midNotificationCompatMessagingStyleSetGroupConversation == nil {
			callErr = fmt.Errorf("androidx.core.app.NotificationCompat$MessagingStyle.setGroupConversation is not available on this device")
			return callErr
		}
		var jArg0 uint8
		if arg0 {
			jArg0 = jniTrue
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midNotificationCompatMessagingStyleSetGroupConversation, jni.BooleanValue(jArg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// IsGroupConversation calls androidx.core.app.NotificationCompat$MessagingStyle.isGroupConversation.
func (m *NotificationCompatMessagingStyle) IsGroupConversation() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midNotificationCompatMessagingStyleIsGroupConversation == nil {
			callErr = fmt.Errorf("androidx.core.app.NotificationCompat$MessagingStyle.isGroupConversation is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midNotificationCompatMessagingStyleIsGroupConversation,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// Apply calls androidx.core.app.NotificationCompat$MessagingStyle.apply.
func (m *NotificationCompatMessagingStyle) Apply(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midNotificationCompatMessagingStyleApply == nil {
			callErr = fmt.Errorf("androidx.core.app.NotificationCompat$MessagingStyle.apply is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midNotificationCompatMessagingStyleApply, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// AddCompatExtras calls androidx.core.app.NotificationCompat$MessagingStyle.addCompatExtras.
func (m *NotificationCompatMessagingStyle) AddCompatExtras(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midNotificationCompatMessagingStyleAddCompatExtras == nil {
			callErr = fmt.Errorf("androidx.core.app.NotificationCompat$MessagingStyle.addCompatExtras is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midNotificationCompatMessagingStyleAddCompatExtras, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// ToString calls androidx.core.app.NotificationCompat$MessagingStyle.toString.
func (m *NotificationCompatMessagingStyle) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midNotificationCompatMessagingStyleToString == nil {
			callErr = fmt.Errorf("androidx.core.app.NotificationCompat$MessagingStyle.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midNotificationCompatMessagingStyleToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// ExtractMessagingStyleFromNotification calls androidx.core.app.NotificationCompat$MessagingStyle.extractMessagingStyleFromNotification.
func (m *NotificationCompatMessagingStyle) ExtractMessagingStyleFromNotification(arg0 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midNotificationCompatMessagingStyleExtractMessagingStyleFromNotification == nil {
			callErr = fmt.Errorf("androidx.core.app.NotificationCompat$MessagingStyle.extractMessagingStyleFromNotification is not available on this device")
			return callErr
		}

		result, callErr = env.CallStaticObjectMethod(
			(*jni.Class)(unsafe.Pointer(clsNotificationCompatMessagingStyle)),
			midNotificationCompatMessagingStyleExtractMessagingStyleFromNotification, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}
