// Code generated by javagen. DO NOT EDIT.

package utils

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// SplineSet wraps androidx.constraintlayout.core.motion.utils.SplineSet.
type SplineSet struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// SetProperty calls androidx.constraintlayout.core.motion.utils.SplineSet.setProperty.
func (m *SplineSet) SetProperty(arg0 *jni.Object, arg1 float32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSplineSetSetProperty == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.core.motion.utils.SplineSet.setProperty is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midSplineSetSetProperty, jni.ObjectValue(arg0), jni.FloatValue(arg1),
		)
		return callErr
	})
	return callErr
}

// ToString calls androidx.constraintlayout.core.motion.utils.SplineSet.toString.
func (m *SplineSet) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSplineSetToString == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.core.motion.utils.SplineSet.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midSplineSetToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// SetType calls androidx.constraintlayout.core.motion.utils.SplineSet.setType.
func (m *SplineSet) SetType(arg0 string) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSplineSetSetType == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.core.motion.utils.SplineSet.setType is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		callErr = env.CallVoidMethod(
			m.Obj,
			midSplineSetSetType, jni.ObjectValue(&jArg0.Object),
		)
		return callErr
	})
	return callErr
}

// Get calls androidx.constraintlayout.core.motion.utils.SplineSet.get.
func (m *SplineSet) Get(arg0 float32) (float32, error) {
	var result float32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSplineSetGet == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.core.motion.utils.SplineSet.get is not available on this device")
			return callErr
		}

		result, callErr = env.CallFloatMethod(
			m.Obj,
			midSplineSetGet, jni.FloatValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetSlope calls androidx.constraintlayout.core.motion.utils.SplineSet.getSlope.
func (m *SplineSet) GetSlope(arg0 float32) (float32, error) {
	var result float32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSplineSetGetSlope == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.core.motion.utils.SplineSet.getSlope is not available on this device")
			return callErr
		}

		result, callErr = env.CallFloatMethod(
			m.Obj,
			midSplineSetGetSlope, jni.FloatValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetCurveFit calls androidx.constraintlayout.core.motion.utils.SplineSet.getCurveFit.
func (m *SplineSet) GetCurveFit() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSplineSetGetCurveFit == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.core.motion.utils.SplineSet.getCurveFit is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midSplineSetGetCurveFit,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetPoint calls androidx.constraintlayout.core.motion.utils.SplineSet.setPoint.
func (m *SplineSet) SetPoint(arg0 int32, arg1 float32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSplineSetSetPoint == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.core.motion.utils.SplineSet.setPoint is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midSplineSetSetPoint, jni.IntValue(arg0), jni.FloatValue(arg1),
		)
		return callErr
	})
	return callErr
}

// Setup calls androidx.constraintlayout.core.motion.utils.SplineSet.setup.
func (m *SplineSet) Setup(arg0 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSplineSetSetup == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.core.motion.utils.SplineSet.setup is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midSplineSetSetup, jni.IntValue(arg0),
		)
		return callErr
	})
	return callErr
}

// MakeCustomSpline calls androidx.constraintlayout.core.motion.utils.SplineSet.makeCustomSpline.
func (m *SplineSet) MakeCustomSpline(arg0 string, arg1 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSplineSetMakeCustomSpline == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.core.motion.utils.SplineSet.makeCustomSpline is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		result, callErr = env.CallStaticObjectMethod(
			(*jni.Class)(unsafe.Pointer(clsSplineSet)),
			midSplineSetMakeCustomSpline, jni.ObjectValue(&jArg0.Object), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// MakeCustomSplineSet calls androidx.constraintlayout.core.motion.utils.SplineSet.makeCustomSplineSet.
func (m *SplineSet) MakeCustomSplineSet(arg0 string, arg1 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSplineSetMakeCustomSplineSet == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.core.motion.utils.SplineSet.makeCustomSplineSet is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		result, callErr = env.CallStaticObjectMethod(
			(*jni.Class)(unsafe.Pointer(clsSplineSet)),
			midSplineSetMakeCustomSplineSet, jni.ObjectValue(&jArg0.Object), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// MakeSpline calls androidx.constraintlayout.core.motion.utils.SplineSet.makeSpline.
func (m *SplineSet) MakeSpline(arg0 string, arg1 int64) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSplineSetMakeSpline == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.core.motion.utils.SplineSet.makeSpline is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		result, callErr = env.CallStaticObjectMethod(
			(*jni.Class)(unsafe.Pointer(clsSplineSet)),
			midSplineSetMakeSpline, jni.ObjectValue(&jArg0.Object), jni.LongValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}
