// Code generated by javagen. DO NOT EDIT.

package utils

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// TypedValuesPositionType wraps androidx.constraintlayout.core.motion.utils.TypedValues$PositionType.
type TypedValuesPositionType struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// ToString calls androidx.constraintlayout.core.motion.utils.TypedValues$PositionType.toString.
func (m *TypedValuesPositionType) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midTypedValuesPositionTypeToString == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.core.motion.utils.TypedValues$PositionType.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midTypedValuesPositionTypeToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// GetId calls androidx.constraintlayout.core.motion.utils.TypedValues$PositionType.getId.
func (m *TypedValuesPositionType) GetId(arg0 string) (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midTypedValuesPositionTypeGetId == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.core.motion.utils.TypedValues$PositionType.getId is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		result, callErr = env.CallStaticIntMethod(
			(*jni.Class)(unsafe.Pointer(clsTypedValuesPositionType)),
			midTypedValuesPositionTypeGetId, jni.ObjectValue(&jArg0.Object),
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetType calls androidx.constraintlayout.core.motion.utils.TypedValues$PositionType.getType.
func (m *TypedValuesPositionType) GetType(arg0 int32) (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midTypedValuesPositionTypeGetType == nil {
			callErr = fmt.Errorf("androidx.constraintlayout.core.motion.utils.TypedValues$PositionType.getType is not available on this device")
			return callErr
		}

		result, callErr = env.CallStaticIntMethod(
			(*jni.Class)(unsafe.Pointer(clsTypedValuesPositionType)),
			midTypedValuesPositionTypeGetType, jni.IntValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}
