// Code generated by javagen. DO NOT EDIT.

package center.dx.jni.generated;

import android.view.WindowInsetsAnimation$Callback;
import center.dx.jni.internal.GoAbstractDispatch;

public class WindowInsetsAnimation$CallbackAdapter extends android.view.WindowInsetsAnimation$Callback {
    private final long handlerID;

    public WindowInsetsAnimation$CallbackAdapter(long handlerID) {
        this.handlerID = handlerID;
    }

    @Override
    public int getDispatchMode() {
        return (Integer) GoAbstractDispatch.invoke(
            handlerID, "getDispatchMode", new Object[]{  }).intValue();
    }

    @Override
    public void onEnd(android.view.WindowInsetsAnimation arg0) {
        GoAbstractDispatch.invoke(
            handlerID, "onEnd", new Object[]{ arg0 });
    }

    @Override
    public void onPrepare(android.view.WindowInsetsAnimation arg0) {
        GoAbstractDispatch.invoke(
            handlerID, "onPrepare", new Object[]{ arg0 });
    }

    @Override
    public android.view.WindowInsetsAnimation$Bounds onStart(android.view.WindowInsetsAnimation arg0, android.view.WindowInsetsAnimation$Bounds arg1) {
        return (android.view.WindowInsetsAnimation$Bounds) GoAbstractDispatch.invoke(
            handlerID, "onStart", new Object[]{ arg0, arg1 });
    }
}
