// Code generated by javagen. DO NOT EDIT.

package identity

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// PersonalizationDataBuilder wraps android.security.identity.PersonalizationData$Builder.
type PersonalizationDataBuilder struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// NewPersonalizationDataBuilder creates a new android.security.identity.PersonalizationData$Builder instance.
func NewPersonalizationDataBuilder(vm *jni.VM) (*PersonalizationDataBuilder, error) {
	var t PersonalizationDataBuilder
	t.VM = vm

	err := vm.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			return err
		}
		if clsPersonalizationDataBuilder == nil {
			return fmt.Errorf("android.security.identity.PersonalizationData$Builder is not available on this device")
		}
		if midPersonalizationDataBuilderCtor == nil {
			return fmt.Errorf("android.security.identity.PersonalizationData$Builder constructor ()V is not available on this device")
		}
		obj, err := env.NewObject((*jni.Class)(unsafe.Pointer(clsPersonalizationDataBuilder)), midPersonalizationDataBuilderCtor)
		if err != nil {
			return err
		}
		t.Obj = env.NewGlobalRef(obj)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// AddAccessControlProfile calls android.security.identity.PersonalizationData$Builder.addAccessControlProfile.
func (m *PersonalizationDataBuilder) AddAccessControlProfile(arg0 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPersonalizationDataBuilderAddAccessControlProfile == nil {
			callErr = fmt.Errorf("android.security.identity.PersonalizationData$Builder.addAccessControlProfile is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midPersonalizationDataBuilderAddAccessControlProfile, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// Build calls android.security.identity.PersonalizationData$Builder.build.
func (m *PersonalizationDataBuilder) Build() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPersonalizationDataBuilderBuild == nil {
			callErr = fmt.Errorf("android.security.identity.PersonalizationData$Builder.build is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midPersonalizationDataBuilderBuild,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// ToString calls android.security.identity.PersonalizationData$Builder.toString.
func (m *PersonalizationDataBuilder) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPersonalizationDataBuilderToString == nil {
			callErr = fmt.Errorf("android.security.identity.PersonalizationData$Builder.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midPersonalizationDataBuilderToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
