// Code generated by javagen. DO NOT EDIT.

package contentcapture

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// DataRemovalRequest wraps android.view.contentcapture.DataRemovalRequest.
type DataRemovalRequest struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// DescribeContents calls android.view.contentcapture.DataRemovalRequest.describeContents.
func (m *DataRemovalRequest) DescribeContents() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDataRemovalRequestDescribeContents == nil {
			callErr = fmt.Errorf("android.view.contentcapture.DataRemovalRequest.describeContents is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midDataRemovalRequestDescribeContents,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetLocusIdRequests calls android.view.contentcapture.DataRemovalRequest.getLocusIdRequests.
func (m *DataRemovalRequest) GetLocusIdRequests() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDataRemovalRequestGetLocusIdRequests == nil {
			callErr = fmt.Errorf("android.view.contentcapture.DataRemovalRequest.getLocusIdRequests is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midDataRemovalRequestGetLocusIdRequests,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetPackageName calls android.view.contentcapture.DataRemovalRequest.getPackageName.
func (m *DataRemovalRequest) GetPackageName() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDataRemovalRequestGetPackageName == nil {
			callErr = fmt.Errorf("android.view.contentcapture.DataRemovalRequest.getPackageName is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midDataRemovalRequestGetPackageName,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// IsForEverything calls android.view.contentcapture.DataRemovalRequest.isForEverything.
func (m *DataRemovalRequest) IsForEverything() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDataRemovalRequestIsForEverything == nil {
			callErr = fmt.Errorf("android.view.contentcapture.DataRemovalRequest.isForEverything is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midDataRemovalRequestIsForEverything,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// ToString calls android.view.contentcapture.DataRemovalRequest.toString.
func (m *DataRemovalRequest) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDataRemovalRequestToString == nil {
			callErr = fmt.Errorf("android.view.contentcapture.DataRemovalRequest.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midDataRemovalRequestToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// WriteToParcel calls android.view.contentcapture.DataRemovalRequest.writeToParcel.
func (m *DataRemovalRequest) WriteToParcel(arg0 *jni.Object, arg1 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDataRemovalRequestWriteToParcel == nil {
			callErr = fmt.Errorf("android.view.contentcapture.DataRemovalRequest.writeToParcel is not available on this device")
			return callErr
		}

		callErr = env.CallStaticVoidMethod(
			(*jni.Class)(unsafe.Pointer(clsDataRemovalRequest)),
			midDataRemovalRequestWriteToParcel, jni.ObjectValue(arg0), jni.IntValue(arg1),
		)
		return callErr
	})
	return callErr
}
