// Code generated by javagen. DO NOT EDIT.

package contentcapture

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// DataRemovalRequestBuilder wraps android.view.contentcapture.DataRemovalRequest$Builder.
type DataRemovalRequestBuilder struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// NewDataRemovalRequestBuilder creates a new android.view.contentcapture.DataRemovalRequest$Builder instance.
func NewDataRemovalRequestBuilder(vm *jni.VM) (*DataRemovalRequestBuilder, error) {
	var t DataRemovalRequestBuilder
	t.VM = vm

	err := vm.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			return err
		}
		if clsDataRemovalRequestBuilder == nil {
			return fmt.Errorf("android.view.contentcapture.DataRemovalRequest$Builder is not available on this device")
		}
		if midDataRemovalRequestBuilderCtor == nil {
			return fmt.Errorf("android.view.contentcapture.DataRemovalRequest$Builder constructor ()V is not available on this device")
		}
		obj, err := env.NewObject((*jni.Class)(unsafe.Pointer(clsDataRemovalRequestBuilder)), midDataRemovalRequestBuilderCtor)
		if err != nil {
			return err
		}
		t.Obj = env.NewGlobalRef(obj)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// AddLocusId calls android.view.contentcapture.DataRemovalRequest$Builder.addLocusId.
func (m *DataRemovalRequestBuilder) AddLocusId(arg0 *jni.Object, arg1 int32) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDataRemovalRequestBuilderAddLocusId == nil {
			callErr = fmt.Errorf("android.view.contentcapture.DataRemovalRequest$Builder.addLocusId is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midDataRemovalRequestBuilderAddLocusId, jni.ObjectValue(arg0), jni.IntValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// Build calls android.view.contentcapture.DataRemovalRequest$Builder.build.
func (m *DataRemovalRequestBuilder) Build() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDataRemovalRequestBuilderBuild == nil {
			callErr = fmt.Errorf("android.view.contentcapture.DataRemovalRequest$Builder.build is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midDataRemovalRequestBuilderBuild,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// ForEverything calls android.view.contentcapture.DataRemovalRequest$Builder.forEverything.
func (m *DataRemovalRequestBuilder) ForEverything() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDataRemovalRequestBuilderForEverything == nil {
			callErr = fmt.Errorf("android.view.contentcapture.DataRemovalRequest$Builder.forEverything is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midDataRemovalRequestBuilderForEverything,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// ToString calls android.view.contentcapture.DataRemovalRequest$Builder.toString.
func (m *DataRemovalRequestBuilder) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDataRemovalRequestBuilderToString == nil {
			callErr = fmt.Errorf("android.view.contentcapture.DataRemovalRequest$Builder.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midDataRemovalRequestBuilderToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
