// Code generated by javagen. DO NOT EDIT.

package drm

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// StorePlayback wraps android.drm.DrmStore$Playback.
type StorePlayback struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// NewStorePlayback creates a new android.drm.DrmStore$Playback instance.
func NewStorePlayback(vm *jni.VM) (*StorePlayback, error) {
	var t StorePlayback
	t.VM = vm

	err := vm.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			return err
		}
		if clsStorePlayback == nil {
			return fmt.Errorf("android.drm.DrmStore$Playback is not available on this device")
		}
		if midStorePlaybackCtor == nil {
			return fmt.Errorf("android.drm.DrmStore$Playback constructor ()V is not available on this device")
		}
		obj, err := env.NewObject((*jni.Class)(unsafe.Pointer(clsStorePlayback)), midStorePlaybackCtor)
		if err != nil {
			return err
		}
		t.Obj = env.NewGlobalRef(obj)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// ToString calls android.drm.DrmStore$Playback.toString.
func (m *StorePlayback) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midStorePlaybackToString == nil {
			callErr = fmt.Errorf("android.drm.DrmStore$Playback.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midStorePlaybackToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
