// Code generated by javagen. DO NOT EDIT.

package voice

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// InteractionSessionInsets wraps android.service.voice.VoiceInteractionSession$Insets.
type InteractionSessionInsets struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// NewInteractionSessionInsets creates a new android.service.voice.VoiceInteractionSession$Insets instance.
func NewInteractionSessionInsets(vm *jni.VM) (*InteractionSessionInsets, error) {
	var t InteractionSessionInsets
	t.VM = vm

	err := vm.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			return err
		}
		if clsInteractionSessionInsets == nil {
			return fmt.Errorf("android.service.voice.VoiceInteractionSession$Insets is not available on this device")
		}
		if midInteractionSessionInsetsCtor == nil {
			return fmt.Errorf("android.service.voice.VoiceInteractionSession$Insets constructor ()V is not available on this device")
		}
		obj, err := env.NewObject((*jni.Class)(unsafe.Pointer(clsInteractionSessionInsets)), midInteractionSessionInsetsCtor)
		if err != nil {
			return err
		}
		t.Obj = env.NewGlobalRef(obj)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// ToString calls android.service.voice.VoiceInteractionSession$Insets.toString.
func (m *InteractionSessionInsets) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midInteractionSessionInsetsToString == nil {
			callErr = fmt.Errorf("android.service.voice.VoiceInteractionSession$Insets.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midInteractionSessionInsetsToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
