// Code generated by javagen. DO NOT EDIT.

package rtt

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// ResponderConfigBuilder wraps android.net.wifi.rtt.ResponderConfig$Builder.
type ResponderConfigBuilder struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// NewResponderConfigBuilder creates a new android.net.wifi.rtt.ResponderConfig$Builder instance.
func NewResponderConfigBuilder(vm *jni.VM) (*ResponderConfigBuilder, error) {
	var t ResponderConfigBuilder
	t.VM = vm

	err := vm.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			return err
		}
		if clsResponderConfigBuilder == nil {
			return fmt.Errorf("android.net.wifi.rtt.ResponderConfig$Builder is not available on this device")
		}
		if midResponderConfigBuilderCtor == nil {
			return fmt.Errorf("android.net.wifi.rtt.ResponderConfig$Builder constructor ()V is not available on this device")
		}
		obj, err := env.NewObject((*jni.Class)(unsafe.Pointer(clsResponderConfigBuilder)), midResponderConfigBuilderCtor)
		if err != nil {
			return err
		}
		t.Obj = env.NewGlobalRef(obj)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// Build calls android.net.wifi.rtt.ResponderConfig$Builder.build.
func (m *ResponderConfigBuilder) Build() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midResponderConfigBuilderBuild == nil {
			callErr = fmt.Errorf("android.net.wifi.rtt.ResponderConfig$Builder.build is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midResponderConfigBuilderBuild,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// Set80211azNtbSupported calls android.net.wifi.rtt.ResponderConfig$Builder.set80211azNtbSupported.
func (m *ResponderConfigBuilder) Set80211azNtbSupported(arg0 bool) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midResponderConfigBuilderSet80211azNtbSupported == nil {
			callErr = fmt.Errorf("android.net.wifi.rtt.ResponderConfig$Builder.set80211azNtbSupported is not available on this device")
			return callErr
		}
		var jArg0 uint8
		if arg0 {
			jArg0 = jniTrue
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midResponderConfigBuilderSet80211azNtbSupported, jni.BooleanValue(jArg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// Set80211mcSupported calls android.net.wifi.rtt.ResponderConfig$Builder.set80211mcSupported.
func (m *ResponderConfigBuilder) Set80211mcSupported(arg0 bool) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midResponderConfigBuilderSet80211mcSupported == nil {
			callErr = fmt.Errorf("android.net.wifi.rtt.ResponderConfig$Builder.set80211mcSupported is not available on this device")
			return callErr
		}
		var jArg0 uint8
		if arg0 {
			jArg0 = jniTrue
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midResponderConfigBuilderSet80211mcSupported, jni.BooleanValue(jArg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetCenterFreq0Mhz calls android.net.wifi.rtt.ResponderConfig$Builder.setCenterFreq0Mhz.
func (m *ResponderConfigBuilder) SetCenterFreq0Mhz(arg0 int32) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midResponderConfigBuilderSetCenterFreq0Mhz == nil {
			callErr = fmt.Errorf("android.net.wifi.rtt.ResponderConfig$Builder.setCenterFreq0Mhz is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midResponderConfigBuilderSetCenterFreq0Mhz, jni.IntValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetCenterFreq1Mhz calls android.net.wifi.rtt.ResponderConfig$Builder.setCenterFreq1Mhz.
func (m *ResponderConfigBuilder) SetCenterFreq1Mhz(arg0 int32) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midResponderConfigBuilderSetCenterFreq1Mhz == nil {
			callErr = fmt.Errorf("android.net.wifi.rtt.ResponderConfig$Builder.setCenterFreq1Mhz is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midResponderConfigBuilderSetCenterFreq1Mhz, jni.IntValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetChannelWidth calls android.net.wifi.rtt.ResponderConfig$Builder.setChannelWidth.
func (m *ResponderConfigBuilder) SetChannelWidth(arg0 int32) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midResponderConfigBuilderSetChannelWidth == nil {
			callErr = fmt.Errorf("android.net.wifi.rtt.ResponderConfig$Builder.setChannelWidth is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midResponderConfigBuilderSetChannelWidth, jni.IntValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetFrequencyMhz calls android.net.wifi.rtt.ResponderConfig$Builder.setFrequencyMhz.
func (m *ResponderConfigBuilder) SetFrequencyMhz(arg0 int32) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midResponderConfigBuilderSetFrequencyMhz == nil {
			callErr = fmt.Errorf("android.net.wifi.rtt.ResponderConfig$Builder.setFrequencyMhz is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midResponderConfigBuilderSetFrequencyMhz, jni.IntValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetMacAddress calls android.net.wifi.rtt.ResponderConfig$Builder.setMacAddress.
func (m *ResponderConfigBuilder) SetMacAddress(arg0 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midResponderConfigBuilderSetMacAddress == nil {
			callErr = fmt.Errorf("android.net.wifi.rtt.ResponderConfig$Builder.setMacAddress is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midResponderConfigBuilderSetMacAddress, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetPreamble calls android.net.wifi.rtt.ResponderConfig$Builder.setPreamble.
func (m *ResponderConfigBuilder) SetPreamble(arg0 int32) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midResponderConfigBuilderSetPreamble == nil {
			callErr = fmt.Errorf("android.net.wifi.rtt.ResponderConfig$Builder.setPreamble is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midResponderConfigBuilderSetPreamble, jni.IntValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetResponderType calls android.net.wifi.rtt.ResponderConfig$Builder.setResponderType.
func (m *ResponderConfigBuilder) SetResponderType(arg0 int32) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midResponderConfigBuilderSetResponderType == nil {
			callErr = fmt.Errorf("android.net.wifi.rtt.ResponderConfig$Builder.setResponderType is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midResponderConfigBuilderSetResponderType, jni.IntValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetSecureRangingConfig calls android.net.wifi.rtt.ResponderConfig$Builder.setSecureRangingConfig.
func (m *ResponderConfigBuilder) SetSecureRangingConfig(arg0 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midResponderConfigBuilderSetSecureRangingConfig == nil {
			callErr = fmt.Errorf("android.net.wifi.rtt.ResponderConfig$Builder.setSecureRangingConfig is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midResponderConfigBuilderSetSecureRangingConfig, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// ToString calls android.net.wifi.rtt.ResponderConfig$Builder.toString.
func (m *ResponderConfigBuilder) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midResponderConfigBuilderToString == nil {
			callErr = fmt.Errorf("android.net.wifi.rtt.ResponderConfig$Builder.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midResponderConfigBuilderToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
