// Code generated by javagen. DO NOT EDIT.

package view

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// DragEvent wraps android.view.DragEvent.
type DragEvent struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// DescribeContents calls android.view.DragEvent.describeContents.
func (m *DragEvent) DescribeContents() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDragEventDescribeContents == nil {
			callErr = fmt.Errorf("android.view.DragEvent.describeContents is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midDragEventDescribeContents,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetAction calls android.view.DragEvent.getAction.
func (m *DragEvent) GetAction() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDragEventGetAction == nil {
			callErr = fmt.Errorf("android.view.DragEvent.getAction is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midDragEventGetAction,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetClipData calls android.view.DragEvent.getClipData.
func (m *DragEvent) GetClipData() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDragEventGetClipData == nil {
			callErr = fmt.Errorf("android.view.DragEvent.getClipData is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midDragEventGetClipData,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetClipDescription calls android.view.DragEvent.getClipDescription.
func (m *DragEvent) GetClipDescription() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDragEventGetClipDescription == nil {
			callErr = fmt.Errorf("android.view.DragEvent.getClipDescription is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midDragEventGetClipDescription,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetLocalState calls android.view.DragEvent.getLocalState.
func (m *DragEvent) GetLocalState() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDragEventGetLocalState == nil {
			callErr = fmt.Errorf("android.view.DragEvent.getLocalState is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midDragEventGetLocalState,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetResult calls android.view.DragEvent.getResult.
func (m *DragEvent) GetResult() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDragEventGetResult == nil {
			callErr = fmt.Errorf("android.view.DragEvent.getResult is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midDragEventGetResult,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// GetX calls android.view.DragEvent.getX.
func (m *DragEvent) GetX() (float32, error) {
	var result float32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDragEventGetX == nil {
			callErr = fmt.Errorf("android.view.DragEvent.getX is not available on this device")
			return callErr
		}
		result, callErr = env.CallFloatMethod(
			m.Obj,
			midDragEventGetX,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetY calls android.view.DragEvent.getY.
func (m *DragEvent) GetY() (float32, error) {
	var result float32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDragEventGetY == nil {
			callErr = fmt.Errorf("android.view.DragEvent.getY is not available on this device")
			return callErr
		}
		result, callErr = env.CallFloatMethod(
			m.Obj,
			midDragEventGetY,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// ToString calls android.view.DragEvent.toString.
func (m *DragEvent) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDragEventToString == nil {
			callErr = fmt.Errorf("android.view.DragEvent.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midDragEventToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// WriteToParcel calls android.view.DragEvent.writeToParcel.
func (m *DragEvent) WriteToParcel(arg0 *jni.Object, arg1 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDragEventWriteToParcel == nil {
			callErr = fmt.Errorf("android.view.DragEvent.writeToParcel is not available on this device")
			return callErr
		}

		callErr = env.CallStaticVoidMethod(
			(*jni.Class)(unsafe.Pointer(clsDragEvent)),
			midDragEventWriteToParcel, jni.ObjectValue(arg0), jni.IntValue(arg1),
		)
		return callErr
	})
	return callErr
}
